### ISSUE TITLE
Symfony 2.8: YML linking to methods not working anymore, went back to 0.14.146

### ISSUE THREAD

**Issue by oliveru** [Haehnchen/idea-php-symfony2-plugin#1003]
Symfony 2.8: In yml - files, can't click on controllers e.g. to jump to that method. 

Went back to version 0.14.146 (since collegue is still using that version, both on the newest PHPStorm). Now it is working again.

0.14.150 does not work.

**Comment by Haehnchen** [comment]
maybe #995 ?

**Comment by oliveru** [comment]
Yes thanks! With 0.14.151 it is working again.
