### ISSUE TITLE
Disable CaseSensitivityServiceInspection

### ISSUE THREAD

**Issue by zanardigit** [Haehnchen/idea-php-symfony2-plugin#1008]
The latest best practices for Symfony suggest to use the FQDN class name of service as its id, to facilitate autowiring. See https://symfony.com/doc/current/best_practices/business-logic.html#services-naming-and-format.

Thus, the CaseSensitivityServiceInspection is no longer actually needed (and probably a new inspection should be provided to suggest using the FQDN name).

Thank you very much for your useful plugin!

**Comment by stof** [comment]
Using the FQCN is not a requirement at all, and there are still valid cases to use a different one. So I would not add an inspection enforcing it.

**Comment by zanardigit** [comment]
@stof thank you for your feedback. The original point of my issue still stands: the plugin currently reports as "wrong" a service id like `AppBundle\Service\MyCustomService` due to the use of capital letters; but this is actually the current suggested best practice. So IMHO the `CaseSensitivityServiceInspection` should be removed.

**Comment by stof** [comment]
@zanardigit I have lots of services using FQCN, and I don't get any such warning from the inspection. Are you sure you are using the latest version of the plugin (you need to be using at least 0.14.147)

**Comment by zanardigit** [comment]
I am using 0.14.150. The warning appears when using service in controller. See attached image.
![phpstorm-warning](https://user-images.githubusercontent.com/2579986/29807087-8de5c2a8-8c92-11e7-9f07-d40c0fc61fb5.png)

**Comment by stof** [comment]
ah, I'm not using this case, indeed.

@Haehnchen the inspection should be changed depending on the Symfony version:

- for 3.2 and older, it should recommend using lowercase
- for 3.3+, it should recommend using the same case than when defining the service (this is the optimized path, and the non-deprecated path)
- for 4.0+, it should be disabled (and the inspection about unknown public services should check existence in a case sensitive way)

**Comment by stof** [comment]
@Haehnchen this issue should be added to the list of tasks needed for proper Symfony 4 support.

**Comment by cedricziel** [comment]
@zanardigit I'm fixing the false positive, but you might consider using FQCNs through class constants (`My\App\Service::class`) anyways.

**Comment by cedricziel** [comment]
Thanks for your quick answer! - Yes, I'm suggesting that. The value is the same :)

This will disable the inspection, because it only inspects PHP strings on the `ContainerInterface::get` part.

**Comment by zanardigit** [comment]
Sorry I did not reply earlier. Your suggestion did in fact fix my problem.
