### ISSUE TITLE
Plugin does not suggest classes for anonymous services

### ISSUE THREAD

**Issue by simPod** [Haehnchen/idea-php-symfony2-plugin#1021]
I'm trying to get the plugin suggest me the class name when registering anonymous service in Symfony 3.3. However, it says `No Suggestions`. 

The thing is that few times I have seen it suggest it for me so I suppose I'm doing something wrong becase the feature is there (?).

![image](https://user-images.githubusercontent.com/327717/30431055-a0f2a276-995d-11e7-9a08-b9b462ed116d.png)

**Comment by Koc** [comment]
duplicates #595

**Comment by simPod** [comment]
Forgot about this, found a way to get it working.

Just start with `:`, move cursor before it and start typing.
