### ISSUE TITLE
Doctrine repository function are not autocompleted

### ISSUE THREAD

**Issue by wallish** [Haehnchen/idea-php-symfony2-plugin#1038]
Phpstorm version: 2016.2.4
Plugin version: 0.14.155

All functions in the repository are not autocompleted, even when i use cmd + click (goto) and of course the functions are working.

```php
// in articles entity
/**
 * Articles
 *
 * @ORM\Table(name="articles")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ArticlesRepository")
 */
class Articles
{
```
```php
// in my repository
class ArticlesRepository extends EntityRepository
{
    public function findLastest(){}
```

```php
// in my controller
$em = $this->getDoctrine()->getManager();
$articles = $em->getRepository('AppBundle:Articles')->findLastest();
```

Here some screenshots \:

<img width="560" alt="capture d ecran 2017-10-07 a 13 00 09" src="https://user-images.githubusercontent.com/5347276/31307232-e6be6632-ab5f-11e7-9461-9629b51d8b4b.png">
<img width="837" alt="capture d ecran 2017-10-07 a 13 02 53" src="https://user-images.githubusercontent.com/5347276/31307236-f86b5246-ab5f-11e7-9018-5e95d444f16a.png">

<img width="525" alt="capture d ecran 2017-10-07 a 13 00 25" src="https://user-images.githubusercontent.com/5347276/31307235-f0e48222-ab5f-11e7-8b0e-bfffc6e9afec.png">

**Comment by wallish** [comment]
Talking about this features #25

**Comment by Koc** [comment]
Possible duplicate of #981

**Comment by wallish** [comment]
Tried to rollback to phpstorm 2017.1.4 and it's same

**Comment by wallish** [comment]
I got this issue because i opened the project with a parent directory like `project/{a folder}/{root of symfony project}`

If i open the project directly from {a folder} it's working.

There is a way to specific the symfony root project ?

**Comment by northorchid** [comment]
you can set the symfony root directory 
![image](https://user-images.githubusercontent.com/1713140/33534914-6c7354ba-d8e5-11e7-914e-4d9c6107b122.png)

**Comment by wallish** [comment]
You are my hero, i didnt search enough deeply. Thx !
