### ISSUE TITLE
Binary incompatibility of plugin with upcoming IntelliJ IDEA 2017.3 EAP

### ISSUE THREAD

**Issue by tejksat** [Haehnchen/idea-php-symfony2-plugin#1040]
The return type of the method `com.jetbrains.plugins.webDeployment.ConnectionOwnerFactory#createConnectionOwner(com.intellij.openapi.project.Project)` changed --- `com.jetbrains.plugins.webDeployment.ConnectionOwner` moved to `com.intellij.ssh.interaction` package.

The source code of the plugin does not require to be changed but the plugin requires to be rebuilt because of binary incompatibility.

The next IntelliJ IDEA 2017.3 EAP is going to be released this week.

**Comment by Haehnchen** [comment]
thank you. plugin prepared
