### ISSUE TITLE
Completion for variables of template rendering

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#1052]
Provide completion for template rendering parameter

```php
foobar('foo.html.twig', [
  'foobar' => ...
]);
```

```twig
{{ foobar }}
{% if foobar %}
...
```

**Comment by pueppiblue** [comment]
0.15.159 broke autocomplete for template parameters
```
 # someController
return $this->render(foo/bar.html.twig', array(
            'foo' => $foo
        ));
```
```
# bar.html.twig
{{ foo }}
```
* foo does not autocomplete itself nor provide any methods or its type.
* Noticed that on PhpStorm 2017.3 EAP after plugin update.
* Went to 2017.2.4 to double-check this (still with older plugin version installed):
{{ foo }} worked as intended alas twig global {{ app }} did not.
* updated symfony plugin on 2017.2.4 => no autocompletion for {{ foo }} either

**Comment by pueppiblue** [comment]
Narrowed it to symfony: "3.3.*"
On 2.8 for example, it still works.

**Comment by Haehnchen** [comment]
so should be fixed in next release including: https://github.com/Haehnchen/idea-php-symfony2-plugin/commit/beb0da7d4c591a225a40141322df3e86de110688
