### ISSUE TITLE
Code navigation to parent twig when using twig paths

### ISSUE THREAD

**Issue by samimussbach** [Haehnchen/idea-php-symfony2-plugin#1055]
When using twig paths like
```
twig:
    paths:
        '%kernel.root_dir%/../MyBundle/Resources/views': 'MyBundleParent'
```
and referencing in twig with
```
{% extends '@MyBundleParent/User/newUser.html.twig' %}
```
it is not possible to navigate via strg+click. It would be awesome, if this would also be possible.

**Comment by Haehnchen** [comment]
implemented via https://github.com/Haehnchen/idea-php-symfony2-plugin/blob/master/src/fr/adrienbrault/idea/symfony2plugin/templating/path/ConfigAddPathTwigNamespaces.java
