### ISSUE TITLE
IDE Fatal Error

### ISSUE THREAD

**Issue by Lehj14** [Haehnchen/idea-php-symfony2-plugin#1066]
Hi I am trying to create a symfony project using phpstrom 2017.2.4 and I am getting the following error:
![selection_039](https://user-images.githubusercontent.com/5898005/32148565-03d1d892-bcf1-11e7-805a-69debc54b6e1.png)

**Comment by cedricziel** [comment]
Hi, I'm currently harvesting old issues. Is this still a current problem?

**Comment by Lehj14** [comment]
Hi, Sorry. Nope. But i am getting a new issue which i posted on a diff issue.
