### ISSUE TITLE
Routing: Add completion and inspection for '_fragment' param

### ISSUE THREAD

**Issue by cedricziel** [Haehnchen/idea-php-symfony2-plugin#1071]
It would be great if we could have the always available `_fragment` routing parameter (Symfony 3.2, https://symfony.com/blog/new-in-symfony-3-2-routing-improvements#added-support-for-url-fragments) and validate the fragment value for `#`es.

Example: 

```
// example.com/admin/company/4711/customer#tab-users

return $this->redirectToRoute('foo_admin_company_customer_list', [
                'companyId' => $company->getId(),
                '_fragment' => 'tab-users',
            ]);
```

Validation for the inspection would need to check for absence of '#' character.

If you could tell me where this is placed best, i'd implement it mysql and send you a PR :)

**Comment by Haehnchen** [comment]
Its just one line for all Route Parameters eg PHP, Twig, ... :)
`fr.adrienbrault.idea.symfony2plugin.routing.RouteHelper#getRouteParameterLookupElements`
