### ISSUE TITLE
Template name generation changed in SensioFrameworkExtraBundle

### ISSUE THREAD

**Issue by bobvandevijver** [Haehnchen/idea-php-symfony2-plugin#1082]
In version 4.0 from SensioFrameworkExtraBundle the template name generation changed from camelCase to under_score (see [changelog](https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/CHANGELOG.md)).

For example, before the update it was:
`WespAdminBundle:authentication:verifyEmail.html.twig`  
and now it is 
`WespAdminBundle:authentication:verify_email.html.twig`. 

This unfortunately breaks the `@Template` annotation support, so I hope this can be updated.

**Comment by King2500** [comment]
@bobvandevijver I'm curious what the reason was behind this change. Any issue link on discussion?

**Comment by bobvandevijver** [comment]
The use of camelCase for file names does not adhere to the Symfony conventions, as mentioned in https://github.com/sensiolabs/SensioFrameworkExtraBundle/issues/303. 

It was changed with https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/508 without to many details on it. It is a large BC-break, so I do not really understand why this was changed so easily...

**Comment by Jean85** [comment]
It's a BC change over a major version change of the Bundle, so it's allowed.

Yes, it's pretty annoying to fix an existing project that relies on this, still...
