### ISSUE TITLE
Plugin adds empty menu "Other"

### ISSUE THREAD

**Issue by King2500** [Haehnchen/idea-php-symfony2-plugin#1093]
There is an empty menu "Other":

![image](https://user-images.githubusercontent.com/4896363/33441216-73d71ed0-d5f2-11e7-9c42-1eb5f4ff1a4f.png)

After disabling the Symfony plugin this entry disappears.

Source: https://blog.jetbrains.com/phpstorm/2017/11/phpstorm-2017-3-release/#comment-3637962482

**Comment by Koc** [comment]
It allows create web test case for controllers

**Comment by King2500** [comment]
So it appears inside controllers only?

It's annoying in other places / when not working with controllers...

**Comment by Haehnchen** [comment]
```
    [junit] ERROR: fr.adrienbrault.idea.symfony2plugin.action.bundle.WebTestCaseGeneratorAction (SymfonyWebTestCaseGenerator): group with id "PhpUnitNewGroup" isn't registered; action will be added to the "Other" group [Plugin: fr.adrienbrault.idea.symfony2plugin]

    [junit] com.intellij.diagnostic.PluginException: fr.adrienbrault.idea.symfony2plugin.action.bundle.WebTestCaseGeneratorAction (SymfonyWebTestCaseGenerator): group with id "PhpUnitNewGroup" isn't registered; action will be added to the "Other" group [Plugin: fr.adrienbrault.idea.symfony2plugin]
```

**Comment by vaidotas-adf** [comment]
"Other" menu item can be removed from Preferences->Appearance & Behavior -> Menus and Toolbars , Main Menu. Not sure if it will re-appear after plugin update.

**Comment by Haehnchen** [comment]
done, dropped the nesting into PhpUnit menu
