### ISSUE TITLE
Translation auto-complete not working in Symfony Flex directory structure

### ISSUE THREAD

**Issue by DidierLmn** [Haehnchen/idea-php-symfony2-plugin#1096]
- PhpStorm 2017.3
- Symfony Plugin 0.15.160

Translations autocomplete doesn't work with the new directory structure of Symfony 4. The `translations/ ` directory now resides in the root of the project. When setting the **Translation Root Path** in the plugin settings to this folder, the autocomplete still doesn't work.
Moving the `translations/ ` directory back to `src/Resources/translations/ ` and setting that path in the plugin settings does work, but that's not the recommended structure anymore. What's strange is that the settings don't seem to work as intended.

**Comment by Haehnchen** [comment]
thx for this feedback; fixed

**Comment by DidierLmn** [comment]
Thanks for the quick follow-up :)

**Comment by Haehnchen** [comment]
done
