### ISSUE TITLE
Argument for @NotNull parameter 'path'

### ISSUE THREAD

**Issue by vuras** [Haehnchen/idea-php-symfony2-plugin#1135]
Argument for @NotNull parameter 'path' of fr/adrienbrault/idea/symfony2plugin/templating/path/TwigPath.<init> must not be null

It is constantly thhrowing this exception. What can be done to solve it?
 
I think it is related to this. It started to throw error when I added a path to Twig config.
![config](https://user-images.githubusercontent.com/14833197/34516120-2f28de30-f07e-11e7-9c47-8810139e86f3.png)

**Comment by sokrev** [comment]
I encountered the same bug. Problem occurs when path starts with `/` (I'm using linux, not sure if windows has same problem with absolute paths). After saving there is an IDE plugin exception and added entry cannot be removed from settings window (just like on @vuras screenshot).

For now the only way to fix this is either remove added template from `.idea/symfony2.xml` file (looks like this: `<twig_namespace custom="true" namespaceType="ADD_PATH" />`, or set `path` propery by hand in the same place, f.ex. `<twig_namespace custom="true" namespaceType="ADD_PATH" path="/var/www/project/templates" />`.

**Comment by Haehnchen** [comment]
duplicate: https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/1331
