### ISSUE TITLE
@Template annotation generate wrong path

### ISSUE THREAD

**Issue by Holicz** [Haehnchen/idea-php-symfony2-plugin#1138]
When you have controller named with two or more words (e.g. StaticPageController) and use @Template annotation it generated folder StaticPage in views, but Symfony expects static_page.

# Steps to reproduce

1. Create this controller
```
class StaticPageController extends Controller
{
    /**
     * @Route("/about-us", name="about-us")
     * @Template
     */
    public function aboutUsAction()
    {
    }
}
```

2. Use function "Twig: Create Template" (It creates Resources/views/StaticPage/AboutUs.html.twig)
3. Run server
4. Go to address /about-us

# What is the result
Error message "Unable to find template "AppBundle/static_page/about_us.html.twig""

# What should be the result
Plugin should generate folders and files with snake_case, not with camelCase (it is also written [here](http://symfony.com/doc/3.4/best_practices/templates.html) in best practices)

**Comment by ilario-pierbattista** [comment]
Same issue here. Versions of `sensio/framework-extra-bundle` newer than `v3.0.29` use snake case to generate folders.

The behaviour of the generator should take into account the version framework-extra-bundle installed to chose the naming strategy.

**Comment by Haehnchen** [comment]
note same as https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/1082

**Comment by jverdeyen** [comment]
Is there a configuration settings available to use underscore filename resolving with the idea-php-symfony2-plugin?

**Comment by TomasVotruba** [comment]
Fixed by #1389

**Comment by tarjei** [comment]
@TomasVotruba are you sure? If I try to create a template from an annotation, the old CamelCase name is used - what is needed to get a snake_case name instead?

**Comment by TomasVotruba** [comment]
Blast from the past, I have no idea. 

I'd try to add it to `ide-twig.json` ([example](https://github.com/shopware/administration/blob/master/Resources/ide-twig.json)

**Comment by Haehnchen** [comment]
both names are still in, but this automated template is not support by Template attribute at all :)
