### ISSUE TITLE
Support ::class in Doctrine annotations

### ISSUE THREAD

**Issue by julienfalque** [Haehnchen/idea-php-symfony2-plugin#1145]
Hi, not sure this is the right place to submit this, please let me know if I should submit it somewhere else.

When I define the repository class of a Doctrine entity, e.g.:

```php
/**
 * @ORM\Entity(repositoryClass="App\Repository\FooRepository")
 */
class Foo
{
    // ...
}
```

I use to do it with the `::class` notation, which is supported by Doctrine:

```php
use App\Repository\FooRepository;

/**
 * @ORM\Entity(repositoryClass=FooRepository::class)
 */
class Foo
{
    // ...
}
```

When writing the FQCN, the plugin is able to find the custom methods from the repository, but when I use the `::class` notation instead, the plugin does not seem to understand it anymore and marks custom methods as unknown.

**Comment by b1rdex** [comment]
Relates https://github.com/Haehnchen/idea-php-annotation-plugin/issues/104

**Comment by Koc** [comment]
can be closed as duplicate

**Comment by julienfalque** [comment]
Indeed, thanks.
