### ISSUE TITLE
Twig's asset function doesn't show files in public directory on Symfony 4

### ISSUE THREAD

**Issue by Stiiks** [Haehnchen/idea-php-symfony2-plugin#1147]
When using a Symfony 4 project, as the directory structure change, the {{ asset() }} function doesn't suggest files that are in public folder.

**Comment by iSDP** [comment]
Set it in the settings (web -> public)

**Comment by Aerendir** [comment]
Where are exactly those settings?

**Comment by rawburner** [comment]
This solved the issue for me.
settings -> Languages & Frameworks -> PHP -> Symfony -> Web Directory change to "public"

**Comment by cedricziel** [comment]
Detection for new projects should be fixed with #1198
