### ISSUE TITLE
Symfony's new directory structure and the settings.

### ISSUE THREAD

**Issue by Coffee2CodeNL** [Haehnchen/idea-php-symfony2-plugin#1148]
What are the proper settings for the new directory structure?

Translations is now `translations`, easy.
Web directory is now `public`, easy.
App directory is now what exactly? this one is a bit hard to change to the right folder....

**Comment by Haehnchen** [comment]
related https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/1118

**Comment by cybernet** [comment]
#1118 is still not fixed, it's been months since symfony 4 was released and now it is stable ( 4.1.1 ), yet this is still a bug :)

**Comment by tom10271** [comment]
![Screenshot 2019-08-26 at 11 56 33 AM](https://user-images.githubusercontent.com/5089629/63664309-9957dd80-c7f8-11e9-93a1-bbfc3e36c8a1.png)

This is still not working

**Comment by Haehnchen** [comment]
duplicate, see related issues: https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/1736

ui will be changed; but there is already a lot of guessing the value independent from settings
