### ISSUE TITLE
Support for PhpStorm 2018.1

### ISSUE THREAD

**Issue by ostrolucky** [Haehnchen/idea-php-symfony2-plugin#1150]
It seems this plugin have no support for latest PhpStorm release. There is no integration upon installing it.

![image](https://user-images.githubusercontent.com/496233/36371079-59fa947a-1561-11e8-8979-168b28083303.png)

```
PhpStorm 2018.1 EAP
Build #PS-181.3741.23, built on February 14, 2018
PhpStorm EAP User
Expiration date: March 16, 2018
JRE: 1.8.0_152-release-1136-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-109-generic
```

**Comment by ByScripts** [comment]
Just for information, `Symfony plugin` requires `Php Annotations` plugin which is not compatible with `2018.1`, so PhpStorm disable it.

**Comment by ostrolucky** [comment]
Ohh, that is very good to know. Thanks for information!

**Comment by vkhramtsov** [comment]
**Php annotations** already compatible with new php storm https://plugins.jetbrains.com/plugin/7320-php-annotations

**Comment by Haehnchen** [comment]
annotations plugin updated
