### ISSUE TITLE
Form type properties wrongly searched as entity properties

### ISSUE THREAD

**Issue by zanardigit** [Haehnchen/idea-php-symfony2-plugin#1152]
- Plugin v.0.16.164
- PhpStorm v.2017.3.4

See attached image. When you add a field of `EntityType` type in a form builder, properties of the type are underlined as wrong because (e.g.):

    Field 'required' not exists in referenced class \AppBundle\Entity\Customer

![entitytype](https://user-images.githubusercontent.com/2579986/36794875-d46e309e-1ca1-11e8-801a-e95b0d7617fb.png)

But they are in fact properties of `EntityType` class and not of `Customer` class. 

Hope my report makes sense. Thank you for your plugin and for your help, feel free to contact me for tests and/or more informations.

**Comment by ddlzz** [comment]
yes, I often experience the same issue because of the heavy usage of the forms component!

**Comment by cedricziel** [comment]
I think you have the Yii2 plugin installed. This error is not added from the symfony plugin.

**Comment by ddlzz** [comment]
@cedricziel you're right! I turned it off and the error disappeared! thanks

**Comment by zanardigit** [comment]
@cedricziel confirmed. Thank you! Not a Symfony plugin issue at all.
I installed Yii plugin for another project but then I never used it, so I would have never made the connection.
