### ISSUE TITLE
2018.1 compatibility / Gradle build

### ISSUE THREAD

**Issue by cedricziel** [Haehnchen/idea-php-symfony2-plugin#1158]
Hi there,

I wanted to ask about 2018.1 platform compatibility, and then I thought I can do that myself an just PR, but since your plugin uses the IDE based build, I wanted to ask beforehand if you'd be open to have the build infra adapted to gradle?

**Comment by Haehnchen** [comment]
i am really thankful for this. as i see you started with https://github.com/Haehnchen/idea-php-toolbox/pull/79 which is indeed a good plugin without that match dependencies. If we polish it we can spread it around all other plugins also at this one here.

**Comment by cedricziel** [comment]
Hi Daniel - thx for your kind words. In the toolbox there's only a single component that needs fixing. I'll try to build upon it and propose changes to the other projects ;)

**Comment by metalmini** [comment]
The official release of 2018.1 was today and sadly the most used plugin does not work anymore. Whats up guys? There is a PR for this issue but isn't merged yet.

**Comment by cedricziel** [comment]
@metalmini all good. I'm pretty sure Daniel will go through the PRs soon.

**Comment by cedricziel** [comment]
Here's a prebuilt jar for you: [Symfony Plugin-0.16.165.zip](https://github.com/Haehnchen/idea-php-symfony2-plugin/files/1861605/Symfony.Plugin-0.16.165.zip)

If you don't trust a stranger on the internet, I actively encourage you to build it yourself, it's not as hard as it sounds (one of the PRs goals is to make it simpler for anyone to contribute to the plugins). You need a JDK installed (`javac` must be available on your `PATH`).

Then run:

```bash
PHPSTORM_ENV="skip incomplete" ./gradlew clean check buildPlugin
```

The build artifact is available in the `build/distributions` folder then.

I hope that helps :) Let me know if anything is off.

**Comment by oleja** [comment]
Thanks @cedricziel!
Since Symfony plugin depends on PHP Annotations plugin, I also had to update PHP Annotations plugin. PHPStorm didn't show any update messages, so I had to manually reinstall the plugin using latest official jar from https://plugins.jetbrains.com/plugin/7320-php-annotations.

**Comment by metalmini** [comment]
Thanks for the prebuild.

Thanks for the tip about the building process, will do that eventually. Right now i just have to get everything up and running for work ;-)

I also did the annotations reinstall.

**Comment by lashae** [comment]
I personally downgraded to 2017.3 when I noticed that Symfony plugin is not compatible yet; it was a painful experience but I managed :-) Honestly, I like using the latest version always, however 2018.1 has nothing to offer to make me upgrade now by forgiving Symfony plugin.

Long word short, I'm waiting the compatible Symfony plugin to upgrade to PhpStorm 2018.1

**Comment by nalekberov** [comment]
Luckily after re-installing both PHP annotations and Symfony plugin everything works well.

**Comment by stevechilds** [comment]
To make things worse, I installed the JetBrains Toolbox, so it automatically upgraded Storm for me.

C'mon guys, for one of the most popular plugins for PHPStorm, why wasn't this compatible with 2018.1, surely Jetbrains let plugin developers have preview access to a new release before it comes out?

**Comment by tzfrs** [comment]
@nalekberov How did you re-install? When I uninstall, restart PhpStorm and browse the repository for the plugins I don't see any install button for the two plugins PHP Annotations and Symfony Plugin.

**Comment by webdevilopers** [comment]
There is a "Browse repositories" Button @tzfrs .

**Comment by rawburner** [comment]
Reinstalling worked for me. Deactivate plugins, restart PHPStorm then search them in the plugin-repo. After restarting again they works.

**Comment by lashae** [comment]
@rawburner Did you manage to downgrade to PHPStorm 2017.3 and activate Symfony plugin or did you manage to run Symfony plugin "from Jetbrains repository" on PHPStorm 2018.1?

**Comment by rawburner** [comment]
@lashae I have PHPStorm 2018.1 and symfony plugin running. After removing both plugins (PHP Annotations ans Symfony Plugin) I could find them in the plugin repository and install again.

**Comment by migo315** [comment]
Great @lashae - that solved my problem.

**Comment by cedricziel** [comment]
This one can be closed indeed.

**Comment by Haehnchen** [comment]
yes indeed
