### ISSUE TITLE
Generated getters irgnore doctrine nullable annotation

### ISSUE THREAD

**Issue by y2keeper** [Haehnchen/idea-php-symfony2-plugin#1165]
Technically this is a problem with the core PHP Storm implementation for generating getters but I doubt they would address this and hope it's something this plugin could address.

PHP Storm auto generated return type declarations for getters don't take Doctrine\ORM\Mapping annotations into account.

Specifically, suppose you have a property:

``` php
/**
 * @var string
 * @ORM\Column(type="string", nullable=true)
 */
protected $fullName;
```

The getter generated for this will be:

``` php
/**
 * @return string
 */
public function getFullName(): string
{
    return $this->fullName;
}
```
    
Resulting in errors such as:

```
Type error: Return value of App\Entity\User::getFullName() must be of the type string, null returned
```

```
PHP Storm Version: 2017.3.4
Plugin Version: 0.16.165
```

Thanks for providing / maintaining this plugin - it makes our lives a LOT easier :-)

**Comment by rvitaliy** [comment]
@y2keeper the auto generated getter got information from `@var` of property.

in your case it's wrong configured, try to change it in `@var string|null`

```
/**
 * @var string|null
 * @ORM\Column(type="string", nullable=true)
 */
protected $fullName;
```
