### ISSUE TITLE
Autocomplete class names in constant() function in Twig

### ISSUE THREAD

**Issue by nickygerritsen** [Haehnchen/idea-php-symfony2-plugin#1167]
When using the `constant()` function in Twig files, I get autocompletion for global constants.
As soon as I typed a class, say `Foo\\Bar` inside the `constant` function, I get autocompletion for constants inside that class.

However, it would be great if either:
* We get autocompletion for all classes (that have constants) immediately inside the `constant` function
* We get autocompletion for all class constants immediately

Such that I do not have to manually type the class name before having code completion.

**Comment by Haehnchen** [comment]
done by related issue
