### ISSUE TITLE
Autocompletion for Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-symfony2-plugin#1189]
The new `Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted` does not have any autocompletion for attribute values yet. But we could have some.

```php
class MyController
{
    /**
     * @IsGranted("DISABLE", subject="organization")
     * @IsGranted("ROLE_SUPER_ADMIN")
     */
    public function disableAction(Request $request, Organization $organization)
    {
    }
}
```

We could have completion in 2 places here:

- the permission being checked (as done for the first argument of `isGranted()`)
- the subject. This attribute takes the name of a controller argument.

**Comment by vctls** [comment]
Maybe create a new method reference provider for roles? That way we could use it wherever we want.

**Comment by stof** [comment]
I don't want completion for roles only. I want completion for permission attributes (roles are only one thing used as permission attribute. In my example, `DISABLE` is a non-role permission attribute because it is handled by a different voter).
And there is already that provider somewhere, as we have it for `isGranted`. This issue is about supporting the `@IsGranted` annotation.

**Comment by Haehnchen** [comment]
done

**Comment by stof** [comment]
The linked PR does not seem to add completion for the `subject` attribute (which should autocomplete the names of method parameters).
