### ISSUE TITLE
Case sensitive in yaml files about a class namespace

### ISSUE THREAD

**Issue by xserrat** [Haehnchen/idea-php-symfony2-plugin#1200]
Hi,

First of all, thanks for this great plugin.

I've just found an issue about how the plugin understands if a class exists or not with the exact namespace. If I define in my yaml file a service with a specific class namespace like this:

```yaml

myservice:
   class: A\Namespace\ClassName
```

If the correct namespace is `A\NameSpace\ClassName`, the plugin does not highlight that the class I'm trying to use does not exist owing to the wrong namespace. (The correct is`Namespace` instead of `NameSpace`).

Thank you so much and let me know if you need more info about that.

**Comment by cedricziel** [comment]
Great idea - I will try to create such inspection.

**Comment by cedricziel** [comment]
That should do it - i have created a QuickFix that can correct the FQN automatically as well :)

**Comment by xserrat** [comment]
That's nice! Thank you @cedricziel !
