### ISSUE TITLE
Plugin error 'No Symfony service with given id found'

### ISSUE THREAD

**Issue by SMielcarek** [Haehnchen/idea-php-symfony2-plugin#1207]
I am using Symfony IoC container in one of my projects (just ContainerBuilder, not full Symfony framework). I add services programmatically, like so:

```
$this->container = new ContainerBuilder();
$this->container->register('routeCollection', RouteCollection::class);
$this->container->register('context', RequestContext::class);
$this->container->register('matcher', UrlMatcher::class)->setArguments(array(
    new Reference('routeCollection'),
    new Reference('context')
));
```

Then I try to get the service

`$matcher = $this->container->get('matcher');`

But I am getting the warning: 'No Symfony service with given id found'. The plugin is activated and I can see a couple of default services when I press ctrl+space. I also see that my services are there when I list them with:

`$this->container->getServiceIds();`

Also my program works correctly. Does this mean the plugin works only with xml or yml config files?

**Comment by King2500** [comment]
I recommend dumping your container to a XML file (maybe for your Dev environment only). Then you get autocomplete and type support for get method on your IDE.

**Comment by King2500** [comment]
Look here:
http://symfony.com/doc/current/components/dependency_injection/compilation.html#dumping-the-configuration-for-performance

Instead of PhpDumper use XmlDumper

**Comment by SMielcarek** [comment]
Hi, I used XmlDumper. It creates xml file with list of services in the container. If this file is present, PhpStorm recognizes all the services correctly. So indeed, it seems for the plugin to work, this xml file is required. Thanks for the advice.

**Comment by cedricziel** [comment]
What about closing the issue then? :)
