### ISSUE TITLE
Support multiple twig path that are set dynamically in the app

### ISSUE THREAD

**Issue by tristanbes** [Haehnchen/idea-php-symfony2-plugin#1216]
Hello,

I'm adding to twig new path on runtime based on some logic. PhpStorm+Symfony plugin can't find my templates.

<img width="578" alt="yprox____workspace_yprox__-_____sites_src_articlebundle_controller_articlecontroller_php__yprox_" src="https://user-images.githubusercontent.com/346010/44199513-a4d3eb80-a144-11e8-966f-e9c9fc5b5458.png">

<img width="355" alt="yprox____workspace_yprox__-_____sites_src_articlebundle_controller_articlecontroller_php__yprox_" src="https://user-images.githubusercontent.com/346010/44199655-f67c7600-a144-11e8-8928-0884a0819a09.png">

```twig
twig:
    paths: ~ # default config
```

```php
class TwigPathAdder
{
    public function foo() {
        if (Site::THEME_ENGINE_CODENAME === $theme) {
            $this->loader->prependPath("{$this->projectDir}/templates/plymouth");
        } 
        if (Site::THEME_ENGINE_LEGACY === $theme) {
            $this->loader->prependPath("{$this->projectDir}/templates/weymouth");
        }
    }
}
```

Is there a way to add root path for templates please ?
Excepted behaviour is CTRL+CLICK on template name should show 
```
- weymouth/article/print.html.twig
- plymouth/article/print.html.twig
```

Thank you.

**Comment by tristanbes** [comment]
Ok, i've found it: 

<img width="1031" alt="twig_namespace_et_preferences_et_yprox____workspace_yprox__-_____sites_src_articlebundle_controller_articlecontroller_php__yprox_" src="https://user-images.githubusercontent.com/346010/44200027-e7e28e80-a145-11e8-80e7-44b88dcce82e.png">

**Comment by kianbomba** [comment]
Can I ask what editor color scheme are you using ? :P
