### ISSUE TITLE
New YAML constans syntax

### ISSUE THREAD

**Issue by asuran** [Haehnchen/idea-php-symfony2-plugin#1218]
Hi!

Starting from Symfony 3.4 new syntax for constants in YAML was introduced.

```php
!php/const PHP_INT_MAX
```

https://symfony.com/blog/new-in-symfony-3-2-php-constants-in-yaml-files

Plugin version: 0.16.165
PHPStorm version: 2018.2.1

**Comment by cedricziel** [comment]
Should be fixed in current master (see #1202).

**Comment by Crovitche-1623** [comment]
I don't know if something has changed in the meantime or if my issue is related but the `!php/const` syntax is not working :
- 1. Usages are not found by the IDE
- 2. Refactoring does not refactor the `!php/const` located in yaml file.

Please re-open.
