### ISSUE TITLE
No autocomplete on ControllerTrait::redirectToRoute method

### ISSUE THREAD

**Issue by rrajkomar** [Haehnchen/idea-php-symfony2-plugin#1223]
When creating a redirect response with 
`new RedirectResponse($this->get('router')->generate(ROUTE_NAME));`
the autocomplete on the route name works

However when using `$this->redirectToRoute(ROUTE_NAME);`, the autocomplete won't trigger.

When the entire route name is written a Ctrl + Click on the name will still map to the correct controller action though...

**Comment by Haehnchen** [comment]
outdate api, but should still work :)
