### ISSUE TITLE
Support autocompletion for new controller format in routing

### ISSUE THREAD

**Issue by apfelbox** [Haehnchen/idea-php-symfony2-plugin#1231]
Hi,

I would be great if the plugin could support the new controller format (`FQCN::method`) in the routing definitions for autocompletion.

The format itself is supported (= Cmd+Click works and jumps to the correct method), but autocompletion doesn't work yet:

Autocompletion only supports the old format: ❌
![2018-09-20 at 11 44](https://user-images.githubusercontent.com/1032411/45810310-a146fd80-bcca-11e8-83bf-6144c0947f08.png)

Related to #1159

**Comment by Haehnchen** [comment]
done
