### ISSUE TITLE
Consider providing a ErrorReportSubmitter

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-symfony2-plugin#1233]
While getting an exception coming from the plugin (the same than #1184), I noticed that PhpStorm told me that the plugin does not implement its error reporting component, and so PhpStorm could not report it directly.

It looks like PhpStorm allows plugins to register a ErrorReportSubmitter. Would it make sense for this plugin to have one ?

**Comment by Haehnchen** [comment]
added
