### ISSUE TITLE
GoTo is broken for routes named the same than a PHP function

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-symfony2-plugin#1237]
Reproducing case:

- create a route named `join`
- write `$this->generateUrl('join')` in a controller
- click on the route name in this code to trigger the GoTo logic

Expected behavior: go to the route definition and/or the corresponding controller

Actual behavior: goes to the definition of the `join` function in the stubs

**Comment by cedricziel** [comment]
Hi @stof ,

is the `join` route in the autocompletion for the UrlGenerator?

**Comment by stof** [comment]
yes, the autocompletion works fine.

**Comment by Haehnchen** [comment]
already fixed
