### ISSUE TITLE
Autocomplete for app variable in Twig not working

### ISSUE THREAD

**Issue by yoannk** [Haehnchen/idea-php-symfony2-plugin#1238]
When i type "ap" in Twig template i have autocompletion : 
![a](https://user-images.githubusercontent.com/18040372/46486671-2d424480-c7f6-11e8-8257-b86d9eb58441.PNG)
but when i type "app." i see nothing (no app.request, app.session etc).

I am using PhpStorm 2018.2 and symfony 4.1

**Comment by Nkoyan** [comment]
Autocompletion works now, it would be nice to have `app.flashes` too.

**Comment by King2500** [comment]
Original reported and detailed here: #903

**Comment by chiqui3d** [comment]
Hello,
For my `app `autocompletion does not work.

**Comment by ovgray** [comment]
Autocomplete of "app." still does not offer "flashes", and when "app.flashes" is included in a twig template "flashes" is highlighted, and hovering over the work triggers "Field or method not found"

**Comment by Haehnchen** [comment]
already fixed
