### ISSUE TITLE
Symfony 4.2: support translation file suffix "+intl-icu"

### ISSUE THREAD

**Issue by gharlan** [Haehnchen/idea-php-symfony2-plugin#1251]
https://github.com/symfony/symfony/pull/28952

At the moment all messages are marked as missing in phpstorm.

**Comment by digilist** [comment]
I did it this way, because in Symfony this is a valid domain and you can use it.

**Comment by digilist** [comment]
Ah never mind, you mean that it should be shown without the suffix as well. Will fix it :)

**Comment by digilist** [comment]
Hmm, no wait :smile: Did you test the PR that I provided or is this unrelated? Otherwise this is fixed with my PR.

**Comment by gharlan** [comment]
> Did you test the PR that I provided or is this unrelated?

It's unrelated, I use the current release.

> Otherwise this is fixed with my PR.

Cool! And thanks for your pr! ❤️

**Comment by Haehnchen** [comment]
its released, feedback is welcome ;)

**Comment by gharlan** [comment]
Made a quick test, and it seems to work very well! Thanks a lot! ❤️
