### ISSUE TITLE
Entity autocomplete in annotations not working in symfony 4.2.3

### ISSUE THREAD

**Issue by deivid11** [Haehnchen/idea-php-symfony2-plugin#1280]
Symfony 4.2.3 no longer generates appDevDebugProjectContainer.xml file, the new name of the file is  is srcApp_KernelDevDebugContainer.xml. Can this plugin check for it so autocomplete works correctly?

**Comment by gbtux** [comment]
Hi.
Go to File -> Settings -> L&F > PHP > Symfony > Container.

Configure like the capture.
Enjoy ;)
![capture d ecran de 2019-02-24 12-27-47](https://user-images.githubusercontent.com/2924704/53298526-aa1a9d00-382f-11e9-86f7-71fe4e8a32ee.png)

**Comment by deivid11** [comment]
Solved, thanks.

**Comment by Haehnchen** [comment]
closed, also created an issue for improvements on autodetection
