### ISSUE TITLE
Twig autocomplete not working in symfony 4.2.3

### ISSUE THREAD

**Issue by dsentker** [Haehnchen/idea-php-symfony2-plugin#1281]
A twig variable injected by related controller does not show member methods of the object.
Example:

Controller:
![Controller](https://i.imgur.com/Ddxn3HG.png)

Template, Strg+Space shows:
![Twig](https://i.imgur.com/Ap4Uhd9.png)

What to do?

**Comment by Haehnchen** [comment]
i think you need to provide ".html.twig". i guess its working on Symfony side. maybe then there is a way to support it also here.

**Comment by auipga** [comment]
If it does not link your parameters from the controllers render method, you can always manually typehint:
```
{# @var user \App\Entity\User #}
{{ user... }}
```

**Comment by alturic** [comment]
You know, I was wondering how exactly it knows the auto-completion for vars injected into the Twig environment.

Frankly, it would be terrible having to stuff templates with var declarations. I know it’s somewhat a “one and done” thing, but when something that’s supposed to work, doesn’t, I always feel like I’m not doing something right.

**Comment by dsentker** [comment]
@Haehnchen, the extension is provided, but omitted by PhpStorm.

**Comment by Haehnchen** [comment]
its working when

- types are provided
- template and contoller knows each other (see "red mark")
- (check also you yellow underline on the template)

![image](https://user-images.githubusercontent.com/1011712/166811297-1bff840d-acdb-4bc9-bf0f-102aa92d6c0c.png)

![image](https://user-images.githubusercontent.com/1011712/166811387-8a9c2b16-456e-4444-a9d3-3235cd8c16fa.png)
