### ISSUE TITLE
@Event with constants

### ISSUE THREAD

**Issue by janbuecker** [Haehnchen/idea-php-symfony2-plugin#1282]
Hey, I collect my events in a class for simple auto-completion. As their value, they reference an event's constant. If I use the event collection class, i don't get auto-completion for the event. If the event is a simple string, it can be resolved and the correct type-hint for the created method is set.

This does work:
```php
class MyEvents
{
    /**
     * @Event("Acme\OwnEvent")
     */
    public const MY_OWN_EVENT = 'own_event';
}
```

This does **not** work:
```php
class MyEvents
{
    /**
     * @Event("Acme\OwnEvent")
     */
    public const MY_OWN_EVENT = OwnEvent::EVENT_NAME;
}
```

Maybe am I doing something wrong?

**Comment by Haehnchen** [comment]
@Event has been removed from Symfony, becasue of class constants
