### ISSUE TITLE
[Symfony 4] "Missing template" > lowercase template folders

### ISSUE THREAD

**Issue by ruudk** [Haehnchen/idea-php-symfony2-plugin#1285]
I'm working on a case sensitive filesystem.

Before Symfony 4, `\AdminBundle\Controller\Financial\TransactionController::indexAction` would resolve to `src/AdminBundle/Resources/views/Financial/Transaction/index.html.twig`.

But starting from Symfony 4, the folder names need to be snake_cased. That means that the template is now located at `src/AdminBundle/Resources/views/financial/transaction/index.html.twig` 

```diff
-src/AdminBundle/Resources/views/financial/Transaction/Index.html.twig
+src/AdminBundle/Resources/views/financial/transaction/index.html.twig
```

The plugin doesn't understand this.

**Comment by ruudk** [comment]
@Haehnchen This is still broken, also for Symfony 5. Do you know how to fix this?

**Comment by VincentLanglet** [comment]
@Haehnchen The problem still exists. What code should be updated ?

**Comment by Haehnchen** [comment]
this was already fixed, but neverless there is now also support for php attributes and following improves to support non bundle project structures
