### ISSUE TITLE
Container parameter case sensitivity and environment variables

### ISSUE THREAD

**Issue by FlyingDR** [Haehnchen/idea-php-symfony2-plugin#1288]
Symfony plugin have "Container sensitivity" inspection that controls container parameter names compatibility with [Symfony guidelines](https://symfony.com/doc/current/contributing/code/standards.html#service-naming-conventions). 

However with introduction of [DotEnv](https://symfony.com/doc/current/components/dotenv.html) component in Symfony 3.3 these guidelines are updated to include exception for defining default values for environment variables as explained [here](https://symfony.com/doc/current/configuration/external_parameters.html#environment-variables). 

As of version v0.17.170 Symfony plugin have no support for such exception and hence definition of default value for environment variable currently results into false positive.

**Comment by pgl** [comment]
Here's an example of this:

![symfony-plugin-complaint-about-uppercase-parameters](https://user-images.githubusercontent.com/1181139/56288621-6fdac700-611f-11e9-8e4c-344e67173e69.png)

**Comment by pgl** [comment]
Here's an example.

![symfony-plugin-complaint-about-uppercase-parameters](https://user-images.githubusercontent.com/1181139/56288793-c6480580-611f-11e9-9cd3-add545ac69bc.png)

**Comment by equapro** [comment]
In addition, [Service Naming Conventions](https://symfony.com/doc/current/contributing/code/standards.html#service-naming-conventions) said 

> Use lowercase letters for parameter names **(except when referring to environment variables with the %env(VARIABLE_NAME)% syntax)**

**Comment by Haehnchen** [comment]
closed; inspection was removed
