### ISSUE TITLE
Symfony.phar fails to download

### ISSUE THREAD

**Issue by Michigras** [Haehnchen/idea-php-symfony2-plugin#1310]
When creating a new symfony project, PhpStorm wants to download the symfony.phar file from their website. Unfortunately, it gives a 403 error. I suppose after that the basic symfony folder structure should be created in my PhpStorm project. Of course, this does not happen.

Error message:
    **> Downloading Symfony.phar**
    > Failed to download 'http://symfony.com/installer':
    > Request failed with status code 403

http://symfony.com/installer redirects to https://symfony.com/installer to https://get.symfony.com/symfony.phar. I don't get a 403 error in my browser.

The plugin seems to try to fetch https://get.symfony.com/Symfony.phar (notice the capital 'S'). This gives, indeed, a 403 in my browser.

Any ideas?

**Comment by so1ver** [comment]
same fault in ideaIntellij with plugin version v0.17.172

**Comment by Haehnchen** [comment]
url changed via #1311

**Comment by Haehnchen** [comment]
i also changed it now to the direct redirect target

**Comment by stevedb** [comment]
Hello @Haehnchen, do you know when you're planning on releasing this? I'm still seeing this issue after updating the plugin to v0.18.174 in PHP Storm.

**Comment by Michigras** [comment]
It was pushed right after the last version, so it should be in v0.18.175!

**Comment by stevedb** [comment]
Unless I'm wrong if it was pushed after the last version tag then it wouldn't be in that version.
Just looking at the updated file at tag 0.18.174 and it's not there:
https://github.com/Haehnchen/idea-php-symfony2-plugin/blob/0.18.174/src/main/java/fr/adrienbrault/idea/symfony2plugin/installer/SymfonyInstallerUtil.java#L38
It's not a massive issue for me now just trying to be helpful and point out it hasn't been released yet.

**Comment by BrickZ28** [comment]
Issue still exist.  Ijsut install the sympfony plugin yesterday and tried to start a new project with no luck.

**Comment by Michigras** [comment]
As I said, the fix was pushed right _after_ .174's release, so it should be in the next version .175.

**Comment by stevedb** [comment]
My apologies, I misread your version number above.

**Comment by SAMUEL-KETECHIE** [comment]
Please when would the v0.18.175 be out on Jetbrains PhpStorm for us to use ?
 We are stacked on a very serious project.
We appreciate your hard work.

**Comment by Olafxso** [comment]
I would like to try this plugin, but it failed to download Symfony.phar . Do you have a workarround? Is it possible to download Symfony.phar myself and save it to an location so the plugin does not need to download it?

**Comment by Haehnchen** [comment]
its released

**Comment by Tortonas** [comment]
Issue still exists.

![image](https://user-images.githubusercontent.com/41127259/66424115-a847c780-ea15-11e9-9a76-592e9ca8f706.png)

**Comment by Vartistry** [comment]
Still exists

**Comment by harrieb** [comment]
Same here.

I was curious. So i figured out some kind of workaround. 

I used a proxy in a docker container to redirect to the URL needed. Might not be the smartest way to handle this, but hey... it worked.

Here are the steps to reproduce it.

1. Create docker container and publish port 8118. For example:
`docker run -ith privoxy --name privoxy -p 8118:8118 ubuntu /bin/bash`

2. Inside the container install and configure privoxy:
`apt-get update && apt-get upgrade -y && apt-get install -y privoxy`
`sed -i -E 's/(^\s*listen-address.*)/# \1/' /etc/privoxy/config`
`echo -e "listen-address 0.0.0.0:8118\n" >> /etc/privoxy/config`

3. Inside the container add a redirection to privoxy's user action file:
 `echo '{+redirect{https://get.symfony.com/symfony.phar}}' >> /etc/privoxy/user.action`
 `echo 'symfony.com/installer' >> /etc/privoxy/user.action`

4. Inside the container start privoxy:
 `service privoxy start`

5. In your IDE create a new project. Select 'Symfony' as project type, select a folder an do all the other stuff. Then click the "Create" button and look at the annoying hint.

![Bildschirmfoto 2019-12-18 um 01 39 48](https://user-images.githubusercontent.com/49253517/71046140-a433d680-2137-11ea-9ac3-7fcbc9fcdd3d.png)

6. This time select "Set up HTTP proxy settings", add the proxy you just created and you're done.

![Bildschirmfoto 2019-12-18 um 01 44 43](https://user-images.githubusercontent.com/49253517/71046259-13112f80-2138-11ea-95e6-2e1a8ad1a34b.png)

7. Don't forget to remove the proxy after you're finished with this. Remove from the IDE settings and drop the container.

Hope this helps somebody

**Comment by Plasticable** [comment]
Problem still persists

**Comment by dragonis41** [comment]
[https://get.symfony.com/symfony.phar](https://get.symfony.com/symfony.phar) is no longer supported, according to the documentation we need to use those commands now :
`wget https://get.symfony.com/cli/installer -O - | bash` on Linux or
`curl -sS https://get.symfony.com/cli/installer | bash` on Mac.
Why not integrate a version of Symfony and update it during the first launch and maybe allow us to choose between an Embedded Symfony and the System Symfony ?

**Comment by pablorodrigo** [comment]
The problem still persists :(

**Comment by 5thHarbinger** [comment]
I'm sure a lot already have found this solution but a good workaround is to create a new composer project instead of a symfony one.

You can choose any symfony package you want to start with, like `symfony/skeleton` or `symfony/website-skeleton`.

[Solution found here, by Eugene M.](https://youtrack.jetbrains.com/issue/WI-46989#focus=Comments-27-3516428.0-0)

**Comment by devnix** [comment]
This is why we can't have nice things

**Comment by soufian250** [comment]
**The issue is still there** 
![Screenshot from 2021-11-11 10-30-30](https://user-images.githubusercontent.com/36607713/141274007-d37f1db1-0410-4a39-b87a-e966661b902f.png)

**Comment by 5thHarbinger** [comment]
@soufian250  I believe doing it this way is officially deprecated since quite some time now. This issue should be closed imo.

Me and some other put possible workaround above in this thread, did you tried those?

**Comment by ri5t3ai** [comment]
any update here?

**Comment by soufian250** [comment]
> any update here?

No updates for now

**Comment by Vaflenii** [comment]
Still doesn't work. Now it's not even trying to download.
![Screenshot 2023-08-30 101627](https://github.com/Haehnchen/idea-php-symfony2-plugin/assets/142094495/eaeb218e-8a98-48e8-99c6-04cd81874a59)
