### ISSUE TITLE
Browse buttons do not work

### ISSUE THREAD

**Issue by erop** [Haehnchen/idea-php-symfony2-plugin#1313]
While auto-configuration for the project works well, trying to use browse buttons to choose dirs for translation, app and web does not work completely. I'm on macOS 10.13.6, IDEA 2019.1.2.

![image](https://user-images.githubusercontent.com/124678/58151741-3d1e7400-7c73-11e9-950a-ea2990cc7b41.png)

**Comment by ruudk** [comment]
Will be fixed in https://github.com/Haehnchen/idea-php-symfony2-plugin/pull/1392
