### ISSUE TITLE
Question : How enable transation autocomplete on custom methods

### ISSUE THREAD

**Issue by DarkPingoo** [Haehnchen/idea-php-symfony2-plugin#1322]
Hi
I wrote a method that send a message, with a message parameter, and i'd like to enable translation autocomplete when i write the parameter.

Can you add annotation or something that enable autocompletion on methods ?

For instance : 
```
/**
 * @translateAutocomplete $message
*/
function mymethod($message) {
 ...
}
```

**Comment by King2500** [comment]
This should work:

```php
/**
 * @param string $message #TranslationKey
 */
public function mymethod($message) {}

$obj->mymethod('<caret>');
```
There is also `#TranslationDomain`

See: https://symfony2-plugin.espend.de/extension/method_parameter.html#hash-tags

**Comment by DarkPingoo** [comment]
Thank you, it works !!
