### ISSUE TITLE
Enable this plugin for non-symfony projects / support for multiple projects

### ISSUE THREAD

**Issue by BenoitDuffez** [Haehnchen/idea-php-symfony2-plugin#1332]
I have a project with 2 Symfony applications, and 2 common libraries. All 4 are opened in the same window thanks to the recent "attach" feature of PHPStorm.

The applications use Symfony, but the libraries don't. One of the library though uses Twig and has a templates folder (that mimics Symfony's) and `xxx/yyy.html.twig` templates.

When referencing them from the code, they appear as non-existent templates and it's not possible to ctrl-click them to open them. I think that's because the plugin ignores them because this is not a Symfony project.

Would it be possible to support this without Symfony, but based on the Twig dependency?

**Comment by BenoitDuffez** [comment]
Note: it only works on the 1st Symfony app in fact. The 2nd Symfony app does not have this feature enabled either. I guess that the Twig templates scan only occurs on the first project opened, and it is not relative to the project the current file belongs to.

Maybe this is not related to the use or not of Symfony, but rather on the new PHPStorm feature that allows to open several projects in the same window.

**Comment by kick-the-bucket** [comment]
The feature of attaching multiple projects/modules to a window is not new - it was a checkbox option for opening in current window before it became a separate button.

**Comment by BenoitDuffez** [comment]
Works now
