### ISSUE TITLE
Mark indirectly used services as not unused

### ISSUE THREAD

**Issue by RikudouSage** [Haehnchen/idea-php-symfony2-plugin#1348]
The new PhpStorm 2019.2 by default detects unused classes/methods.

Is it possible for your plugin to detect controllers and mark them as used?

**Comment by RikudouSage** [comment]
I let PhpStorm locate all classes that are unused and this is what I found:

These are reported as unused even if you have compiled kernel inside project tree:

- classes that are only used in annotations
- doctrine migrations

These are reported as unused if you have compiled kernel outside project tree:

- commands
- controllers
- doctrine fixtures
- listeners / subscribers
- repositories (if you fetch them via entity manager and not directly as services)
- authenticators
- tagged services that you don't fetch directly
- voters

This pretty much boils down to anything that is a service which isn't used directly.

**Comment by Jean85** [comment]
This seems a duplicate of #1366

**Comment by ruudk** [comment]
@RikudouSage Please close in favor of #1366

**Comment by RikudouSage** [comment]
@Jean85 @ruudk Isn't the other one duplicate of this, since this was first?

**Comment by ruudk** [comment]
@RikudouSage You are right, but the other issue has more detailed information + reply from the maintainer. Just close this one and subscribe to the other one, it keeps the issue tracker a bit more organized 😊

**Comment by RikudouSage** [comment]
Closed in favor of #1366
