### ISSUE TITLE
Service id resolving is not working in at least 4.3+ using Symfony Flex structure

### ISSUE THREAD

**Issue by tom10271** [Haehnchen/idea-php-symfony2-plugin#1360]
There is no app directory anymore

Take Sylius as example:
https://github.com/Sylius/Sylius-Standard

**Comment by thedomeffm** [comment]
Probably this can help you: https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/1148#issuecomment-380512638

**Comment by tom10271** [comment]
That is not working for me. It is hard to program without the aids of this plugin

**Comment by Haehnchen** [comment]
dont have a running sulu project. but https://github.com/Sylius/Sylius-Standard/blob/master/src/Kernel.php looks to be a supported structure; all should work out of box. if not you need to provide a debug / container manually via "Container" setting in the plugin configuration
