### ISSUE TITLE
Symfony in sub folder

### ISSUE THREAD

**Issue by thedomeffm** [Haehnchen/idea-php-symfony2-plugin#1363]
How to configure the plugin when symfony is in a subdirectory?

- Project (root)
-- backend (symfony)
-- frontend (vue)
-- docker

(e.g. `backend/src/Controller/DebugController.php` )
![Symfony_Plugin_SubDir](https://user-images.githubusercontent.com/29406401/63585400-50591c80-c59f-11e9-9e80-b9cc05568619.png)

As you can see in the img, PHPStorm/Symfony Plugin can't resolve (the vendor) stuff.
Inside of the `backend` directory it is a normal symfony application.

Thx for your help.

**Comment by stephanvierkant** [comment]
This is not related to the Symfony plugin. PhpStorm should resolve the classes even without this plugin.
