### ISSUE TITLE
Directory browsing not works

### ISSUE THREAD

**Issue by vaso123** [Haehnchen/idea-php-symfony2-plugin#1382]
When I want to change the directories in plugin, directory browser does not appears.

Of course I can write manually the values, but it should be fixed.

Nothing happens when click on the icon.

Ubuntu 18.04LTS, PHPStorm: 2019.2.3 September 25. built.

**Comment by ruudk** [comment]
Will be fixed in https://github.com/Haehnchen/idea-php-symfony2-plugin/pull/1392
