### ISSUE TITLE
Twig "Cannot find declaration to go to" for embed/include()

### ISSUE THREAD

**Issue by mhitza** [Haehnchen/idea-php-symfony2-plugin#1424]
When I use in my views the Twig `include` function or `embed` tag, the go-to definition functionality doesn't work for the files referenced.

**Comment by Haehnchen** [comment]
no enough context given to help.

**Comment by mhitza** [comment]
Both cases work nowdays. Probably wasn't the case at the time of reporting this issue in 2020.
