### ISSUE TITLE
Auto-Complete: missing first character

### ISSUE THREAD

**Issue by DZander** [Haehnchen/idea-php-symfony2-plugin#1429]
![image](https://user-images.githubusercontent.com/3225790/74227680-477c1480-4cbf-11ea-8ea9-9a0c69636db0.png)
![image](https://user-images.githubusercontent.com/3225790/74227717-56fb5d80-4cbf-11ea-9a30-fa8847dc5b10.png)

PhpStorm 2019.3.2
Symfony Support v0.19.189

**Comment by Haehnchen** [comment]
fixed
