### ISSUE TITLE
FOSRestBundle: Missing Route

### ISSUE THREAD

**Issue by AlexeyKosov** [Haehnchen/idea-php-symfony2-plugin#1433]
The plugin does not seem to support routes defined through REST annotations:

```
use FOS\RestBundle\Controller\Annotations as Rest;

/**
 * @Rest\Get("/test", name="test")
 */
public function testAction() {
```

It highlights the route as "Missing Route".

PhpStorm 2019.3.2, Symfony 5.0.4

**Comment by Haehnchen** [comment]
sry, as its an external bundle (also for its widely usage) is will never be implemented directly. use / provide a compiled routed out of the cache folder
