### ISSUE TITLE
Navigate to macros not working

### ISSUE THREAD

**Issue by theredled** [Haehnchen/idea-php-symfony2-plugin#1464]
Not sure if is a bug or a enchancement to be made.

CMD-clicking on macros calls doesn't navigate to the corresponding macro declaration.
Quite strange as macros has autocompletion, so maybe it's a bug?

PHPStorm 2020.1.1 
Symfony Support 0.19.193

**Comment by Haehnchen** [comment]
yes, noticed it also a long time ago; resulted because of api / lexer changes on twig plugin

**Comment by kevinpapst** [comment]
+1 from my side, this is really disturbing the workflow in twig templates
