### ISSUE TITLE
Phpstorm freeze with querybuilder autocompletion

### ISSUE THREAD

**Issue by SosthenG** [Haehnchen/idea-php-symfony2-plugin#1477]
PhpStorm freezes everytime I try to write an "orderBy" with a query builder.
I had the issue once with the completion of "where" clauses (now appears resolved), but this time it's with the orderBy order (in every repository, no matter the entity I try to query).

```
$qb = $this->createQueryBuilder('e');

$qb->orderBy('e.start_date', 'AS'); // Freeze here when I write "ASC", just before the C, it shows me the autocompletion popup and then freezes.
```

Event after waiting couple of minutes, it's still freezing, I can't quit the the IDE, I have to SIGKILL it.

I'm using PhpStorm 2020.1.1 with plugin version 0.20.194 on Ubuntu 19.10.

I don't have this issue on all my SF projects, so I'm guessing there is something with my project that triggers this issue, but I can't find out what. If needed I can provide my crash logs to anyone willing to investigate this.

Thanks!

**Comment by tomschwiha** [comment]
Maybe related to #1476 ?

**Comment by SosthenG** [comment]
> Maybe related to #1476 ?

Thanks for the reply. No I don't have the same error and I had the issue before version 0.20.194 and still having it after updating to the latest (.195) as suggested by [joel-ns](https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/1476#issuecomment-633854377)

[Here](https://pastebin.com/1HEQYfuL) is a part of my crash logs, I don't know if the rest is relevant (it continues like that in all the crash log files, for as long at the IDE was freezed before I killed it).

**Comment by tomschwiha** [comment]
Is the error also happening if the Symfony Plugin is disabled? There were back in time some PHPStorm issues so it may be a native issue.

**Comment by SosthenG** [comment]
No it's not, I first reported the issue to [jetbrains](https://youtrack.jetbrains.com/issue/WI-53231).
I just had the issue again with Symfony client autocompletion for a functional test:
```
 $client = $this->createClientWithParams([], 'username', 'password');
$client->request('GE') // Freeze here when trying to type "GET", the autocompletion showed up then the IDE freezed.
```

I don't really know if it's linked to this plugin, the logs I have doesn't make any sense to me. I never had the problem with all plugins disabled, but it makes sense because it only freezes when SF autocompletion appears (query builder, SF client).
I just updated some of my plugins (including PHP Annotations) and tried multiple combinations of enabled plugins : I can't reproduce anymore, even with all plugins enabled. Might be temporary but for now it seems solved, may be it was a PHP Annoations/SF Support issue.

Thanks for your help!

**Comment by SosthenG** [comment]
Sorry, I had the issue again, it's not solved...

**Comment by SosthenG** [comment]
Hi,
Can anyone help with this?
This is becoming unusable, I'm thinking about removing this plugin, which is a shame because it adds a lot of good functionalities but I really can't use PhpStorm anymore, it freezes 10 times a day, I have to kill and restart it each times...
Thanks.
