### ISSUE TITLE
Additional autocompletions for PHP templates

### ISSUE THREAD

**Issue by Venzon** [Haehnchen/idea-php-symfony2-plugin#148]
Will it be possible to implement such autocompletions in PHP templates:

<pre>
// php template helper name autocompletion
$view['helper_name']->method();

// route name autocompletion for router helper
$view['router']->generate('route_name');

// service name autocompletion
$this->container->get('service_name')->method();
</pre>

Thanks in advance ^^

**Comment by Haehnchen** [comment]
not supported by Symfony core anymore or in future so also closing issue in this project
