### ISSUE TITLE
Argument name binding service aliases trigger service name inspection

### ISSUE THREAD

**Issue by DavidBennettUK** [Haehnchen/idea-php-symfony2-plugin#1480]
Since Symfony 4.2.0 (I believe), it's possible to create a service alias that only binds to a specific argument name.

The following example will inject the `App\Serializer\MySerializer` service into parameters that are type-hinted with `Symfony\Component\Serializer\SerializerInterface` - but only if the parameter is named `$mySerializer`:

````
services:
    Symfony\Component\Serializer\SerializerInterface $mySerializer: '@App\Serializer\MySerializer'
````

This functionality was introduced here: https://github.com/symfony/symfony/commit/c0b8f53bcb44eb24f9f7779bf9f283ea1238d225

However the service name triggers the below inspection in the plugin:
"lowercase letters for service and parameter"

(Tested in PHPStorm 2020.1 with plugin version 0.20.195)

**Comment by Haehnchen** [comment]
> lowercase letters for service and parameter

this inspection was removed
