### ISSUE TITLE
QueryBuilder autocomplete does not work anymore

### ISSUE THREAD

**Issue by keksa** [Haehnchen/idea-php-symfony2-plugin#1483]
I have no idea when this happened, as I do remember this working correctly. With the following usage, the QueryBuilder autocomplete does not work, not just for the DQL within, but even for just the methods.

```php
$this->entityManager->getRepository(Foo::class)
    ->createQueryBuilder('f') // <- this still shows that it returns QueryBuilder
    // but in here nothing works anymore, no methods are suggested
    // and no parameters within the methods are suggested
    ->andWhere('f.bar = true')
    ->getQuery()
    ->getResult();
```

Putting just the query builder to a variable does not help as well. However dropping the `getRepository(Foo::class)` and using `$this->entityManager->createQueryBuilder()->from(Foo::class, 'f')` instead, does work as expected and everything is being autocompleted.

### versions
- macOS Catalina
- PhpStorm 2020.1.2
- Symfony Support 0.20.195
- PHP Annotations 7.0.2

### what I checked
- there are no errors generated
- tried the "clear index" in Symfony plugin settings
- tried the "invalidate caches & restart" several times
- first time I noticed this, I was on PhpStorm 2020.1.1, since then I updated to 2020.1.2 with no change
- tried disabled all other plugins except for PHP Annotations with no change

Please let me know if I can provide you with anything else to debug this issue, I'd really like this working again. :)

**Comment by jhard** [comment]
I'm seeing the same on PhpStorm 2020.2.2 (PHP annotations 7.1.3, PHP Toolbox 5.11, Symfony Support 0.21.202), however while trying to gather more input for this issue, I've found a workaround of sorts: it does work when the entity manager is passed as a type hinted argument or put into a temporary variable with a type hint in an annotation.

In the following example in `notWorking()` there will be autocompletion for methods (e.g. ->andWhere() will be suggested) but not method arguments, not even "s." will be suggested. 

In `working()` it works just fine, methods will be suggested and so will parameters, both "s." will as "s.fieldName" will show up. in `alsoWorking()`, they will show up as well, but you'd need to pass in the entitymanager. 

Hovering over the methods shows now differences, PhpStorm knows that it's a QueryBuilder.

```
<?php
class A {
   /**
    * @var \Doctrine\ORM\EntityManagerInterface
    */
   private $entityManager;
   
   public function __construct(\Doctrine\ORM\EntityManagerInterface $entityManager)
   {
      $this->entityManager      = $entityManager;
   }
   
   public function notWorking()
   {
      $this->entityManager->getRepository(\App\Entity\Something::class)->createQueryBuilder("s");
   }

   public function working()
   {
      /** @var \Doctrine\ORM\EntityManagerInterface $entityManager */
      $entityManager = $this->entityManager;
      $entityManager->getRepository(\App\Entity\AffiliateProduct::class)->createQueryBuilder("s");
   }
   
   public function alsoWorking(\Doctrine\ORM\EntityManagerInterface $entityManager)
   {
      $entityManager->getRepository(\App\Entity\Something::class)->createQueryBuilder("s");
   }
}
```
Switching to PHP 7.4 and using `private EntityManagerInterface $entityManager;` does not change the behavior.

I've verified this in two different Symfony projects, on 4.4 and 5.0. Please let me know if there's anything I can try or debugging information I can provide.
The workaround with an annotated variable will work for me with more complex queries, but it would be great if this was solved, as I'd like to avoid adding boilerplate everywhere.

**Comment by jhard** [comment]
I found a workaround that is much less annoying than having helper variables + typehinting all over the place.
With `.phpstorm.meta.php`, we can override the return values of methods. So something like the following will let PhpStorm know that passing '\App\Entity\MyEntity' into ->getRepository() will return a MyEntityRepository object.
It works for me, so I now longer have the issue of PhpStorm only knowing that it's an EntityRepository but not which kind (which then cascades to it not being sure what entities are returned by e.g. ->find() and flagging method calls as undefined). The very good news is: with that override in place, autocompletion on QueryBuilder works as expected.

That's a good enough solution for me, just have to automate creating the file and map all repositories, so I don't have to learn Java to fix this.

```
<?php

namespace PHPSTORM_META {
   
   use Doctrine\ORM\EntityManagerInterface;
   
   override(
      EntityManagerInterface::getRepository(0),
      map(
         [
            '\App\Entity\MyEntity' => 'App\Repository\MyEntityRepository',
            ''                     => 'Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository',
         ]
      )
   );
}
```

**Comment by keksa** [comment]
started working again after updating to PhpStorm 2021.1.1 and updating the plugin to the latest version
