### ISSUE TITLE
Support for manifest.json of Webpack Encore

### ISSUE THREAD

**Issue by yura3d** [Haehnchen/idea-php-symfony2-plugin#1536]
Hi! I'm using [Webpack Encore](https://github.com/symfony/webpack-encore) to bring Webpack to my Symfony app. Encore generates special file called `manifest.json` ([info](https://symfonycasts.com/screencast/webpack-encore/copy-files#public-path-to-versioned-copied-files-manifest-json)) which contains simple linear JSON object that maps logical assets' paths to their real equivalents. These 2 type of paths may differ by using hashes in filenames or even using different target folders:

![image](https://user-images.githubusercontent.com/10958696/91046351-f1e6d400-e620-11ea-82d3-0bdd37558b4f.png)

But **Missing asset** inspection expects only real paths in `{{ asset() }}` Twig function calls so I have huge amount of warnings in project about it:

![image](https://user-images.githubusercontent.com/10958696/91046921-ef38ae80-e621-11ea-89ea-9b8a199a28f7.png)

Additionally, I run Encore directly on remote machine so my local build folder for assets is always empty. This situation is identical to described (by using Docker) in similar issue here: https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/1020#issuecomment-336711444

So, it would be nice to have support of `manifest.json` to check file availability by checking object keys from this file.

**Comment by mathieu-coingt** [comment]
Yes, it would be very nice !

**Comment by sciro-de** [comment]
I just ran into the same thing. It would indeed be nice to have support for this.

**Comment by nexces** [comment]
+1 from me 😉

**Comment by crgbe** [comment]
Yeah! I've just ran into the same problem too. That would be very great if phpstorm could offer support for that. Thanks anyway for everything you're already doing (@phpstorm, @symfony, @weaverryan)

**Comment by miroslav-chandler** [comment]
+

**Comment by Haehnchen** [comment]
added
