### ISSUE TITLE
[feature-request] add support to PHP 8 attributes

### ISSUE THREAD

**Issue by azjezz** [Haehnchen/idea-php-symfony2-plugin#1567]
I have upgraded one of my projects to PHP 8 and noticed that routes declared using PHP 8 attributes are not recognized by this plugin.

I'm not sure if this issue has already been reported, but I searched and couldn't find one :)

example:
```php
<?php

declare(strict_types=1);

namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

final class IndexController
{
    #[Route("/", name: 'index', methods: ['GET'])]
    public function index(): Response
    {
        // some code
    }
}
```

**Comment by Haehnchen** [comment]
its now supported

**Comment by azjezz** [comment]
Thank you for your work @Haehnchen! ❤️
