### ISSUE TITLE
False positive "Twig: Missing Template"

### ISSUE THREAD

**Issue by VincentLanglet** [Haehnchen/idea-php-symfony2-plugin#1570]
With a controller `src/Controller/FooController.php` and a `defaultAction()` method,
I get `Twig: Missing Template` on my `@Template()` annotation.

But the file `templates/foo/default.html.twig` exists, and everything works fine.

Plus when I click on `Create Template`, I get "Can not find a target dir".

**Comment by sebtiz13** [comment]
I have same issue with `$this->render('index.html.twig')` also my file exist in `templates/index.html.twig`

I using:
Symfony 5
PHPStorm 2020.3.2

**Comment by Haehnchen** [comment]
its still working. by time "templates" was adapted as new file structure
