### ISSUE TITLE
Autocomplete not working!

### ISSUE THREAD

**Issue by igorpopryadukhin** [Haehnchen/idea-php-symfony2-plugin#1577]
Hi
Autocomplete not working!
I'll make a reservation right away, this does not work in the controller.

![image](https://user-images.githubusercontent.com/48174353/105767086-afc51400-5f6b-11eb-9978-b8f627ac6c6e.png)

I wanted so badly

**Comment by Haehnchen** [comment]
there is autocomplete for common querybuilder scopes, but there not enough information inside image to get a hint what is the main "entity".
