### ISSUE TITLE
Add support for ICU translations 

### ISSUE THREAD

**Issue by Khartir** [Haehnchen/idea-php-symfony2-plugin#1583]
Symfony supports messages with placeholders using the ICU-format (https://symfony.com/doc/current/translation/message_format.html)

In order to use these, the message files have to be renamed from `messages.<locale>.xlf` to `messages+intl-icu.<locale>.xlf`. This causes the plugin to mark messages in those files as missing.

https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/1251 suggests this should have been fixed, so maybe this is a regression?

Support for the validation of placeholders would also be nice, but that is of course a much more difficult change.

**Comment by Haehnchen** [comment]
should be inside via: https://github.com/Haehnchen/idea-php-symfony2-plugin/commit/42985c1b. i guess just outdated index process
