### ISSUE TITLE
Add better support for multiple locales in translations

### ISSUE THREAD

**Issue by Khartir** [Haehnchen/idea-php-symfony2-plugin#1584]
When trying to follow a translation key to the file that supports it, the dropdown to select the files containing that key show all files that match, but show the same `<>source` entry for all files:
![sources](https://user-images.githubusercontent.com/5592420/106583149-1090b580-6545-11eb-8754-8b96ce10665d.png)
It would be helpful if either the filename or the locale would be shown.

**Comment by zelding** [comment]
I came to ask for the same, unfortunately there was no visible progress made on this in years.
With Symfony 3 + xlf files, I have the same popup, even though all the files have the `source-language` and `target-language` attributes set on the `file` node

**Comment by Haehnchen** [comment]
![image](https://github.com/Haehnchen/idea-php-symfony2-plugin/assets/1011712/a569818f-bfbf-4141-a17a-ee00f4a40f24)

The main problem is that is basically already supported, but as "xlf" are non offical formats it depends now on plugins an other stuff ;)

I now why you see this kind of items, i will check if there is a suitable ways to rebuild the item rendering inside the plugin itself.

**Comment by Haehnchen** [comment]
included with much more :)

- icons
- symfony layer icon
- upvoting
- improved text ;)
- ...

![image](https://github.com/Haehnchen/idea-php-symfony2-plugin/assets/1011712/7a61fd73-febc-4884-8c21-5307e4cdfd66)
