### ISSUE TITLE
[QUESTION]: Possibility to hook into refactoring of PHPStorm

### ISSUE THREAD

**Issue by icanhazstring** [Haehnchen/idea-php-symfony2-plugin#1620]
Hi!

First of all, thanks for the plugin, amazing help.
But, sadly I am missing a crucial function that I used very often when working with Zend/Laminas where everything is based in *.php files.

The refactoring tool of PHPStorm.

Using the refactoring with *.yaml files does not work. The PHP part gets updated according to my changes, but the yaml stays with the old referenced names.

Is it possible to somehow hook into that refactoring system and provide refactoring for yaml files as well?

**Comment by Haehnchen** [comment]
i found no way so far, thats why all refactoring tools only work partially :)
