### ISSUE TITLE
Support of PHP 8 attributes in Doctrine ORM

### ISSUE THREAD

**Issue by yura3d** [Haehnchen/idea-php-symfony2-plugin#1653]
Just yesterday Doctrine 2.9 has been released: https://www.doctrine-project.org/2021/05/24/orm2.9.html

The major new feature is support of PHP 8 attributes for ORM data mapping in addition to already existing PHPDoc annotations.

But the plugin hasn't full support of PHP 8 attributes in Doctrine now.

Example 1. Value specified in `mappedBy` parameter of `OneToMany` association mapping is recognized as entity field and available for "Go to" if the mapping is writted in PHPDoc. But the value is not recognized as field if the mapping is written in attributes.

![image](https://user-images.githubusercontent.com/10958696/119537988-4cb98180-bd93-11eb-88fd-0fbe60f0872e.png)

Example 2. Custom repository type is not inferred from `EntityManager::getRepository()` if entity is mapped in attributes.

![image](https://user-images.githubusercontent.com/10958696/119539718-34e2fd00-bd95-11eb-99e6-1a7829e62a19.png)
![image](https://user-images.githubusercontent.com/10958696/119540096-af138180-bd95-11eb-9ce5-30c317e4dd9f.png)

**Comment by Haehnchen** [comment]
first general attribute metadata support added via: https://github.com/Haehnchen/idea-php-symfony2-plugin/pull/1701

**Comment by yura3d** [comment]
@Haehnchen Thank you for the release!

I've just tested my examples provided in the first post, and the 1st example doesn't work (`mappedBy` still doesn't navigate to correspondent field).

**Comment by asjur** [comment]
This is still an issue a year later. Is there anyone working on this?

**Comment by Gemorroj** [comment]
@Haehnchen i think it's major issue

**Comment by Haehnchen** [comment]
- Example 1 :heavy_check_mark:  already implemented
- Example 2 :heavy_check_mark: add in external plugin: https://github.com/Haehnchen/idea-php-annotation-plugin/pull/247
