### ISSUE TITLE
Symfony plugin prompting to activate on Laravel project

### ISSUE THREAD

**Issue by givihuda** [Haehnchen/idea-php-symfony2-plugin#1663]
I got a pop-up at the bottom right of PHPStorm when I opened my Laravel project...

6/21/21
9:17 AM	Symfony: Enable the Symfony Plugin with auto configuration now, open Project Settings or dismiss further messages

Shouldn't it be smart enough to read a composer.json file and realize that it's not Symfony?

```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.3|^8.0",
```

I mean, even without a composer.json... the plugin (or PHPStorm) should be smart enough to identify whether it's Symfony or not.

Any thoughts?

**Comment by givihuda** [comment]
I get this now on custom framework projects...

"Symfony: Enable the Symfony Plugin with auto configuration now, open Project Settings or dismiss further messages"

Really, the Symfony plugin should not be showing a prompt to activate it for the project without recognizing something showing it's a Symfony project; like a symfony version in composer.json, or a symfony folder in a recognizable place in the vendor folder.

**Comment by Haehnchen** [comment]
its a valid "Symfony project", lavaral is based on Symfony and provides possible features; thats why its finding smyfony components and given a hint

**Comment by givihuda** [comment]
That doesn't explain why I get the prompt on custom framework projects. Can you explain how the check is done? Does it search the code for Symfony anywhere, like in a vendor file?

**Comment by andrew-demb** [comment]
@givihuda Laravel extends some of the Symfony components and it means, that the Symfony plugin can be pretty useful for Laravel projects too.

Here is the logic, how plugin decides to show a notification https://github.com/Haehnchen/idea-php-symfony2-plugin/blob/6556c6fdd8540b9173275b97ac620ba434d34edb/src/main/java/fr/adrienbrault/idea/symfony2plugin/Symfony2ProjectComponent.java#L131-L134

**Comment by givihuda** [comment]
That doesn't explain why I get the prompt on custom framework projects (meaning, not a standard framework like Laravel).

Regardless, I discovered that the custom project has a package that includes symfony in vendor... so that explains that at least.
