### ISSUE TITLE
Dynamically added Routes not recognized

### ISSUE THREAD

**Issue by anvaya** [Haehnchen/idea-php-symfony2-plugin#1684]
Hi,

When using bundles like Sonata Admin that create routes dynamically, PHPStorm won't recognize a valid route and flag it as an invalid route.

![phpstorm_symfony_route_issue](https://user-images.githubusercontent.com/2928423/127771671-2f791ae5-94ca-4a26-a501-1f1dd85c8b6f.png)

**Comment by Haehnchen** [comment]
if you project follows support file structure, is possible now detected. if not you need to provide a compiled container file:

![image](https://user-images.githubusercontent.com/1011712/166761757-c8a332bf-2524-4326-88d1-3945164e758e.png)
