### ISSUE TITLE
Support of PHP 7.4 typed property for container

### ISSUE THREAD

**Issue by yura3d** [Haehnchen/idea-php-symfony2-plugin#1689]
PhpStorm 2021.2, Win10 x64
Symfony Support 0.23.210, PHP Toolbox 6.0.0
Symfony Components 5.3.4, Symfony Flex 1.13.4

Container `Psr\Container\ContainerInterface` as type-hinted parameter is recognized:

![image](https://user-images.githubusercontent.com/10958696/129040240-8d31c2cd-8ada-447b-b275-17aca8189ede.png)

But it is not recognized if container is stored to typed property:

![image](https://user-images.githubusercontent.com/10958696/129040764-13a8b6b1-e1a0-4b97-87ef-024caa6a4258.png)

**Comment by adamwojs** [comment]
Hi @yura3d. Could you please provide some more details to help reproduce this issue? 

- Which version of Symfony/PhpStorm and Symfony plugin are you using? 
- What is the FQCN (fully qualified class name) of ContainerInterface?

**Comment by yura3d** [comment]
Hi @adamwojs, thanks for reply. I've clarified the first message to answer the questions.

Also, I didn't install the whole Symfony framework, this is not necessary for my app. I'm just using some Symfony tools as independent components, and [DependencyInjection](https://symfony.com/doc/current/components/dependency_injection.html) component is one of them. This is exactly the same service container that is used in the framework.

To get container in services, I'm using [Service Subscriber](https://symfony.com/doc/current/service_container/service_subscribers_locators.html#defining-a-service-subscriber) pattern. By this pattern, services accept container as a paramerer to their constructors (when the parameter is type-hinted as `Psr\Container\ContainerInterface`).

If I use the container only in constructor, everything is fine: I'm only accessing constructor parameter variable and Symfony Plugin recognizes it as a container correctly. But it often needs to use a container in other methods, and to make it possible I need to store the container in service (class) property. And such property, even if it's type-hinted as a container, doesn't recognize as a container (like it shown on the 2nd screenshot in the first message).

**Comment by adamwojs** [comment]
Hi. Thank you for explanations, I was able to reproduce your issue.

**Comment by yura3d** [comment]
I've found a workaround. The behavior described in the first post started to work fine after configuring Symfony DI to compile container also to XML file in addition to existing compiled container in PHP file.

The plugin settings (PHP - Symfony - Container) prompted me to do this since only XML container files are acceptable for configuration. Does it mean the other configuration formats (PHP, YAML) are not fully supported in the plugin?

**Comment by mitelg** [comment]
I have the same problem, but I already have the container as XML. is there another way to get around this?

**Comment by yura3d** [comment]
@mitelg You need to have compiled (not config) dev (not prod) container as XML in project dir (in `var/cache/dev`, for example) on local machine. As you change something in your dependency graph, be sure that the container is updated.

**Comment by mitelg** [comment]
I have that :slightly_smiling_face:

**Comment by Haehnchen** [comment]
is working. under "current versions"

**Comment by yura3d** [comment]
@Haehnchen Today I've caught the behavior described above, but now I have correct compiled container inside `var/cache/dev`:

![image](https://user-images.githubusercontent.com/10958696/181363790-9680d499-444b-49ef-a6dd-0a4ce67b3bca.png)

PhpStorm 2022.1.4, Win11 x64
Symfony Support 2022.1.231, PHP Toolbox 6.1.0, PHP Annotations 8.2.3
Symfony 6.1.2, Flex 2.2.2
