### ISSUE TITLE
(PhpStorm) Symfony.phar / Code : 403 - Download failed

### ISSUE THREAD

**Issue by MonsieurLeonel** [Haehnchen/idea-php-symfony2-plugin#1693]
On PhpStorm 2021, in last update, I can't create project php with framework (plugin) Synfony "0.23.211"

I have attached two images of the error.

![978CDFB7-5320-466E-86B5-3AD76A55DF1A](https://user-images.githubusercontent.com/78348104/130369339-23e74826-b614-4ab3-8a57-d7dc7ee6d263.jpeg)

![A5272402-85DC-455C-A9DD-40A2F6C18D62](https://user-images.githubusercontent.com/78348104/130369349-cfde617f-e9fa-42a8-b842-b64956ca7f4b.jpeg)

**Comment by Haehnchen** [comment]
already replaced with symfony cli
