### ISSUE TITLE
Doctrine suggested type constants are deprecated for a while now

### ISSUE THREAD

**Issue by pkly** [Haehnchen/idea-php-symfony2-plugin#1695]
The `Doctrine\DBAL\Types\Type::*` constants are deprecated in newer versions of doctrine, so the type hints for `QueryBuilder::setParameter()` ($type) are invalid.
A check should be made if `Doctrine\DBAL\Types\Types` exists, if yes, only it should be used (optionally along with PDO? But it seems like it'd cause extra confusion)

**Comment by King2500** [comment]
I think it comes from bundled meta file:
https://github.com/King2500/doctrine-phpstorm-meta/blob/master/dbal/.phpstorm.meta.php

@pkly What are the correct type constants in newer Doctrine versions?

**Comment by pkly** [comment]
yeah, that's likely.
It's just the consts available in `Doctrine\DBAL\Types\Types`, we've added them manually to the suggestions in our meta file
