### ISSUE TITLE
Exception in plugin

### ISSUE THREAD

**Issue by maisoui** [Haehnchen/idea-php-symfony2-plugin#1703]
Hi,

I use PHPStorm 2021.2.1 with Symfony Plugin and I often have the following problem:
IDE Fatal Error:
java.nio.file.InvalidPathException: Illegal char <<> at index 0: <94a52ed2-357b-4612-be0d-bfdf1c06d830>/web/src/Controller/MyController.php

You can notice that the file path has invalid character "<" and ">". How to fix this ? Is it a project's configuration issue or a plugin bug ?

Best regards

**Comment by Haehnchen** [comment]
without i stacktrace; just gussing thats fixed via https://github.com/Haehnchen/idea-php-symfony2-plugin/pull/1746
