### ISSUE TITLE
ParameterBag get method autocomplete and warning

### ISSUE THREAD

**Issue by werwolf666** [Haehnchen/idea-php-symfony2-plugin#1706]
If we use object $parameterBag that implements 
Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface 

and write $parameterBag->get('some_name') we have not correct behaviour.

If 'some_name' is name of service all works fine: this value could be autocompleted and Phpstorm not show warnings.

But if 'some_name' is name of parameter Phpstorm can't find this value: it not exists in autocomplete variants and Phpstorm show warning 'Missing Service'.

PhpStorm 2021.2.1 build PS-212.5080.71
Plugin version 0.23.212
Symfony 5.2.14

**Comment by arderyp** [comment]
I'm experiencing this too, and would love a solution.

**Comment by arderyp** [comment]
@Haehnchen I'd love to hear your feedback on this if you have time. Thanks in advance :)

**Comment by bnjmnfnk** [comment]
same for Symfony\Component\DependencyInjection\ParameterBag\ContainerBagInterface

**Comment by mrFleshka** [comment]
Please add support parameters for:

`Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface`

**Comment by mrFleshka** [comment]
It works like a charm! THX!)

**Comment by S-Tian86** [comment]
Mmm... for the class 
Symfony\Component\DependencyInjection\ParameterBag\ContainerBagInterface

Not working for me.

😥

**Comment by S-Tian86** [comment]
Hi, I tried, but I don't know.
For example this Work:
```php
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;

private ParameterBagInterface $parameterBag;
//...    
$token = $this->parameterBag->get('app.token');
```

But, this don't work:
```php
use Symfony\Component\DependencyInjection\ParameterBag\ContainerBagInterface;

private ContainerBagInterface $containerBag;
//...    
$token = $this->containerBag->get('app.token');
```

In my services.yaml:

```yaml
parameters:
    app.token: '%env(TOKEN)%'
```

Thx.

Saludos.
