### ISSUE TITLE
Exception in plugin Symfony support (0.23.212)

### ISSUE THREAD

**Issue by damSilver** [Haehnchen/idea-php-symfony2-plugin#1730]
### General

Issue on Linux with PhpStorm 2021.2.3, similar to other reports.

### PhpStorm Info

PhpStorm 2021.2.3
Build #PS-212.5457.49, built on October 13, 2021
Subscription is active until October 13, 2022.
Runtime version: 11.0.12+7-b1504.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.11.0-38-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: de.espend.idea.php.toolbox (6.0.0), de.espend.idea.laravel (0.15.4), de.espend.idea.php.annotation (8.0.0), fr.adrienbrault.idea.symfony2plugin (0.23.212), com.ibexa.dxp.plugin (1.5.0)
Current Desktop: ubuntu:GNOME

### Error Message
java.lang.Throwable: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@2c15676f != fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@51d9069a
  which is 0th element of [fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@2c15676f, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@2bb6890e, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1e5dd043, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@19f4f2f8, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@80ca8a, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1f61dd6d, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@6fced90a, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@51139539, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5741d10b, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@465af43b, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5fc57373, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@12b28fef, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@4ba2cd3b, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5ac80358, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@2e62bd99, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@2829924d, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@753f4966, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@6ff7465a, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@54c2a048, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@301deb67, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@3f66e07b, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@6af6b45b, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@2b7799ad, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@74ee0977, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@7c834aa9, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@23086d0e, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@34252233, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@30042071, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5634f2da, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@3634950f, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@2b9d0d40, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@3a8ba7ea, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@4b582043, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@59d658ca, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1ae2a9bd, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@7d31f9fc, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@77e18421, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1c1a921f, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@133a6f60, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@61b68ae2, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1a0dca79, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@52cf294d, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@124e0d1b, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@477a642a, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@335030be, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@18fef2d8, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@7a3a0209, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@6ef57250, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5c926af0, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@33152b88, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@19154da9, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5cb7db29, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@133defa5, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@9eedf21, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@3a25a3b0, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5829494e, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@2415d529, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5b7d015d, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@4cd201a1, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5e23524c, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5495683c, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@67d1ec1a, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@3bd22648, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@7fa7a24c, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@ce10c, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@68d57c2b, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@429fe71f, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@e898c2, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@670b0d52, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@247c11bc, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1966ad33, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5d8c1855, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@62d2ef2b, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@26e7e33c, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@a44cde6, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@3737324b, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@42692831, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5b0ecd43, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@77091039, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@7922d1f9, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@7281464c, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@5fc8f98a, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@607fa292, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@f3d1a7d] and [fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@51d9069a, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@77f69ef0, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@6fea2d2d, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@721c6970, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@15957bbc, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@56d766e0, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@68eaaa52, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@792c09d6, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@47dad5d4, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@2ad74ba9, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@17d2cc9b, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@ea9050e, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1fcc157a, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@fd68f29, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@e612c5c, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@4826d9eb, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@37be6250, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@caa0c49, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@baed24c, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@75b9ab53, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@31d1eb56, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@6dc57161, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1004f227, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@285f3047, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@16eae541, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@50e2d084, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@67c08575, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@36cc4cc2, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@774d67b7, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@316dff2a, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@52653f5f, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@69bd38d, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1af76c36, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@443d44ed, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@3f5904f2, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@6706bf2f, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@46b1f925, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@6885c732, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1f0c2044, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@4da10b4d, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@410bb0d, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@42ea50ea, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@3c1a56f3, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@7924d95e, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@786dcda4, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@6810bf43, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@6d3c17c, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@596216d1, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@4ff4e0b4, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@2273a4ae, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@3ab359bd, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@73ae14a4, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@1bb7bb25, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@245e3a29, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@480e1ae, fr.adrienbrault.idea.symfony2plugin.templating.path.TwigPath@708deae, fr.adrienbrault.idea.symfony2plugin.templatin ...

**Comment by Haehnchen** [comment]
duplicate #1554
