### ISSUE TITLE
Question: support for custom annotations / attributes?

### ISSUE THREAD

**Issue by dfreudenberger** [Haehnchen/idea-php-symfony2-plugin#1731]
Hey,

first of all thank you for dedicating some of your time to this project.

Is there a way to give hints to the plugin about the context and thus the actions that should be available?

I.e. the first example works perfectly fine, while the second one has no context support anymore

```php
public function someAction(): Response
{
    return $this->redirectToRoute('command space will show a list of routes', 'command space will show a list of route params');
}
```

```php
public function someAction(): Response
{
    return $this->anotherMethod('no context here', 'and no context here');
}

private function anotherMethod(string $route, array $params): Response
{
    return $this->redirectToRoute($route, $params);
}
```

I have not checked the sources of this or any other intellij plugin so far, but maybe we could do sth. like the following to give some hints to the plugin.

```php
#[RouteName('route')]
#[RouteParams('params')]
private function anotherMethod(string $route, array $params): Response { ... }
```

And of course the same could be done for all kind of contextual help (i.e. translation keys)

**Comment by LPodolski** [comment]
yes it's called has tags and it is in documentation: https://symfony2-plugin.espend.de/extension/method_parameter.html#hash-tags
