### ISSUE TITLE
Change the default values of configuration

### ISSUE THREAD

**Issue by N445** [Haehnchen/idea-php-symfony2-plugin#1736]
# Change default values for

- Translation Root Path
- App Directory
- Web Directory

## Old values
- `app/cache/dev/translations`
- `app`
- `web`

## New Values

Compatibility with symfony 4/5 and maybe 6

- `translations`
- `src`
- `public`

**Comment by madalinignisca** [comment]
I have a fresh installation.
**App Directory** was set to `app`.
**Web Directory** was to `public`. (resets to `web` if I hit Default)
I am not sure about **Translations Root Path**. I found it on new symfony project created set to `var/cache/dev/translations` (exists and has a lot of generated files in), and on hitting Default, it reset to the above `app/cache/dev/translations`.

Where it should point really, to `/translations` or `/var/cache/dev/translations`?

**Comment by madalinignisca** [comment]
Translations must be on `/var/cache/dev/translations`, as per docs in Jetbrains

**Comment by vjandrea** [comment]
@madalinignisca it works perfectly fines also pointing directly to /translations; just tested both settings in a Symfony 6 project https://github.com/vjandrea/idea-plugin-testing

**Comment by Haehnchen** [comment]
- i changed what is possible to match new file structure
- mainly all settings are optional, as there is now much more smarter directory guessing during runtime
- form UI will get some optimization to reflect this
