### ISSUE TITLE
add support .php translations

### ISSUE THREAD

**Issue by FluffyDiscord** [Haehnchen/idea-php-symfony2-plugin#1764]
Hi, would it be possible to add support for translations being in a .php file instead of xaml ?

**Comment by faizanakram99** [comment]
@Haehnchen 

Ever since we changed translation files from xlf to php, we lost whole translation support in IDE.

![image](https://user-images.githubusercontent.com/10880992/165060768-955468a0-5d31-4c3f-916c-573387f13388.png)

**Comment by Haehnchen** [comment]
yes this is also supported. check path configration

![image](https://user-images.githubusercontent.com/1011712/165130145-227d8955-ddda-42ad-b6a6-0fea36bb1e8b.png)

**Comment by faizanakram99** [comment]
> yes this is also supported. check path configration

It is already set and translations are still not recognized, hence my question why doesn't it work with .php files but works with .yaml, .xliff and .xlf files ?

![image](https://user-images.githubusercontent.com/10880992/165277134-6ffa9935-f059-4658-88ce-9689ad2e2465.png)

**Comment by Haehnchen** [comment]
> why doesn't it work with .php

i never had the personal need for this. no, "cached path" has a complete different format and structure. if you want php support wait for the next release.

**Comment by faizanakram99** [comment]
> "cached path" has a complete different format and structure.

Indeed, it is the same though regardless of translation file (yaml, php, xlf or even database translations).

> if you want php support wait for the next release.

Understood, thank you very much.

**Comment by FluffyDiscord** [comment]
I think the #1872 will fail if the transkation key/value is something dynamic, like a php constant or YourClass::class

**Comment by Haehnchen** [comment]
yes it will fail, but inside an index process there no technically way to resolve this value. as the use case for php translation in projects is already rar, a constant or other php logic is not worth to implement.
