### ISSUE TITLE
Error in the plugin

### ISSUE THREAD

**Issue by Graber1407** [Haehnchen/idea-php-symfony2-plugin#1766]
Error in the "Symfony Support" plugin

Hello!  I have a problem when creating a Symfony project. (PhpStorm **2021.3.2**)

Screenshots:
![2022-02-01_17-32-53](https://user-images.githubusercontent.com/88322043/151988422-5f9e1015-4364-498e-a221-ca62dea32f30.png)
![2022-02-01_17-33-20](https://user-images.githubusercontent.com/88322043/151988449-01234de7-bbf9-4ffc-bc18-5061aa7052ff.png)

**Comment by jonmnoj** [comment]
See #1310

**Comment by Haehnchen** [comment]
duplicate closed
