### ISSUE TITLE
"Missing template" when omitting file extensions (.html.twig) or underscore in PhpStorm

### ISSUE THREAD

**Issue by D3strukt0r** [Haehnchen/idea-php-symfony2-plugin#1770]
https://stackoverflow.com/questions/71183915/
This issue stems from my Stackoverflow issue.

I'm using CraftCMS which uses Twig as templating system. However, I'd like to refer to my twig files without file extensions or underscores, just like it works in JS (e.g. `import './js/scripts'` (`scripts.js`)) and SCSS (e.g. `@import './variables'` (`_variables.scss`)). CraftCMS supports omitting file extensions, but not underscores (or I simply don't know of a way yet)

The ones commented with "Fails", is due to CraftCMS and might be fixed somewhere later, but for the others it would be great, if this plugin somehow supported figuring out that they actually exist, and preferably configurable in a window or something.
<img width="818" alt="sePny" src="https://user-images.githubusercontent.com/5726865/156597888-bb8e9d83-a20e-45ee-b2b9-7a5ac20ed380.png">

**Comment by Haehnchen** [comment]
as this is an non official Symfony way and running into an exception as file not found, closing this
