### ISSUE TITLE
PHP8 doctrine autocomplete attributes work incorrectly.

### ISSUE THREAD

**Issue by berkut1** [Haehnchen/idea-php-symfony2-plugin#1789]
There is an issue with autocomplete of Column `type` attribute.
![php8attr](https://user-images.githubusercontent.com/13355990/160323796-651bd2e8-d4b9-4066-8229-d95434b8dbfd.png)

It starts working if you use it as an array
![php8attrArr](https://user-images.githubusercontent.com/13355990/160323844-1d86e540-5eac-49dd-b993-47fa6ce3bb23.png)

But that is wrong, `type` can't accept array.

**Comment by Haehnchen** [comment]
fixed via https://github.com/Haehnchen/idea-php-annotation-plugin/pull/235
