### ISSUE TITLE
"lowercase letters for service and parameter" when the built-in functiions-like constructions used in FQCN

### ISSUE THREAD

**Issue by sc0rp10** [Haehnchen/idea-php-symfony2-plugin#1850]
Hi
`Symfony: lowercase letters for service and parameter` firing when I use function-like constructions (die, empty, isset, print etc) as a part of namespace.

For example, FQCN `App\Foo\Print` marked as wrong, same as `App\Foo\Echo`, `App\Foo\Isset` etc. But `App\Foo\Printer` is OK.

You can check attached screen recording by the following [link](https://cdn.weblab.pro/2b1v2.mp4)

**Comment by andrew-demb** [comment]
This inspection has been dropped from the plugin as of https://github.com/Haehnchen/idea-php-symfony2-plugin/pull/1839
