### ISSUE TITLE
Symfony Support is not compatible with WebStorm.

### ISSUE THREAD

**Issue by CyrilKrylatov** [Haehnchen/idea-php-symfony2-plugin#1885]
Hi,

Is there any reason why this plugin is not compatible with WebStorm?

Thank you for your time!

Cheers,

**Comment by Haehnchen** [comment]
its defined automatically via the plugin dependencies. i would say `com.jetbrains.php` is limiting it, but without it simply nothing works. see https://plugins.jetbrains.com/docs/intellij/plugin-compatibility.html#modules-specific-to-functionality
