### ISSUE TITLE
Having a paid license, paid inspections are not showing up

### ISSUE THREAD

**Issue by devnix** [Haehnchen/idea-php-symfony2-plugin#1968]
I'm trying to trigger any of the inspections listed [here](https://espend.de/phpstorm/plugin/symfony#completion), but it doesn't show anything.

The plugin seems to be configured right, as icons are showing up on `services.yaml`, doctrine xmls are performing code completions, routes and twigs are working too, etc.

**Comment by Haehnchen** [comment]
Its working without any problem: as you linked something else maybe you except something else?

**example of a paid feature**

![image](https://user-images.githubusercontent.com/1011712/174632522-edcaa535-0982-4bf2-a34d-bec19fed5ade.png)

**license status**

![image](https://user-images.githubusercontent.com/1011712/174632607-d3e9470e-8eac-4568-b95f-ebf466e0c4a6.png)

**Comment by devnix** [comment]
Here is an example like yours, overwriting a block to show that the plugin is working, but pro features don't:
![image](https://user-images.githubusercontent.com/1777519/174634177-0b2f7bc9-81b5-4b86-9f6e-f7dd59b4f47f.png)

AFAIK, the plugin should detect the license correctly: 
![image](https://user-images.githubusercontent.com/1777519/174634386-1b70f817-dfbb-455d-bff5-ea6e5989b7e1.png)

I've disabled every non-bundled extension but it's just not working. Previously I was using EAP, now I'm using the stable version: 
![image](https://user-images.githubusercontent.com/1777519/174634860-867f7e8d-6221-41f9-8529-6123ae4882be.png)

Is there anything I can do to debug this?

**Comment by Haehnchen** [comment]
I checked now alot of stuff, but mainly i am thinking your license is somehow falling outside the prefix check https://github.com/JetBrains/marketplace-makemecoffee-plugin/blob/master/src/main/java/com/company/license/CheckLicense.java#L116. Possible i will just remove it, even if that is the documented way.

can please check:

- reopen phpstorm / reopen project: you have ~15min after open where all feature are available and check if you see the inspection
- maybe you just have disabled the inspections somehow?

![image](https://user-images.githubusercontent.com/1011712/174659203-402f57d6-19c3-4cad-a411-36cd63d3029b.png)

**Comment by devnix** [comment]
Oh snap: 
![image](https://user-images.githubusercontent.com/1777519/174659735-df761f30-ac74-4afb-b22e-cbe51ff959ae.png)
![image](https://user-images.githubusercontent.com/1777519/174659928-9accf1d2-eb97-490e-929c-46fd60373acf.png)
![image](https://user-images.githubusercontent.com/1777519/174660087-e374e9d0-b2f7-473a-958e-a30fc0d82caa.png)

I don't have any clue why these could be disabled.

Thanks for your patience!
