### ISSUE TITLE
[Feature] Support translation autocomplete on form constraints with named arguments

### ISSUE THREAD

**Issue by SVillette** [Haehnchen/idea-php-symfony2-plugin#1969]
## Description
The  translation autocomplete feature on constraints is already working and is working well. But recently Symfony changed constraints signature and allowed named arguments instead of using an associative array:

### Before
```php
$builder
    ->add('foo', TextType::class, [
        'label' => 'app.form.foo',
        'constraints' => [
            new NotBlank([
                'message' => 'app.foo.not_blank',
                'groups' => ['app_foo']
            ])
        ]
    ])
;
```

### After
```php
$builder
    ->add('foo', TextType::class, [
        'label' => 'app.form.foo',
        'constraints' => [
            new NotBlank(
                message: 'app.foo.not_blank',
                groups: ['app_foo']
            )
        ]
    ])
;
```

That would be a great feature to have the same autocomplete with constraints with named arguments

**EDIT** : The navigation feature (go to translation declaration) would be nice too

**Comment by Haehnchen** [comment]
added

**Comment by SVillette** [comment]
Thanks a lot !
