### ISSUE TITLE
Support manifest.json w/o Webpack Encore

### ISSUE THREAD

**Issue by althaus** [Haehnchen/idea-php-symfony2-plugin#2006]
Hey,

in https://github.com/Haehnchen/idea-php-symfony2-plugin/commit/3c4182e3878615178eb90c322ff8718fce7d642a you've added support for reading assets from a manifest.json. The path is hardcoded to `build/manifest.json` in the web directory.

We're using Webpack without Encore and our build path has a different name. It'd be great if the plugin could either just glob for the manifest files or the path could configurable or multiple paths could be configured.

Cheers
Matthias

**Comment by Haehnchen** [comment]
:+1: every file named "manifest.json" independent from is path is now also taken
