### ISSUE TITLE
Plugin does not install on host via JetBrains Gateway in PHPStorm.

### ISSUE THREAD

**Issue by lpeabody** [Haehnchen/idea-php-symfony2-plugin#2012]
In case this is a bug I'm leaving a quick bit of feedback. I'm setting up a project with Gitpod using JetBrains Gateway and I'm unable to install the Symfony Support plugin. It seems to start the install and then just hangs forever. There doesn't appear to be any log data. Maybe someone else can verify? Given how beta Gateway is, and also how beta Gitpod is, I wouldn't be surprised if this issue lay outside of the scope of this plugin, but figured I would post just in case.

**Comment by Haehnchen** [comment]
just i guess: maybe they need a hot reload plugin (dynamic plugins), as this plugin is having an optional "paid" flag this feature is sadly automatically deactivated. 

maybe a quick idea would be try it eg with https://github.com/Haehnchen/idea-php-annotation-plugin, its supporting dynamic plugin loading.
