### ISSUE TITLE
[Translation] Add autocompletion and navigation for named arguments

### ISSUE THREAD

**Issue by SVillette** [Haehnchen/idea-php-symfony2-plugin#2015]
## Description
When using the translator service with a non default domain (e.g. "validators"), the autocompletion works when the domain is passed as the third argument but not when using PHP8 named arguments.

```php
this->translator->trans('app.existing_translation', domain: 'validators') // Warning: "Symfony: Missing translation key"
```

In a global way, supporting autcompletion and navigation when using PHP named arguments would be a nice feature (as you started to support it for Symfony constraints classes).

**Comment by Haehnchen** [comment]
added, translations are special cases because of 2 parameters id+domain. others are already behind an abtraction layer and will added also.

**Comment by SVillette** [comment]
Thank you @Haehnchen
