### ISSUE TITLE
Deprecated doctrine type not reported in attributes

### ISSUE THREAD

**Issue by acrobat** [Haehnchen/idea-php-symfony2-plugin#2018]
The doctrine `array` field type is deprecated and shows in strikethrough in the annotations but not in attributes

![image](https://user-images.githubusercontent.com/1374857/195597901-6480194e-9938-4659-8a59-99b5de01f2bc.png)

**Comment by Haehnchen** [comment]
not sure where i implemented it, but i think it was not here. will check :)

https://github.com/Haehnchen/idea-php-annotation-plugin

**Comment by acrobat** [comment]
Fixed in the latest php-annotation plugin release. Thanks @Haehnchen!
