### ISSUE TITLE
Creating a routing method already ending in Action appends a second Action

### ISSUE THREAD

**Issue by CJDennis** [Haehnchen/idea-php-symfony2-plugin#2043]
In the routing files a few autocomplete options are available. For a route controller, pressing [Ctrl]+[Space] will present the entirety of existing Controller methods including the appended `Action`. However, when using "Create Method", missing methods are always created with `Action` appended regardless of whether the missing method in the routing file already ends with `Action` or not.

If a route does **not** already end with `Action`, it is appended to the method name when it is created.
`routing.yaml`
```yaml
my_foo_route:
  path: /foo
  controller: MyController::foo
```

`MyController.php`
```php
class MyController {
  // correct
  public function fooAction() {
  }
}
```

If a route **does** already end with `Action`, it is **also** appended to the method name when it is created.
`routing.yaml`
```yaml
my_foo_route:
  path: /foo
  controller: MyController::fooAction
```

`MyController.php`
```php
class MyController {
  // incorrect
  public function fooActionAction() {
  }
}
```

If the routing method already ends with `Action`, a second `Action` should not be appended to it. It should also create a method like this:

`MyController.php`
```php
class MyController {
  // correct
  public function fooAction() {
  }
}
```

Perhaps pressing [Ctrl]+[Space] should present the existing methods both with and without the final `Action` to indicate that either are allowed.

`routing.yaml`
```yaml
my_foo_route:
  path: /foo
  controller: MyController::|
            +------------------------------------+
            | MyController::existingMethod       |
            | MyController::existingMethodAction |
            +------------------------------------+
```
where `|` is the cursor position before pressing [Ctrl]+[Space] and the "box" contains the autocomplete options.

**Comment by Haehnchen** [comment]
action was removed via: https://github.com/Haehnchen/idea-php-symfony2-plugin/pull/2341
