### ISSUE TITLE
Symfony 6.2: No longer required to use $form->createView()

### ISSUE THREAD

**Issue by pauljura** [Haehnchen/idea-php-symfony2-plugin#2059]
Hi, just a simple change in Symfony 6.2, you can pass a form directly to a view without calling createView()

I've disabled the inspection in my project, but perhaps you could detect from composer if the project is >= 6.2 and automatically disable.

Thanks

See: https://symfony.com/blog/new-in-symfony-6-2-dx-improvements#simpler-form-rendering

**Comment by NetworkDevHead** [comment]
This is a simple fix please update the plugin, it impacts every project after Symfony 6.2 with a bad inspection on forms
