### ISSUE TITLE
I bought the license, now what?

### ISSUE THREAD

**Issue by lostfocus** [Haehnchen/idea-php-symfony2-plugin#2062]
Hi,
I just bought a yearly license in the marketplace, how do I get the plugin to understand that I did? The JetBrains license page says "Please sign in to Symfony Support with your JetBrains Account credentials." - where would I do that?

**Comment by Haehnchen** [comment]
Its the same dialog as activating a PhpStorm license itself:

- Help -> Register or
- Everywhere Search -> Manage Licenses

**Comment by lostfocus** [comment]
Thanks a lot. Apparently it also auto-updates the license data when updating PHPStorm and/or the plugin.
