### ISSUE TITLE
PHP Configuration support

### ISSUE THREAD

**Issue by enumag** [Haehnchen/idea-php-symfony2-plugin#2064]
I'd like to use PHP configuration instead of YAML. It's possible to transform everything using this [tool](https://github.com/symplify/config-transformer).

However when I did that the "Navigate to definition" icon no longer works. It seems this plugin only supports YAML config.

**Comment by Haehnchen** [comment]
for transform there should be used external tools.

navigation and service index are in. needs some more optimized that will follow.

![image](https://github.com/Haehnchen/idea-php-symfony2-plugin/assets/1011712/6161760c-b5da-459f-bb5f-515d575a17d1)
