### ISSUE TITLE
For loop variable autocompletion

### ISSUE THREAD

**Issue by wojtas** [Haehnchen/idea-php-symfony2-plugin#208]
Would it be possible to support variable autocompletion in for loops? 

Example (for demonstration purpose I wrote these two hypothetical classes which illustrate my use case):

```php
class MyObject
{
    public function getName() { return 'test'; }
}

class MyService
{
    protected $myObjectList;

    /**
    * @return MyObject[]
    */
    public function getMyObjectList()
    {
        return $this->myObjectList;
    }
}
```

Then in Twig I have an object which is instance of ```MyService``` class, and it is autocompleted nicely:

![image](https://f.cloud.github.com/assets/800260/1878491/4410cabe-793c-11e3-8f22-0e5c4b26e831.png)

but this single loop element ```module```, even if it has a proper PHPDoc annotation, gets no autocompletion:

![image](https://f.cloud.github.com/assets/800260/1878508/8546fd82-793c-11e3-94f6-a24a54720db7.png)

**Comment by Haehnchen** [comment]
fixed. optimization also needed for  #444 later

**Comment by gharlan** [comment]
So, shouldn't autocompletion for `user` work here?

![screenshot 2015-03-10 11 59 20](https://cloud.githubusercontent.com/assets/330436/6573648/585b5e00-c71d-11e4-8477-7fe9a13e540b.png)

The type of `user` is empty, but it should be `\AppBundle\Model\User`..
So I don't get autocompletion for `lastName` etc.

I'm using PhpStorm 9 EAP and sf2 plugin 0.11.86.
