### ISSUE TITLE
[Suggestion] Extracting the signature provider to a separate plugin

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-symfony2-plugin#212]
Currently, the possibility to define custom signature providers through the settings requires enabling the Symfony2 plugin on non-symfony projects. This seems quite weird.

Would it be possible to extract this into a separate plugin (which would then be a dependency of the symfony2 plugin) to be able to use it separately ?
I guess it could even help people wanting to build a plugin for a different framework, as it would become possible to share the logic instead of duplicating it.

**Comment by Haehnchen** [comment]
implemented in https://github.com/Haehnchen/idea-php-toolbox. todo ref: https://github.com/Haehnchen/idea-php-toolbox/issues/1
