### ISSUE TITLE
Doctrine mappedBy/inversedBy attributes

### ISSUE THREAD

**Issue by Gemorroj** [Haehnchen/idea-php-symfony2-plugin#2164]
Currently the plugin shows tooltips only for annotations `mappedBy/inversedBy`, but not for attributes.
![Screen-2023-05-19_14-32-34](https://github.com/Haehnchen/idea-php-symfony2-plugin/assets/885731/947002a1-4bed-4db8-b3a1-2666f05821ff)
![Screen-2023-05-19_14-33-02](https://github.com/Haehnchen/idea-php-symfony2-plugin/assets/885731/7209caf0-394f-4719-b542-0e47456d5d44)

**Comment by Haehnchen** [comment]
fixed via https://github.com/Haehnchen/idea-php-annotation-plugin/pull/283
