### ISSUE TITLE
Importmap support for resolving packages

### ISSUE THREAD

**Issue by weaverryan** [Haehnchen/idea-php-symfony2-plugin#2178]
Hi!

I'm not sure if this would best fit into the plugin or inside PHPstorm itself... I'd love to know what you think.

Suppose we have:

```
// assets/app.js

import _ from 'lodash';
```

There is no `package.json` in this project, as it's using AssetMapper. Instead, there is an `importmap.php` file, which has this:

```php
return [
    // ...
    'lodash' => [
        'url' => 'https://cdn.jsdelivr.net/npm/lodash@4.17.21/+esm',
    ],
];
```

This results in an `importmap` being output on the page for the browser so that when we import `lodash`, we are actually getting it from that CDN URL. The "idea" is that PhpStorm would recognize this give auto-completion when coding.

I "think" that doing this involves having PhpStorm "download" (or at least offer us the ability to download it - like when you have a `<script src="https://cdn.jsdelivr.net/npm/lodash@4.17.21/+esm>` inside an HTML file) the file. If I add the `<script>` tag to `base.html.twig`, hit "Download", then delete it, I DO get auto-completion (though, as minor secondary issue, PhpStorm still highlights that library with the option to add it to `package.json`)

<img width="587" alt="Screenshot 2023-06-20 at 11 25 52 AM" src="https://github.com/Haehnchen/idea-php-symfony2-plugin/assets/121003/fa54df99-1e4f-46c3-927a-81ab8960256c">

WDYT?

**Comment by Haehnchen** [comment]
from what i know there is a build in feature to resolve external packages via url, maybe there is a way to trigger it via a fake file or there are some extension points that allow to register the modules.

both need to check firstly in detail, but loading an `importmap.php` will not make it into PhpStorm itself, i guess, and needs to be done via a external plugin.

**Comment by weaverryan** [comment]
> from what i know there is a build in feature to resolve external packages via url, maybe there is a way to trigger it via a fake file or there are some extension points that allow to register the modules

Exactly - the "feature" if resolving external packages via a URL is there... so the question is: can this be hooked into. Unfortunately, I don't know the answer :p 

> both need to check firstly in detail, but loading an importmap.php will not make it into PhpStorm itself, i guess, and needs to be done via a external plugin.

👍

**Comment by Haehnchen** [comment]
https://blog.jetbrains.com/phpstorm/2024/04/phpstorm-2024-1-is-now-available/#support-for-symfony’s-assetmapper
closed. asset mapper is include in PhpStorm itself, features should go directly into their issue tracker.
