### ISSUE TITLE
Issue with applying #[TaggedLocator] attribute on properties in Symfony

### ISSUE THREAD

**Issue by MichaelBrauner** [Haehnchen/idea-php-symfony2-plugin#2179]
I am attempting to use the #[TaggedLocator] attribute in a Symfony application by applying it to a class property. However, I'm encountering an error message: `"Attribute cannot be applied to a property because it does not contain the 'Attribute::TARGET_PROPERTY' flag"`.

I'm currently using PHP 8.2 and Symfony 6.2, so this functionality should be supported. 
Both Psalm and PHPStan have identified no issues with the code.

Here's a sample of the code I'm using:

```php
<?php
declare(strict_types=1);

namespace App\Service;

use App\JiraTickets\CreateClientJiraTicket;
use Psr\Container\ContainerInterface;
use Symfony\Component\DependencyInjection\Attribute\TaggedLocator;

readonly class JiraTicketService
{
    public function __construct(
        #[TaggedLocator('app.jira_ticket')]
        private ContainerInterface $locator,
    )
    {
    }
}
```

Any help or insights into why this may be happening would be greatly appreciated.

**Comment by Haehnchen** [comment]
its a phpstorm issue and will be fixed in `2023.2`: https://youtrack.jetbrains.com/issue/WI-55697/Non-applicable-attribute-target-declaration-TARGETPARAMETER-is-marked-as-invalid-for-attribute-for-promoted-property
