### ISSUE TITLE
@Route is never used and this is false

### ISSUE THREAD

**Issue by ibasaw** [Haehnchen/idea-php-symfony2-plugin#2204]
hi,

since a few days, i got an issue with this plugins, it does not detect anymore the route file in the vendor directory, and show an error in the console, see screenshot

![2023-08-09_09-56](https://github.com/Haehnchen/idea-php-symfony2-plugin/assets/313704/8e1eb6c1-f244-4462-b12e-24cd20ba38d9)

Symfony 3.4
Phpstorm 2023.2

**Comment by zelding** [comment]
I'm having the same issue with `ORM` annotations on entities;

Looks like the last patch broke the 'dockblock sniffing'

**Comment by Haehnchen** [comment]
see https://github.com/Haehnchen/idea-php-annotation-plugin/issues/290 :)
