### ISSUE TITLE
Unused import: "Unused statement use" reported when using Doctrine annotations

### ISSUE THREAD

**Issue by seitechsoftware** [Haehnchen/idea-php-symfony2-plugin#2209]
The problem is, in code inspection, PHPStorm reports:

Alias 'Doctrine\ORM\Mapping AS ORM' is never used

This has started to happen with the new version of PhpStorm 2023.2, rollback to PhpStorm 2023.1.4 solves de issue.

[https://youtrack.jetbrains.com/issue/WI-14448](https://youtrack.jetbrains.com/issue/WI-14448)

**Comment by Haehnchen** [comment]
see https://github.com/Haehnchen/idea-php-annotation-plugin/issues/290 :)
