### ISSUE TITLE
Symfony: You probably want to inject the parameter "kernel.project_dir" inside Kernel class / implementation

### ISSUE THREAD

**Issue by alcohol** [Haehnchen/idea-php-symfony2-plugin#2222]
This check should probably be ignored when inside a class that extends or implements the `KernelInterface`?

![image](https://github.com/Haehnchen/idea-php-symfony2-plugin/assets/21414/c13f9a0a-046d-4308-ab68-e92baf6bccbc)

**Comment by curry684** [comment]
Came here for the same one   😉 

![image](https://github.com/Haehnchen/idea-php-symfony2-plugin/assets/1455673/09a099a7-818b-44c7-9367-0fca11e0b0e2)

> This check should probably be ignored when inside a class that extends or implements the KernelInterface?

As the plugin parses `services.yaml` to know exactly which services exist a simpler fix should be to only show any "injection is possible" warning when dependency injection is possible at all.

**Comment by Haehnchen** [comment]
fixed: as Kernel::class is injectable, its now hiding not itself, based on the interface.
