### ISSUE TITLE
AssetMapper: Possible for the method autocomplete to be even more precise

### ISSUE THREAD

**Issue by weaverryan** [Haehnchen/idea-php-symfony2-plugin#2263]
Hi @Haehnchen!

Really nice to finally meet you last week - you are such an asset (no pun intended) to the Symfony World :). You may have noticed in my closing Keynote that, after your recommendation, I upgraded to the LATEST version of the plugin so I would get some nice auto-completion when importing assets installed via `importmap:require`. That was excellent :).

Now I'm wondering one further thing. In the video below, when I type `hljs.`, it seems to autocomplete *every* possible method, instead of the specific functions available from the specific file that was imported. Is that accurate? I think, normally, if PhpStorm is *sure* about the methods from an import, they'll be on top and in bold. Is this expected or something that can be improved even further?

Thank you!

https://github.com/Haehnchen/idea-php-symfony2-plugin/assets/121003/2cf38650-d9ed-415a-8914-81880d7f266a

**Comment by Haehnchen** [comment]
> Really nice to finally meet you last week - you are such an asset (no pun intended) to the Symfony World

thank you for the live coding and the running SymfonyCast episodes, that helps even more to understand it from user experience side.

> it seems to autocomplete every possible method

the problem: its provided by PhpStorm even for other elements, but not in more strict known type elements, so i will check if this behavior is able to disable here.

![image](https://github.com/Haehnchen/idea-php-symfony2-plugin/assets/1011712/63c95718-df3f-4358-8e51-52cfa0d6aa1d)

![image](https://github.com/Haehnchen/idea-php-symfony2-plugin/assets/1011712/cd711deb-548c-41ef-99ca-7cc0a1cd6fba)

**Comment by Haehnchen** [comment]
https://blog.jetbrains.com/phpstorm/2024/04/phpstorm-2024-1-is-now-available/#support-for-symfony’s-assetmapper
closed. asset mapper is include in PhpStorm itself, features should go directly into their issue tracker.
