### ISSUE TITLE
[AssetMapper] Scoped npm packages (e.g. @hotwired/turbo) not resolved

### ISSUE THREAD

**Issue by adeys** [Haehnchen/idea-php-symfony2-plugin#2274]
Hi @Haehnchen

Thanks for the really great work you're doing on this plugin.
The support for `importmap` is also very helpful. But as shown as on the below pictures, scoped npm packages (`@hotwired/turbo`, `@hotwired/stimulus`) are not fully resolved and the autocomplete is biased. 

![Packages unresolved](https://github.com/Haehnchen/idea-php-symfony2-plugin/assets/45217162/53e123c5-0c44-4552-9fb1-96167afc379b)

This is resolved when I copy `assets/vendor/@hotwired/stimulus/stimulus.index.js` to `assets/vendor/@hotwired/stimulus.js`
![Packages resolved](https://github.com/Haehnchen/idea-php-symfony2-plugin/assets/45217162/606bdad0-c6b6-40b7-98f2-72525b48f181)

Digging through the code it should be fixed by checking the specific case of scoped npm packages when a file has slashes. I'll propose a fix PR in the comment.

Thanks

**Comment by adeys** [comment]
Proposed fix : #2275

**Comment by chapterjason** [comment]
What about typescript?

**Comment by adeys** [comment]
Hey @chapterjason,

Are you talking about stimulus controllers written using typescript ?

**Comment by chapterjason** [comment]
@adeys Yes

**Comment by adeys** [comment]
@chapterjason It works with typescript controllers too.
The dependencies are resolved by the plugin but you'll have to tweak your `tsconfig.json` file to make typescript compiler happy

**Comment by Haehnchen** [comment]
https://blog.jetbrains.com/phpstorm/2024/04/phpstorm-2024-1-is-now-available/#support-for-symfony’s-assetmapper
closed. asset mapper is include in PhpStorm itself, features should go directly into their issue tracker.
