### ISSUE TITLE
The colors are causing me panic attacks (almost) - what secret setting changes it?

### ISSUE THREAD

**Issue by torian257x** [Haehnchen/idea-php-symfony2-plugin#2276]
See for yourself:

![image](https://github.com/Haehnchen/idea-php-symfony2-plugin/assets/2072058/4c884259-57b9-40e5-aa6c-b00f33e4d672)

I went through all color scheme settings TWICE. None seem to change this. There is no visible setting in phpstorm to fix this.

I shall perish earlier than expected working like this

you can reproduce as well when using the solarized theme, looks ugly  too even though not as ugly as this
[Solarized_Dark.icls.zip](https://github.com/Haehnchen/idea-php-symfony2-plugin/files/13795657/Solarized_Dark.icls.zip)

I searched for the weird highlight colors in the exported color schemes without success. It isnt imported. This is the devils spawn of this plugin

**Comment by Haehnchen** [comment]
There is nothing provided by this plugin.

it looks like its related to the latest PhpStorm releases which introduce some support for querybuilder parameters, there is now injecting of custom dql language into this parameters, in which the custom(?) theme does not provide support for it.

**Comment by torian257x** [comment]
@Haehnchen how can this be from phpstorm if it disappears when you uninstall the plugin?
