### ISSUE TITLE
Lazy/Fuzzy search in Symfony2 view/tool window

### ISSUE THREAD

**Issue by Blackskyliner** [Haehnchen/idea-php-symfony2-plugin#229]
The view for templates, services and routes is (as far as I'm concerned) the only search field in phpStorm that I use with no fuzzy search. Every time I screw up because it's so different of the other search fields...

Maybe this could be added?

**Comment by Rvanlaak** [comment]
The `:` sign can be used to goto a line number within a file, so that maybe can be used to search for a route within a file. Maybe a filename isn't even necessary, and is the following enough

```
:route_name
```
