### ISSUE TITLE
Doctrine DQL support

### ISSUE THREAD

**Issue by hoshsadiq** [Haehnchen/idea-php-symfony2-plugin#230]
It would be nice to support Doctrine Query Language, or at least suppress the error generated by PhpStorm on the colon within DQL and make the entities clickable. [There's a ticket opened on JetBrains YouTrack to support DQL](http://youtrack.jetbrains.com/issue/WI-9948).

**Comment by J7mbo** [comment]
This would be great. Why? I'm using doctrine's `INSTANCE OF` within the query for querying the discriminator within inheritance mapping. Obviously `INSTANCE OF` is not valid SQL.

**Comment by ngse** [comment]
+1 - would be most useful, I work around the highlighting errors at the moment

**Comment by olekhy** [comment]
+1

**Comment by mops1k** [comment]
+1

**Comment by olekhy** [comment]
+1

**Comment by zanderbaldwin** [comment]
+1

**Comment by m0003r** [comment]
+1

**Comment by MikeTralala** [comment]
+1

**Comment by tstrijdhorst** [comment]
+1

**Comment by CarsonF** [comment]
+1

**Comment by CodyBohn** [comment]
+1

**Comment by qaiser110** [comment]
+1

**Comment by Keeo** [comment]
+1

**Comment by matthbull** [comment]
and another +1. it would be incredibly useful

**Comment by thetrompf** [comment]
yet another +1

**Comment by DaniSancas** [comment]
+1

**Comment by SuprF1y** [comment]
+1

**Comment by shrgabor** [comment]
+1; thanks

**Comment by razorness** [comment]
+1

**Comment by devuo** [comment]
+1

**Comment by isakrubin** [comment]
+1

**Comment by Aerendir** [comment]
+1

**Comment by pculka** [comment]
+1

**Comment by anacona16** [comment]
+1

**Comment by fr3dm4n** [comment]
+1

**Comment by ikodev** [comment]
+1

**Comment by YetiCGN** [comment]
+1

**Comment by kingafrojoe** [comment]
+1

**Comment by 0x6368656174** [comment]
+1

**Comment by ArlingtonHouse** [comment]
+1

**Comment by King2500** [comment]
All the +1s don't help implementing this. It's a complex thing. And it's obvious people want this.

**Comment by thetrompf** [comment]
Don't take the +1 negatively, actually it just a gesture from who are
showing their interest in the issue. - It's a good thing, and if or when it
gets implemented a lot of people will be very happy.

**Comment by King2500** [comment]
I don't take it negatively, but it puts more pressure on @Haehnchen

**Comment by J7mbo** [comment]
The +1s here are the only way to show how many people want the feature. I see this on many github issues and on other feature request software that doesn't provide an alternative to saying "+1" to let the developer know they are also rooting for this. 

This allows the developer to prioritise new features by how popular the demand for them is. +1s are helpful in this regard.

I also don't think, given the popularity of developers saying "+1", that this is the most appropriate place to try and oppose that.

**Comment by thetrompf** [comment]
I totally agree

**Comment by ivodvb** [comment]
This would indeed be very nice!

**Comment by Jadro007** [comment]
+1

**Comment by W944** [comment]
One more +1 :)

**Comment by a-tawila** [comment]
yet another +1 :+1:  :)

**Comment by jeff1985** [comment]
+1

**Comment by dkop** [comment]
+1

**Comment by ATLSAPI** [comment]
+1

**Comment by bobvandevijver** [comment]
+1

**Comment by martijn80** [comment]
+1
(no pressure, just letting know i would be very happy as well)

**Comment by dangreenisrael** [comment]
+1

**Comment by dodysw** [comment]
+1

**Comment by mmarton** [comment]
+1

**Comment by cibermichel** [comment]
+1

**Comment by Aaronidas** [comment]
+1

**Comment by silentwarrior** [comment]
+1

**Comment by aminebenhariz** [comment]
+1

**Comment by Aphax** [comment]
+1

**Comment by wbienabe** [comment]
+1

**Comment by Abdeljabar** [comment]
+1

**Comment by diegotham** [comment]
+1

**Comment by tonynelson19** [comment]
+1

**Comment by fkubis** [comment]
+1

**Comment by mablae** [comment]
Everyone who want to write a :+1 on this issue from now on should prefer to send @Haehnchen an amazon giftcard or some other nice thing. This is just not helpful at all.

**Comment by velikanov** [comment]
@mablae this wouldn't be an open source at all)

**Comment by mablae** [comment]
@velikanov Or submit a PR for sure.

**Comment by max4kaps** [comment]
+1

**Comment by lengvarsky** [comment]
+1

**Comment by bobvandevijver** [comment]
Guys, instead of commenting only +1, Github now has the awesome functionality to add a thumbs up to the first post :+1: So do that, to keep the issue somewhat clean :smiley:

**Comment by velikanov** [comment]
So… the year has passed away…
I bet that in a year this functionality… still won't be implemented lol :)

**Comment by Szpadel** [comment]
@velikanov Yeah, definitely you should prepare some Pull Request.
Or maybe you think "For what I'm paying?", but wait... you payed nothing...
So instead of lamenting, check source code and start implementing what are you needing, or spend some $$$ for bounty to encourage someone to work on it.

**Comment by velikanov** [comment]
@Szpadel, why me?
Maybe you?
If I want some functionality - that doesn't mean that I'm able to implement it.
Why don't you give everyone here some $$$ to encourage everyone?

**Comment by ctaquu** [comment]
+1

**Comment by ilianiv** [comment]
+1

**Comment by someother1** [comment]
I wish that for Christmas (2016 ;D) :santa:
:+1:

**Comment by grigoryosifov** [comment]
+1

**Comment by kimpixel** [comment]
+1

**Comment by dchesunas** [comment]
+1

**Comment by hboomsma** [comment]
+1

**Comment by s-o-r-o-u-s-h** [comment]
+1

**Comment by zazoomauro** [comment]
+1

**Comment by schneidermayer** [comment]
+1

**Comment by alexemilberg** [comment]
+1

**Comment by CptDelta** [comment]
+1

**Comment by roj4s** [comment]
+1

**Comment by robertwe** [comment]
+1

**Comment by chancegarcia** [comment]
++

**Comment by Koc** [comment]
Guys, just using query builder, it autocompletes properly

**Comment by Karasuni** [comment]
+1

**Comment by willemnviljoen** [comment]
You can specifically ignore DQL by using a carefully crafted SQL injection in your PHPStorm. I have created Gist with the SQL injection here:

https://gist.github.com/willemnviljoen/d20ad8ad0cc365a7e80744328246610f

This works by matching the same expression as the built-in SQL injection, but excluding any queries which contain a : character. That should make it ignore most DQL queries. This won't get your autocomplete, but at least it will stop marking DQL as an error.

**Comment by jean-gui** [comment]
+1

**Comment by githoober** [comment]
+1

**Comment by hoshsadiq** [comment]
Guys, instead of commenting only +1, Github now has the awesome functionality to add a thumbs up to the first post 👍 So do that, to keep the issue somewhat clean 😃

@Haehnchen maybe you can lock this thread?

**Comment by stof** [comment]
@hoshsadiq AFAIK, locking a thread also prevents adding reactions

**Comment by Karasuni** [comment]
@hoshsadiq And the issue is still 'open', correct?

**Comment by pascalheidman-bedarf** [comment]
+1

**Comment by hoshsadiq** [comment]
@Haehnchen, is it worth closing this now that JetBrains has picked this up? I haven't touched PHP/Symfony for a while, so I'm not sure what the deal is.

**Comment by andrey-sokolov** [comment]
With the latest EAP we’ve provided a new version of DQL plugin with some new features: see https://blog.jetbrains.com/phpstorm/2018/11/phpstorm-2018-3-eap-183-4139-30/ . Give it a try and please share your feedback!
