### ISSUE TITLE
Autocomplete support for Symfony\Component\Translation\t

### ISSUE THREAD

**Issue by julien-lmnr** [Haehnchen/idea-php-symfony2-plugin#2301]
Hi,

I would like to request the addition of an autocomplete feature for the `Symfony\Component\Translation\t` function that simplifies the use of the translation system, especially for TranslatableMessage.

Currently, the autocomplete for translation keys works well with `new TranslatableMessage()`, but it seems that `t`, which is a shortcut alternative, is not supported by the plugin for the autocomplete of keys and translation domains.

Thank you for your excellent work on this very useful plugin.

**Comment by Haehnchen** [comment]
done via https://github.com/Haehnchen/idea-php-symfony2-plugin/pull/2306
