### ISSUE TITLE
Auto-injecting service in constructor is too high priority

### ISSUE THREAD

**Issue by jannes-io** [Haehnchen/idea-php-symfony2-plugin#2350]
When I have the following class:

```php
class Test
{
    public function __construct(private readonly EntityRepository $productRepository)
    {
    }

    public function test()
    {
    }
}
```
And I type some code in the test function like:
```
$this->produ
```

Instead of suggesting the already injected `$productRepository`, it is recommending me other services first and then the already injected service.
![image](https://github.com/Haehnchen/idea-php-symfony2-plugin/assets/9079379/cfce9e13-27f4-4954-a421-6b48bb4ac40d)

Expected behavior:
Always favor already injected services in code autocomplete over service suggestions.

**Comment by Haehnchen** [comment]
yeah, they are already highly downvoted. will try to fine tune it.

**Comment by happit-jannes** [comment]
@Haehnchen it's still way too aggressive on auto injecting.. Even suggesting functions inside of services before the one that's already injected.

Is there a way to just completely disable this feature? It's hindering me personally more than it helps. 99/100 I already know what services I'll need and have already injected them manually...

![image](https://github.com/user-attachments/assets/5df65f36-a84a-4173-bb4d-0827f4eac718)

**Comment by jannes-io** [comment]
@Haehnchen it's still way too aggressive on auto injecting.. Even suggesting functions inside of services before the one that's already injected.

Is there a way to just completely disable this feature? It's hindering me personally more than it helps. 99/100 I already know what services I'll need and have already injected them manually...

![image](https://github.com/user-attachments/assets/5df65f36-a84a-4173-bb4d-0827f4eac718)

**Comment by jannes-io** [comment]
Turns out it was this setting:

![image](https://github.com/user-attachments/assets/23e45e9b-9c3c-4dab-aaad-850fdbafc83a)

Why do they need to force this AI ML crap down our throats... I don't want AI in my IDE. JetBrains should keep its experimental beta shit out of my workflow...
