### ISSUE TITLE
Issue with Symfony Plugin Causing Analyzing Tool to Get Stuck in PhpStorm

### ISSUE THREAD

**Issue by aaguevarah** [Haehnchen/idea-php-symfony2-plugin#2380]
Hi,

I wanted to report an issue I've encountered with the Symfony plugin in PhpStorm. Starting today, for some reason, the "Analyzing" tool gets stuck when the plugin is activated. It just stays on "Analyzing...". I've attached an image to illustrate the problem. When I disable the plugin, everything works correctly. 

I would appreciate a fix for this bug, as this plugin is truly wonderful.

Thank you.
<img width="1407" alt="SCR-20240521-szry" src="https://github.com/Haehnchen/idea-php-symfony2-plugin/assets/54619699/292d3c05-e44e-46c5-bad4-5e16615b5d83">

**Comment by rubenrubiob** [comment]
I have the exact same issue, if it helps to know.

**Comment by aaguevarah** [comment]
It's fixed now, thanks for the great work.

**Comment by rubenrubiob** [comment]
I is indeed fixed. Thank you for your work!
