### ISSUE TITLE
"Missing class" error in YAML services definition when class name is defined as parameter

### ISSUE THREAD

**Issue by FlyingDR** [Haehnchen/idea-php-symfony2-plugin#242]
PHPStorm 7.1.2 on Windows 7 x64, Symfony2 plugin v0.10.44

When services for DiC are defined in YAML format and class names for services are defined as parameters - I get all parameters "Missed class" errors for every service definition. Example screenshot can be seen [here](http://c2n.me/6PeMKa.png) and source of this file is [here](https://github.com/FlyingDR/struct-bundle/blob/master/Resources/config/services.yml). 

Replacing parameter with actual class name resolves problem, hovering highlighted parameter with Ctrl or Ctrl+click works properly, screenshot can be seen [here](http://c2n.me/6PeVtI.png)

**Comment by peteruu** [comment]
and for example something like this
services:
    person:
        parent: globals
        class:  %parameter_defined_in_parameters.yml%Bundle\Repository\PersonRepository

it is posible some way?
