### ISSUE TITLE
Add support of the console helpers

### ISSUE THREAD

**Issue by Koc** [Haehnchen/idea-php-symfony2-plugin#243]
It would be nice add such autocompletes:
1. `$this->getHelperSet()->get(/*suggest*/)`
2. `$this->getHelperSet()->get('concrete helper')->/*suggest*/`

More information available in the doc http://symfony.com/doc/current/components/console/helpers/index.html

**Comment by CarsonF** [comment]
I would like this! I don't think they are going away just getting renamed. One was even added in 2.6 :)

**Comment by Haehnchen** [comment]
https://github.com/Haehnchen/idea-php-shopware-plugin/issues/30

**Comment by Haehnchen** [comment]
still functional in Symfony 7

![image](https://github.com/Haehnchen/idea-php-symfony2-plugin/assets/1011712/c408f0f9-5c31-4b98-a801-a6868651a5db)
