### ISSUE TITLE
Doctrine ORM and ODM conflict

### ISSUE THREAD

**Issue by luxemate** [Haehnchen/idea-php-symfony2-plugin#298]
Since I've installed Doctrine MongoDB ODM bundle, symfony2 plugin doesn't show what ORM repository is related to the entity, and highlights the custom repository methods as they were not found in the ObjectRepository, though it detects ODM repositories and finds custom methods. Could anyone confirm the same behavior?

```php
$this->getDoctrine()
    ->getRepository('AcmeDemoBundle:User')->getByWhatever();

$this->get('doctrine.odm.mongodb.document_manager')
    ->getRepository('AcmeDemoBundle:Article')->getByWhatever();
```

**Comment by Haehnchen** [comment]
fixed because of refactoring
