### ISSUE TITLE
[Form] Add support for collection type's option 'type'

### ISSUE THREAD

**Issue by hoshsadiq** [Haehnchen/idea-php-symfony2-plugin#323]
``` php
$builder->add(
    'children',
    'collection',
    array(
        'type' => 'child'
    )
)
```

Here child is a 'type' cannot be auto completed (should be like argument two of method `$builder->add()`).

**Comment by stof** [comment]
It would be great if the ``options`` option could be supported too for the collection (it configures options for the item type)
