### ISSUE TITLE
Class name autocompletion in the middle of the value in xml services

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-symfony2-plugin#337]
When I'm tryign to change the class name of a service defined in XML, the only way to get autocompletion is to put the cursor at the beginning of the ``class`` attribute. and then, the autocompletion leaves the existing content after the autocompleted one, whcih makes it broken.
This is totally inconsistent with the way the PhpStorm completion works.

If I put the cursor in the middle of the existing value, I would expect to have the autocompletion being triggered based on the text on the left of the cursor, and having the text on the right be replaced when hitting ``Tab`` to apply the completion

**Comment by Haehnchen** [comment]
did some improvements by time here
