### ISSUE TITLE
[Doctrine] Add support of arbitrary joins in QueryBuilder autocompletion

### ISSUE THREAD

**Issue by Koc** [Haehnchen/idea-php-symfony2-plugin#339]
``` php
$qb->join('...') // there is possibility join arbitrary entity here
```

See http://doctrine-orm.readthedocs.org/en/latest/reference/dql-doctrine-query-language.html?highlight=arbitrary%20join for more details.

**Comment by stof** [comment]
@Haehnchen do you have any idea when this will be supported ?

**Comment by Haehnchen** [comment]
@stof doctrine querybuilder refactoring and tests are next on my roadmap to support this and some more use cases

**Comment by stof** [comment]
Great. I find this issue annoying each time I work on a query involving arbitrary joins (and I have a bunch of such queries in my project as almost none of my relations are bidirectional)
