### ISSUE TITLE
The plugin changes the project file in an unexpected way

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-symfony2-plugin#348]
In projects using the Symfony2 plugin, I get a message from time to time telling me that the project file has been changed externally, asking me to reload the project. this is quite annoying when working on something (it looses the search results for instance).
this never happens on projects where I don't use the plugin, so I suspect it is related to the plugin rather than to PhpStorm itself.

**Comment by Haehnchen** [comment]
never got this behavoir, close this for now

**Comment by stof** [comment]
FYI, I never got this behavior since I switched to Ubuntu in September. So I don't know whether it is Windows-specific or whether it has been fixed since then (I stopped using PhpStorm on Windows)
