### ISSUE TITLE
[Feature Request] Allow add symbol to editor.

### ISSUE THREAD

**Issue by liverbool** [Haehnchen/idea-php-symfony2-plugin#380]
For now we have use  `symbol`  pane to navigate to resource, is impossible to add `symbol` to editor at current cursor?

![screenshot oct 31 01 22 52](https://cloud.githubusercontent.com/assets/206804/4849945/7f5bc090-6065-11e4-9d3c-dab7f2568da7.png)

**Comment by Haehnchen** [comment]
old feature
