### ISSUE TITLE
[Feature Request] Make debug token links clickable in REST Client

### ISSUE THREAD

**Issue by ulilicht** [Haehnchen/idea-php-symfony2-plugin#381]
Hi, 

I am developing a REST Application with Symfony. I am testing it using the PHPStorm Built-in REST-Tool. In Response Headers, Symfony outputs the Debug Token Link.

--> It would be great if this link would be clickable and would open in the Browser! 

In the screenshot, you can see that the REST Tool outputs the link and the hostname. 
![Screenshot](https://cloud.githubusercontent.com/assets/456963/4973071/a2b4dc5e-68b5-11e4-8a6a-816942664ee6.png)

**Comment by Haehnchen** [comment]
rest client is no more :)
