### ISSUE TITLE
Plugin Update Error

### ISSUE THREAD

**Issue by ZCJ** [Haehnchen/idea-php-symfony2-plugin#394]
For some reason, this error is back when I try to update the plugin.
Any feedback why this happens? Anyone experiencing the same?

![screen shot 2014-12-05 at 1 01 41 am](https://cloud.githubusercontent.com/assets/1475845/5306075/d47aed78-7c1a-11e4-98fd-3c8a21ddbc8b.png)

![screen shot 2014-12-05 at 1 02 15 am](https://cloud.githubusercontent.com/assets/1475845/5306081/e47f8ce2-7c1a-11e4-819a-be1561f742e5.png)

**Comment by Haehnchen** [comment]
jetbrains infrastructure problem
