### ISSUE TITLE
mistake in $form->get('operator')

### ISSUE THREAD

**Issue by msajadi824** [Haehnchen/idea-php-symfony2-plugin#398]
![form_get](https://cloud.githubusercontent.com/assets/4056919/5344227/a2c7a2a2-7f22-11e4-8c6e-0fb0bea86b83.png)

mistake in $form->get(''). It must don't show list of services. It is a bug. It must show list of form field's or nothing.

My English is very bad.

**Comment by Haehnchen** [comment]
see also #398

**Comment by Koc** [comment]
@Haehnchen you linked the same ticket

**Comment by Haehnchen** [comment]
thx ;)
