### ISSUE TITLE
Not working @Template, and something else...

### ISSUE THREAD

**Issue by alisa-rend** [Haehnchen/idea-php-symfony2-plugin#410]
video

**Comment by alisa-rend** [comment]
@ORM\Column
http://a.pomf.se/rlnadg.mp4

**Comment by Haehnchen** [comment]
@alisa-rend did you install PHP Annotations: https://plugins.jetbrains.com/plugin/7320? annotations are not part of this plugin.

**Comment by alisa-rend** [comment]
:

**Comment by alisa-rend** [comment]
@Haehnchen :+1:
