### ISSUE TITLE
[Yml] Create function when no declaration can be found

### ISSUE THREAD

**Issue by Rvanlaak** [Haehnchen/idea-php-symfony2-plugin#415]
Great feature to goto the declaration of a call by using `CTRL+click` in my `services.yml`. This makes navigating a lot easier, because the yml file is located far away from the controllers.

In case a call / function does not have a declaration (yet), PhpStorm will show the message:

    Cannot find declaration to go to

It would be great to add a generator for this under the `ALT+enter` menu. Most of the time these are setters, so adding the protected variable and the getter/setter would be great!

```yml
acme.test_service:
    calls:
        - [ setLogger, [@logger] ]
``` 

This could generate:

```php
use Monolog\Logger;

/**
 * @var Logger
 */
protected $logger;

/**
 * @param Logger $logger
 * @return self
 */
 public function setLogger(Logger $logger)
{
    $this->logger = $logger;
    return $this;
}
```

**Comment by Haehnchen** [comment]
code generators (+update) are on my todo list, this is only one of them...

**Comment by Rvanlaak** [comment]
:+1: 

The `ALT+enter` lookup to the translation file when you cursor is on a translation string in a Twig file also seems broken.

**Comment by Haehnchen** [comment]
its in. will improve and also support xml in next release

**Comment by Rvanlaak** [comment]
:+1: 

The function is added at a weird position. Are they added sorted by name?

Planning to generate the new class variable as well? Maybe add an extra generator `Create setter + variable` ?

**Comment by Haehnchen** [comment]
@Rvanlaak yes its name sorted what would you a expect?
i will add more features here

**Comment by Rvanlaak** [comment]
Usually I put the getters/setters at the bottom of my class, but don't think there is a way to figure out how to archieve that.
