### ISSUE TITLE
[Twig] Auto-complete macro's imported from inside of another macro

### ISSUE THREAD

**Issue by chetzof** [Haehnchen/idea-php-symfony2-plugin#419]
```
{% macro foo() %}
{% endmacro %}

{% macro breadcrumb(parts) %}
    {% import _self as bar %}
    {{ bar. // NO COMPLETION }}
{% endmacro %}
```

**Comment by exactquery** [comment]
While the _self syntax now works, importing other other templates with macros  does not seem to provide autocomplete: 

`{% macro foo(parts) %}
    {% import 'AppBundle:Macros:barMacros.html.twig' as bar %}
    {{ bar. // NO COMPLETION }}
{% endmacro %}`

You can, however, import a single macro, and get autocomplete:

`{% macro foo(parts) %}
    {% from 'AppBundle:Macros:barMacros.html.twig' import bar %}
    {{ bar. // THIS WORKS }}
{% endmacro %}`

Using Symfony2, Symfony2 Plugin v0.11.95, PHPStorm 9.0 (141.1912)
