### ISSUE TITLE
Services not recognized in SF2 command

### ISSUE THREAD

**Issue by FredoVelcro** [Haehnchen/idea-php-symfony2-plugin#423]
The services are now always recognized (when CTRL + click and so autocompletion) in Symfony2 command for instance : 
```php
$geocoded = $this   ->getContainer()
                                ->get('bazinga_geocoder.geocoder')
                                ->using('google_maps')
                                ->geocode($address);
```
The getContainer() return a "ContainerInterface" but the "bazinga_geocoder.geocoder" not clickable...
(my container is well configured in the plugin container tab)

Is this a bug ?

**Comment by Haehnchen** [comment]
you need add `appDevDebugProjectContainer.xml` file localy or remotely. or just create a dummy xml service in your project to give plugin indexer an chance to know what is behind `bazinga_geocoder.geocoder` if this service is build dynamically by bundle.
