### ISSUE TITLE
[Security] Autocomplete roles

### ISSUE THREAD

**Issue by shane-l** [Haehnchen/idea-php-symfony2-plugin#431]
Hi,

It'd be nice to autocomplete role names inside calls to `is_granted`. This would be built-in roles (`IS_AUTHENTICATED_FULLY`, `IS_AUTHENTICATED_REMEMBERED`, etc) as well as any custom roles defined in `security.yml`.

**Comment by Haehnchen** [comment]
good idea. but not only for twig files.

some compiled sources
````
    <parameter key="security.role_hierarchy.roles" type="collection">
      <parameter key="ROLE_ADMIN" type="collection">
        <parameter>ROLE_USER</parameter>
        <parameter>ROLE_foo</parameter>
      </parameter>
      <parameter key="ROLE_PARENT" type="collection">
        <parameter>ROLE_ADMIN</parameter>
      </parameter>
    </parameter>
````


```xml
    <service id="security.access_map" class="Symfony\Component\Security\Http\AccessMap" public="false">
      <call method="add">
        <argument type="service">
          <service class="Symfony\Component\HttpFoundation\RequestMatcher" public="false">
            <argument>^/login$</argument>
          </service>
        </argument>
        <argument type="collection">
          <argument>IS_AUTHENTICATED_ANONYMOUSLY</argument>
        </argument>
        <argument>null</argument>
      </call>
```

**Comment by Koc** [comment]
It also relates #141. Imho much easier write custom symfony-command which generates JSON instead of writing parser on Java. Somewho of Symfony users can write this kind of command but only small part of Symfony users can code on Java.

**Comment by Haehnchen** [comment]
yes, its also came to my mind because custom twig completion possibilities already included in https://github.com/Haehnchen/idea-php-toolbox per json, but it needs some more improvements before a publish. moreover symfony2 plugin should provide completion on its own data, to make life easier for all "lazy developers" which wont configure several plugins.

**Comment by Koc** [comment]
IMHO it is not so hard install 3 plugins (annotations, php-toolbox, symfony2), one bundle and run 2-3 symfony commands. It can unweight you.

**Comment by King2500** [comment]
:+1:
