### ISSUE TITLE
[Twig] Add description to PhpTyes @var syntax

### ISSUE THREAD

**Issue by mekras** [Haehnchen/idea-php-symfony2-plugin#439]
There is a [great feature](http://symfony2-plugin.espend.de/languages/twig/index.html#phptypes) but it can be more useful with ability to describe variable like this:

```twig
{# @var foo \Foo\Bar description of this variable #}
```
Currently this is not supported. Without description:

![Without description](https://img-fotki.yandex.ru/get/15500/76786768.0/0_11ce1d_c5611a9_orig.png)

With description:

![With description](https://img-fotki.yandex.ru/get/6/76786768.0/0_11ce1e_305a545e_orig)

And will be very nice if the developer can write for template designer something like this:

```twig
{##
 # Some description of template, where and when it used
 #
 # @var foo \Some\Foo\Class description of variable "foo"
 # @var var \Some\Bar\Class description of variable "bar"
 #}
```

**Comment by Haehnchen** [comment]
thx, really good ideas.
whats about supporting some more doc tags which provides navigation like `@see`,  `@link`?

**Comment by mekras** [comment]
> whats about supporting some more doc tags which provides navigation like @see, @link?

It will be useful, I think. But no nessesery for me :-)

**Comment by King2500** [comment]
TwigDoc is born :)

**Comment by gharlan** [comment]
Imo the variable name and type should be swapped:

```twig
{# @var \Foo\Bar foo description of this variable #}
```

**Comment by Haehnchen** [comment]
done

**Comment by mekras** [comment]
Cool!
