### ISSUE TITLE
[Twig] Create translation in multiple files

### ISSUE THREAD

**Issue by rvanlaak** [Haehnchen/idea-php-symfony2-plugin#443]
Creating translations directly from Twig is really effective. Issues I'm facing:
- After one translation key is generated, `ALT+enter` does not show the generators for the other locales anymore
- It is not possible to select multiple generators in the `ALT+enter` menu. Other menus like `CTRL+e` do support selection of multiple elements, so this also might be possible over here.

**Comment by Haehnchen** [comment]
done

**Comment by rvanlaak** [comment]
🎉
