### ISSUE TITLE
[Twig] Autocomplete with array

### ISSUE THREAD

**Issue by dag-io** [Haehnchen/idea-php-symfony2-plugin#444]
Hello

I can not have the autocomplete on twig view working properly with arrays.

On the following screenshot, we can see "category" is not suggested

![screen shot 2015-02-12 at 15 26 28](https://cloud.githubusercontent.com/assets/74581/6169118/89bd8ea2-b2cb-11e4-9b7b-1a4febc7d1ef.png)

The project is here : https://github.com/dag-io/phpstorm-sf2-plugin-set-issue

**Comment by Haehnchen** [comment]
fixed in #208
