### ISSUE TITLE
Detect php-di services

### ISSUE THREAD

**Issue by Brammm** [Haehnchen/idea-php-symfony2-plugin#447]
We use [php-di](http://php-di.org/), which is compatible with the Symfony2 container. Services are loaded through their FQN (instead of an alias). E.g.:

    $barService = $container->get('Foo\Bar');
    // Or 
    $barService = $container->get(Bar::class);

However, the plugin doesn't pick this up and we are back to adding `/** @var **/` docblocks. Would it be possible for the plugin to recognize these services as well?

**Comment by Haehnchen** [comment]
@Brammm there was released a external plugin by @pulyaevskiy https://plugins.jetbrains.com/plugin/7694?pr=phpStorm. moreover https://plugins.jetbrains.com/plugin/7251 should provide same functionality. i am also working a on similar plugin, with extracted staff of the sy2 plugin.

**Comment by Brammm** [comment]
@Haehnchen haha, yep. @pulyaevskiy is a coworker who created that :p

**Comment by Haehnchen** [comment]
so closing this here
