### ISSUE TITLE
Add dependency for Php-Annotations Plugin

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#448]
To reduce duplicate code and implement more annotations features, remove `optional="true"` on `de.espend.idea.php.annotation`.

**Comment by Haehnchen** [comment]
done

**Comment by damianpeterson** [comment]
I've just updated and am getting:

> Problems found loading plugins: Plugin "Symfony Plugin" was not loaded: required plugin "de.espend.idea.php.annotation" not installed.

with options to disable plugin.

Is there anything further I can provide to help with debugging this?

**Comment by damianpeterson** [comment]
OK, I was able to fix this by disabling the Symfony Plugin, installing the PHP Annotations Plugin, restarting, re-enabling the Symfony Plugin and restarting again.

**Comment by Haehnchen** [comment]
yes, i had to do this because of code maintenance reducing
