### ISSUE TITLE
Goto template does not work anymore in strings outside render() calls

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-symfony2-plugin#450]
In older versions of the bundle, any string containing a Twig template name was clickable to go to the template. But this does not work anymore.

In my current project, I have lots of places impacted by that, because I have a bunch of protected methods returning a template name (and then, a child class overwrites these methods to provide a mobile version of the template while the business logic is the same).

```php
    protected function getThreadTemplate()
    {
        return 'WebBundle:Space\Discussion:thread.html.twig';
    }
```

It would be great to support "Goto template" again in this case. It was very handy.

**Comment by Haehnchen** [comment]
PhpStorm9 eap issue. possible issue with new "Language Injections"

**Comment by stof** [comment]
This is on PhpStorm 8.0.3, not on the PhpStorm 9 eap

**Comment by Haehnchen** [comment]
thx, yes api break definitely inside `8.0.3`, in `8.0.2` all is working fine.
