### ISSUE TITLE
the structure panel is broken for Twig templates using the short notation for blocks

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-symfony2-plugin#453]
I don't know whether the Twig integration with the Structure panel is provided by this bundle or the core one.
But it is broken when a block uses the short notation ``{% block foobar expression %}`` instead of the extended syntax ``{% block foobar %}{{ expression }}{% endblock %}``: it displays next blocks as children of this block.

**Comment by Haehnchen** [comment]
iam not doing all the magic :).
opened external: https://youtrack.jetbrains.com/issue/WI-26737

**Comment by dyadix** [comment]
The related ticket WI-26737 has been fixed.

**Comment by Haehnchen** [comment]
thx. `Note: requires build 141.546 or later.`
