### ISSUE TITLE
[Feature] Autocomplete argument and option names in commands

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-symfony2-plugin#454]
It would be great to autocomplete argument and option names in ``$input->getArgument('...')`` and ``$input->getOption('...')`` inside columns, by reading the command definition to know them.

**Comment by stof** [comment]
2 things to check for your implementation (I cannot tell whether it is supported just by reading the code):

- does ``setDefinition()`` properly reset arguments/options which might have been added earlier ?
- does it work with inheritance when the parent code configuring some options and arguments gets called ?

**Comment by Haehnchen** [comment]
- `setDefinition()` reset: its too complex code interpreting for this simple completion context
- good catch on `inheritance`, used in some symfoy2 core commands

**Comment by Haehnchen** [comment]
`parent` implemented
