### ISSUE TITLE
Controller detection when following Best Practices

### ISSUE THREAD

**Issue by gharlan** [Haehnchen/idea-php-symfony2-plugin#455]
When following the [Best Practices for template locations](http://symfony.com/doc/current/best_practices/templates.html#template-locations) the controller should be detected automatically by the twig path:

```
app/Resources/views/default/index.html.twig
AppBundle\DefaultController\indexAction
```

**Comment by Haehnchen** [comment]
There is an index process running in background that collects all `render*` calls with `html.twig` inside. that matches `AppBundle` `$this->render('default/index.html.twig');`
https://github.com/symfony/symfony-standard/blob/2.7/src/AppBundle/Controller/DefaultController.php

I will provide testing for this case, but its should working in index and compiled container context on `addPath`: https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/TwigBundle/DependencyInjection/TwigExtension.php#L91

**Comment by Haehnchen** [comment]
already supported
