### ISSUE TITLE
Wrong Twig autocompletion for templates in the same folder

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-symfony2-plugin#458]
When trying a template which is in the same folder than the current folder, one of the suggestion of the autocompleter is the filename itself.
But this is wrong. ``{% include %}`` (and all other parts using template names) are working with **template names**, not file names. And there is no concept of relative template name.

**Comment by Haehnchen** [comment]
still a "feature" of the orignal twig plugin.

**Comment by stof** [comment]
Oh, I thought the include autocompletion was coming from your plugin

**Comment by Haehnchen** [comment]
nothing i can do here
