### ISSUE TITLE
[Twig] Finally resolve missing block completion in PhpStorm9

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#460]
If we are inside `block` tag no completion event is fired. also "hacked" SMART char-type workaround is not working.

Open external issue again. Old one: https://youtrack.jetbrains.com/issue/WI-24362

```twig
{% block <carpet+completion>  %}
{% endblock %}
```

**Comment by Haehnchen** [comment]
external:
https://youtrack.jetbrains.com/issue/WI-27021

![phpstorm-symfony-block-twig](https://cloud.githubusercontent.com/assets/1011712/7048842/90de7bea-de15-11e4-9d80-0793b71b79c7.png)

**Comment by Sorien** [comment]
you said that they are calling result.stopHere() 

maybe its a bullshit but just a idea there should be possible something like
<completion.contributor language="Twig" implementationClass="" order="FIRST"/> // to go before all contributors
