### ISSUE TITLE
For loop variable autocompletion

### ISSUE THREAD

**Issue by gharlan** [Haehnchen/idea-php-symfony2-plugin#463]
-> #208

Shouldn't autocompletion for `user` work here?

![screenshot 2015-03-10 11 59 20](https://cloud.githubusercontent.com/assets/330436/6573648/585b5e00-c71d-11e4-8477-7fe9a13e540b.png)

The type of `user` is empty, but it should be `\AppBundle\Model\User`..
So I don't get autocompletion for `lastName` etc.

I'm using PhpStorm 9 EAP and sf2 plugin 0.11.86.

**Comment by xawiers** [comment]
+1 using PhpStorm 8.0.3 and 0.11.86 plugin version
It's really annoying - missing this functionality - earlier it worked without problems.
BTW type hint does not help also - tried this way - report autocompletion works, but article autocompletion - does not.

```
    {# report \AppBundle\Entity\Report #}
    <div class="row">
        <div class="col-md-12">
            {{ report.name }}
            {% for article in report.articles %}
                {# article \AppBundle\Entity\Article #}
                {{ article.headline }}
            {% endfor %}
        </div>
    </div>

**Comment by Haehnchen** [comment]
sry guys, but finally fixed and its more stable now. wait for next release :)

**Comment by Haehnchen** [comment]
pls give some feedback on new release, now

**Comment by gharlan** [comment]
It works now! Very nice :heart: Thanks for the fix!

**Comment by Protocteur** [comment]
It work for me too since the last update <3
