### ISSUE TITLE
Problems in recognize namespace

### ISSUE THREAD

**Issue by matiux** [Haehnchen/idea-php-symfony2-plugin#466]
I use phpstorm 9 (build 141.176) and symfony2 plugin 0.11.87
In my symfony project, I have for example this code:
```
<?php namespace Acme\RestApiBundle\Handler\Db\Doctrine;

use Acme\RestApiBundle\Exception\InvalidFormException,
    Acme\RestApiBundle\Form\ReservationType,
    Acme\RestApiBundle\Model\ReservationInterface;
```
or

```
  <?php namespace Acme\RestApiBundle\Model;

use Acme\RestApiBundle\Entity\User,
    Acme\RestApiBundle\Entity\Area,
    Acme\RestApiBundle\Entity\Customer;
```
The problem is that Phpstorm marks Model in first example, or Entity in second Example in red (and sometimes Form or other directories) , so I can't go to the definition... But obviously, Model directory exists.
Is a known problem? Is there a fix?

Thanks

**Comment by Haehnchen** [comment]
i dont know what you mean here, its phpstorm core. there is no plugin feature around this context.

**Comment by Haehnchen** [comment]
pls report to jetbrains. sometimes i can also reproduce this. just retype after last "\".
