### ISSUE TITLE
Separate Twig from plugin?

### ISSUE THREAD

**Issue by Rvanlaak** [Haehnchen/idea-php-symfony2-plugin#467]
Great new Twig features in the latest build :+1: Seems like the Twig features itself could be a separate plugin. We'd like to start using https://github.com/jarednova/timber in our Wordpress website, so a plugin solely for the Twig integration would be great! Did you already put some thoughts in this?

**Comment by Haehnchen** [comment]
also requested in #363. its just about time issue

**Comment by Rvanlaak** [comment]
Agreed. What do you mean with the Twig core being closed source?

**Comment by Haehnchen** [comment]
the main "Twig Plugin" of PhpStorm, which all the plugin features rely on.
