### ISSUE TITLE
[Container] Service updater Intention 

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#470]
Provide an service and phpclass Intention which updates:

 - [x] service arguments if not matching with constructor count
 - [x] generate tags on interfaces
 - [x] dialog, if multiple service are available for an argument
 - [ x] -in phpclass context: update service arguments- redundant
 - [x] yaml integration

**Comment by Haehnchen** [comment]
think of #449

**Comment by Haehnchen** [comment]
![foo](https://cloud.githubusercontent.com/assets/1011712/7316896/62904c10-ea7b-11e4-92cf-42ea4390aa31.png)

**Comment by magnetik** [comment]
Is the YAML service support supposed to be in 0.11.94 ? The plugins seems to ignore my `app/config/service.yml` file (works fine with xml)
