### ISSUE TITLE
[Twig] Provide completion for endblock tag

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#474]
> According to: http://twig.sensiolabs.org/doc/tags/extends.html it's possible to define block name in tag > endblock. Now there is no completion for this situation.
> 
> This techniques is used in Symfony2 in some templates.

https://youtrack.jetbrains.com/issue/WI-19615

#460

**Comment by Haehnchen** [comment]
not our magic

**Comment by givihuda** [comment]
@Haehnchen It appears Symfony or PHPStorm devs are saying it's not their magic either... so who's magic are you saying that it is?
