### ISSUE TITLE
[Installer] Add Symfony Installer as new project type

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#475]
As requested by JetBrains the new symfony installer should be integrated into PhpStorm. We can implement it nicely inside "Create New Project" with selections for: "Empty Symfony Project" and "Symfony Demo Application". moreover include a parameter for a version string. target of implementation should be inside "Symfony2 Plugin".

> We've heard some news on Symfony Installer being now default way to install Symfony2 and create new projects, and it seems logical to include option to create Symfony2 projects to our "Create New Project" workflow (currently you can choose between empty project, Composer project, Bootstrap, etc).
> There is an issue in our issue tracker and Elena (in CC) can implement it, but it looks that the ideal place for this code would be in the idea-php-symfony2-plugin.

Also external issue: https://youtrack.jetbrains.com/issue/WI-27032

**Comment by King2500** [comment]
Does this automatically "enable" the Symfony2 Plugin in the plugin settings?

![image](https://cloud.githubusercontent.com/assets/4896363/8188315/56138778-1455-11e5-9c43-017dfd533afe.png)

**Comment by Haehnchen** [comment]
of course! :sunglasses:

**Comment by King2500** [comment]
:+1:

**Comment by Pierstoval** [comment]
Absolutely awesome :+1:
