### ISSUE TITLE
Twig "trans" filter with "trans_default_domain" does not work correctly

### ISSUE THREAD

**Issue by kherge** [Haehnchen/idea-php-symfony2-plugin#476]
First off, this plugin is a godsend so thanks for all the work put into this!

Unfortunately, it appears that the plugin does not change the domain for the `trans` filter if I use `trans_default_domain` in my Twig template.

```twig
{% trans_default_domain "hello_world" -%}

<html>
  <head>
    <title>{{ 'page.title'|trans }}</title>
  </head>
  <body>
    <p>{{ 'page.content'|trans }}</p>
  </body>
</html>
```

The actual code works fine when I run it, but PhpStorm reports that the translations are missing. It may also be important to note that I may use the `-` character to trim whitespace on either side of `trans_default_domain`.

**Comment by Haehnchen** [comment]
`-%}` :)
there is a regular expression not allowing this. but now i am having a reason to optimize this :)

**Comment by kherge** [comment]
I checked to see if it would make a different whether I used `-%}` or not. It doesn't appear to affect anything, and the messages are still reported as missing.

**Comment by kherge** [comment]
Woops! It looks like if a dash is in the name of the domain, it does not work.

So, this works:

```twig
{% trans_default_domain "mydomain" %}
``

But not this:

```twig
{% trans_default_domain "my-domain" %}
```

So it looks like a dash anywhere breaks it.

**Comment by Haehnchen** [comment]
fixed
