### ISSUE TITLE
[Console] getOption completion not working

### ISSUE THREAD

**Issue by King2500** [Haehnchen/idea-php-symfony2-plugin#477]
The new `getOption` completion/reference doesn't work for me.
`getArgument` works though.

![image](https://cloud.githubusercontent.com/assets/4896363/7124716/8b9e25f8-e22b-11e4-8f7e-156e2fb6555b.png)

Sample code taken from Symfony Console Component documentation:
http://symfony.com/doc/current/components/console/introduction.html

**Comment by Haehnchen** [comment]
thx fixed
