### ISSUE TITLE
Provide autocompletion for DIC parameters defined dynamically

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-symfony2-plugin#478]
Currently, parameters defined dynamically in DI extensions (or in the kernel) are not recognized by the autocompletion when there is no compiled container (which is always the case when working on a bundle rather than a fullstack project). It would be great to look at calls to ``ContainerBuilder::setParameter()`` to detect additional parameters

**Comment by Haehnchen** [comment]
we should also index tags, service defs, and other stuff. see #216. because of not having fully type analysis in index process there is a need for whitelisted typehints like `\Symfony\Component\DependencyInjection\ContainerBuilder`.

**Comment by Haehnchen** [comment]
done
