### ISSUE TITLE
[Translation] in XLIFF format in app/Resources/translations

### ISSUE THREAD

**Issue by Nyholm** [Haehnchen/idea-php-symfony2-plugin#479]
According to the [best practices](http://symfony.com/doc/current/best_practices/i18n.html#translation-source-file-location) you should store your translations in XLIFF format in the app/Resources/translations folder. 

Please correct me if I'm wrong but I can't get it to work properly: 
- Autocomplete - Works fine
- ctrl + click on a translation does not show the source of the translation
- I can't extract translations to app/Resources/translations

**Comment by Haehnchen** [comment]
its because of `XLIFF` is a not supported language type by phpstorm. will open external issue

**Comment by Nyholm** [comment]
Thank you @Haehnchen. I did not know that. Please link to that external issue once it is open.

**Comment by marapper** [comment]
https://youtrack.jetbrains.com/issue/WI-9220

*.xlf and *.xliff registered as pattern for XML but it doesn't work properly:

1. If domain1 contains *.xlf files and domain2 contains *.xliff files and domain3 contains *.yml files
- suggest works only for *.yml
-  ctrl+click doesnt jump to *.xliff files for neither translation text either domain
- "Extract translation" suggest full list domains in "Domain (Yaml)" and oly *.yml files in a current domain file list

**Comment by marapper** [comment]
5. "Create translation key" hint shows up only for *.yml
6. trans_default_domain doesn't work for *.xliff

**Comment by Rvanlaak** [comment]
:+1: for xliff support, it seems the Jetbrains issue is closed, so I've opened a new one with more info: https://youtrack.jetbrains.com/issue/WI-27964#

**Comment by Rvanlaak** [comment]
There is quite some activity on the Jetbrains issue page over the last few days :+1:

**Comment by marapper** [comment]
:+1:

**Comment by stof** [comment]
@Haehnchen any plan to make this work at least when xliff files are registered as being XML files in PhpStorm ?

**Comment by Haehnchen** [comment]
yes, xml is all i need. i am thinking of a mini plugin if jetbrains dont getting it :)

**Comment by neuro159** [comment]
xliff to XML by default for all users, this should be done by (mini?) plugin.

**Comment by stof** [comment]
@Haehnchen please start by supporting Xliff files in this bundle when they are already registered as an XML pattern (I did it in my PhpStorm already).
Then, you could create a plugin registering it automatically, but this may not be worth it: doing it manually is easier than installing a plugin (it requires at most 4 clicks to do it, and no restart...)

**Comment by Nyholm** [comment]
Thank you @neuro159 for replying to this issue. 

@Haehnchen Is it anything I can do to help?

**Comment by rvanlaak** [comment]
Saw https://github.com/Haehnchen/idea-php-symfony2-plugin/commit/84fb5dbf526f80961726edd5fcf386c674c9e511, would it also be possible to add a generator for translations in XLIFF now?

**Comment by piegus** [comment]
+1

**Comment by rvanlaak** [comment]
@Nyholm I've been postponing our move from `.yml` translations to `.xlf` translations because of the partial IDE support. Basically we'd love to start using Weblate for Git-integrated continuous translation based on `.xlf`, but if that would compromise the developer experience we will postpone it again.

So, you got the autocomplete, CTRL+click, extractor and generator in Twig working as how it works with `.yml`?

**Comment by Haehnchen** [comment]
finally its supported now, but you need to register all XLIFF extension as xml files. I am also thinking of adding a notification like its done by the Drupal plugin which announcing eg `.module` files

**Comment by Haehnchen** [comment]
closing XLIFF extension issue; documented in optional installation requirements
