### ISSUE TITLE
Field name autocomplete in $builder->add() should not translate $camelCase variables to 'under_score' field names

### ISSUE THREAD

**Issue by tamcy** [Haehnchen/idea-php-symfony2-plugin#480]
When entering the first parameter in a form type's `$builder->add()` method, the plugin provides great autocomplete capability by extracting the class fields defined in 'data_class'. However, it uses underscore names even when class variables/properties are written in camelCase. So variable `$fooBar` will be translated to field name `foo_bar`.

The field will display and work properly, with one glitch - validation. In this setting, when there is an error, the form will not be able to map the erroneous property `$fooBar` back to the field instance `foo_bar` to display the error message inline (unless with the `property_path` option). This causes field errors not displayed next to or below the corresponding fields, but as a form global error.

I suggest to remove this translation and populate the variables as-is in auto-complete.

Reference: https://github.com/symfony/symfony/issues/9162

**Comment by mtnorthrop** [comment]
I've also run into this bug.

I realize there might be people who appreciate this translation behavior, so maybe it would work to add the ability to configure whether or not the user wants camel case property names to be converted into snake case when autocompleting form builder methods. 

Does a setting like this already exist?

**Comment by Haehnchen** [comment]
moved to the behaviour of the Symfony PropertyAccess component, as no one provided a negative feedback camelCase looks more nature to me.
