### ISSUE TITLE
Option class argument in service treated as missing with a warning.

### ISSUE THREAD

**Issue by kherge** [Haehnchen/idea-php-symfony2-plugin#485]
The last argument in one of my classes has a default value.

```php
class MyService
{
    public function __construct(Interface1 $arg1, Interface2 $arg2, $arg3 = 123)
    {
    }
}
```

However, when I add it as service in the XML configuration file and only pass the first two parameters, I get a warning that the third argument is missing.

This should not be a warning.

**Comment by Koc** [comment]
Have the same error. Thank your for fix, will wait for the new version release.
