### ISSUE TITLE
Twig Include with interpolated string: "Missing template"

### ISSUE THREAD

**Issue by FPar** [Haehnchen/idea-php-symfony2-plugin#488]
If you include a template by an interpolated string, like
```twig
{% include "article/segments/#{segment.typeKey}.html.twig" with {'segment': segment} %}
```
the warning "Missing template" appears.

I would either not check, if the template exists for a string with an interpolated value or check, if the path exists till the first appeareance of a variable.

**Comment by King2500** [comment]
:+1:

**Comment by King2500** [comment]
Same applies with concatenated path string:
```twig
{% include "article/segments/"~segment.typeKey~".html.twig" with {'content': segment.content} %}
```
