### ISSUE TITLE
The autocompletion for form type options should look at parent classes too (in case the parent method is called)

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-symfony2-plugin#490]
This is necessary for the ``entity`` type for instance, given that options are actually configured in the parent abstract class DoctrineType sharing logic between the different Doctrine projects.

**Comment by Haehnchen** [comment]
`EntityType` does not overwrite `configureOptions`, so in this case phpstorm api provides most parent method which is the one from `DoctrineType`. moreover there is a "parent::*" parser currently. this issue will resolve with  #491, because of renamed `setDefaultOptions`
