### ISSUE TITLE
Symfony 2 Profiler not working

### ISSUE THREAD

**Issue by nihilnovi** [Haehnchen/idea-php-symfony2-plugin#494]
The Symfony 2 Profiler in the status bar does not seem to be working.

![image](https://cloud.githubusercontent.com/assets/1016639/7408444/0c3fb296-ef1d-11e4-9c59-0c90b8b9a9b0.png)

![image](https://cloud.githubusercontent.com/assets/1016639/7408416/db3d1c4c-ef1c-11e4-8945-883b2737f9ff.png)

The project settings are correct, everything else is working as expected.
The Profiler status bar does not register anything, regardless if its a normal request or a done via Run / Debug.

**Comment by nihilnovi** [comment]
Phpstorm version 8.0.3
Plugin version 0.11.89
Symfony version 2.6.6
Not in EAP channel

**Comment by nihilnovi** [comment]
Found this to be related to a faulty configuration being changed on reindex, don't know exactly how or why, but the container xml file was set incorrectly after reindex.

**Comment by DocLommi** [comment]
So how did you solve this ?!
