### ISSUE TITLE
[Twig] Add route auto completion for form action attribute

### ISSUE THREAD

**Issue by King2500** [Haehnchen/idea-php-symfony2-plugin#497]
Would be useful if you could add autocompletion for routes in `action` attribute, similar to what you provide for the `href` attribute of `a` tag:

```html
<form action="{CARET}" ...
```

**Comment by Haehnchen** [comment]
suggest to use form `action` var :)

**Comment by King2500** [comment]
If I don't use Form component?

**Comment by Haehnchen** [comment]
then u have autocomplete now :)

**Comment by King2500** [comment]
Thank you. You're awesome! Keep up the good work! :+1:
