### ISSUE TITLE
Resolve AcmeClass::CLASS constants

### ISSUE THREAD

**Issue by artursvonda** [Haehnchen/idea-php-symfony2-plugin#500]
It would be great if plugin could resolve ::CLASS constant and provide autocomplete for form fields (and other places where this might apply).

**Comment by Jean85** [comment]
I requested the same thing in #523

**Comment by Haehnchen** [comment]
@artursvonda form done. please report direct use cases where i missed them

**Comment by artursvonda** [comment]
Thanks.
