### ISSUE TITLE
Form options defined as required should be supported too

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-symfony2-plugin#502]
Currently, the option completion seems to support only options defined with a default value.

It would be great to support required and optional options:

```php
$resolver->setRequired(array('first_required', 'other_required'));

$resolver->setOptional(array('optional_setting'));
// OptionsResolver::setOptional is deprecated in Symfony 2.7. It is replaced by isDefined
$resolver->setDefined(array('optional_setting'));
```

all these methods accept both a string or an array of strings as argument

**Comment by Haehnchen** [comment]
navigation missing for now, but completion is working
