### ISSUE TITLE
Remove ServiceArgumentSelection.class from plugin jar

### ISSUE THREAD

**Issue by MaXal** [Haehnchen/idea-php-symfony2-plugin#512]
Please remove:
```fr.adrienbrault.idea.symfony2plugin.action.ui.ServiceArgumentSelection``` class from jar.

It looks like this class was renamed to ```ServiceArgumentSelectionDialog``` but the old class still exists in the final jar.

As a result our plugin checkers alarms about missing internal classes like:
```
ServiceArgumentSelection$IconColumn
ServiceArgumentSelection$Foo
ServiceArgumentSelection$NamespaceColumn
ServiceArgumentSelection$ServiceColumn
```

**Comment by Haehnchen** [comment]
@MaXal removed in 0.11.93

**Comment by MaXal** [comment]
@Haehnchen I still see the ServiceArgumentSelection.class in symfony2-plugin.jar 0.11.93.

**Comment by Haehnchen** [comment]
@MaXal sry, this time its gone. pls some feedback :)

**Comment by MaXal** [comment]
@Haehnchen Yep, everything is fine now. Thank you a lot!
