### ISSUE TITLE
Add Jms\DiExtraBundle support (for service autocomplete)

### ISSUE THREAD

**Issue by rrajkomar** [Haehnchen/idea-php-symfony2-plugin#514]
Hello,

When using your plugin and the di-extra-bundle, if you define a Service with the Service annotation for the bundle, the service id does not appear in the autocomplete popup. when using container->get().

Adding support for this would be great.

**Comment by Haehnchen** [comment]
bundle scope, we had the discussion not to implement this #116. so tagged as external for now.

**Comment by rrajkomar** [comment]
Hello,

I'm sorry but #116 doesn't quite cover what I was talking about : it mentions the @DI\LookupMethod annotation ( getting a existing service through a method) while I was actually talking about the @DI\Service annotation which allows you to create a entirely new service.

Said service is indeed not recognized as a service by the plugin and therefore does not appear in any autocomplete list.

**Comment by gharlan** [comment]
:+1: for Jms\DiExtraBundle support

**Comment by hoshsadiq** [comment]
If you warm up your cache, it will show up.

**Comment by Haehnchen** [comment]
sry, no implementation for external bundles here
