### ISSUE TITLE
Profiler problem

### ISSUE THREAD

**Issue by tiois** [Haehnchen/idea-php-symfony2-plugin#522]
When using the Symfony2 tab/menu to get the Profiler information, if I click on a profiler link (for instance "(200) /appdev.php/", it opens my browser but in PROD environment, and the Profiler is not enabled in PROD, only in DEV.

Is this a bug, a configuration problem?

My front controller is not "appdev.php" but "app_dev.php", don't know why it displays as "appdev.php" in the Symfony2 menu.

![screen shot 2015-06-16 at 8 40 03 pm](https://cloud.githubusercontent.com/assets/878737/8197586/ee101d0e-1467-11e5-9c20-42dbf3c98f19.png)

![screen shot 2015-06-16 at 8 40 13 pm](https://cloud.githubusercontent.com/assets/878737/8197588/f105a9c0-1467-11e5-8c0b-e69d2dab2f77.png)

**Comment by scottgutman** [comment]
I am having the same issue

![2015-10-03_18-58-29_symfony 2 profiler links button](https://cloud.githubusercontent.com/assets/8239129/10268297/31bd49f8-6a82-11e5-8625-5967d6eacde3.png)
![2015-10-03_18-59-32_bad-link](https://cloud.githubusercontent.com/assets/8239129/10268299/31c0afee-6a82-11e5-98e0-88aa293bf870.png)
![2015-10-03_19-00-22_good-link](https://cloud.githubusercontent.com/assets/8239129/10268298/31bfbdb4-6a82-11e5-9deb-5a783df25b42.png)

**Comment by Haehnchen** [comment]
done by profiler refactoring
