### ISSUE TITLE
"choose destination directory" dialog

### ISSUE THREAD

**Issue by fnagel** [Haehnchen/idea-php-symfony2-plugin#525]
I got a new dialog every time a use multiple folders and use "upload to XYZ" in context menu. 

![screenshot-05](https://cloud.githubusercontent.com/assets/116824/8226791/340c6cd2-15a2-11e5-871f-ffc245a84fdf.png)

Screencast by @krike: http://screencast-o-matic.com/watch/cojiFef42m

How to reproduce this: You will need a existing server in your project "build, execution, deployment -> Deployment". Then focus multiple folders in your project (using shift key) and right click. Some time ago this would have open the context menu but now the described dialog ("choose destination directory") will open. Clicking cancel seems not to have any effect (needs multiple clicks) and ends up in a open context menu which will only close if focus is changed to another window (so, away from the IDE)

When disabling the Symfony plugin the problem is no longer occurring. I've tried updating and cache clearing PHPStorm.

Any idea how to get rid of this dialog?

**Summery of reports:**
Win 8.1 Pro / PHPStorm 8.0.3
OSX Yosemite / -
OSX Yosemite / PHPStorm 8.0.3
Ubuntu / -
Win 8.1 Pro / PHPStorm 9.0 / Plugin 0.11.93
Ubuntu 14.04 / IDEA 14.1.4
OSX Yosemite  / -
Windows 7 / PHPStorm 9

**Comment by damionbroadaway** [comment]
Myself and everybody on my team that uses this have the same issue. We are all on OSX Yosemite.

**Comment by tomtomau** [comment]
Having this same issue on Yosemite on 8.0.3, selecting multi directories and right clicking on them will trigger this. Same effect on having to hit cancel a dozen or so times before it goes away.

**Comment by ggirtsou** [comment]
I'm experiencing the same issue - just @tomtomau

**Comment by fnagel** [comment]
Same issue with PHPStorm 9.0 and Plugin version 0.11.93

**Comment by message** [comment]
+1 Ubuntu 14.04 / IDEA 14.1.4

**Comment by krike** [comment]
i have this problem as well on OSX Yosemite. So does a colleague on Windows 7 with phpstorm 9. Looks like a global problem.

http://screencast-o-matic.com/watch/cojiFef42m

**Comment by moldcraft** [comment]
https://youtrack.jetbrains.com/issue/WI-28441

**Comment by fnagel** [comment]
Sorry, I should have mentioned that I already talked to jetbrains support -- with identical results.

**Comment by fnagel** [comment]
Still an issue in PHPStorm 9.0.2 and Symfony Plugin 0.11.97.
