### ISSUE TITLE
The service generator generates YAML with tabs

### ISSUE THREAD

**Issue by Azenet** [Haehnchen/idea-php-symfony2-plugin#533]
When generating a service, generating a definition for a service in YAML generates a YAML snippet that contains tabs, if you copy it to the clipboard and then paste it.

**Comment by Haehnchen** [comment]
duplicate by #374 will fixed with #362

**Comment by Jean85** [comment]
Up, the problem is still here :( and I don't see it mentioned in #362
Also, #347 is kinda unrelated, XML has different indentation rules and doesn't break because of indentation.

**Comment by Haehnchen** [comment]
done
