### ISSUE TITLE
"kernel" service is linked to propel skeleton class

### ISSUE THREAD

**Issue by gharlan** [Haehnchen/idea-php-symfony2-plugin#539]
I use sf2 with Propel 2.

The "kernel" service is linked to the form skeleton class of PropelBundle: https://github.com/propelorm/PropelBundle/blob/2.0/Resources/skeleton/FormType.php

So, autocompletion for kernel methods does not work.

![screenshot 2015-07-03 10 34 20](https://cloud.githubusercontent.com/assets/330436/8495626/412f5b08-216f-11e5-9d78-681948732331.png)

**Comment by Haehnchen** [comment]
crazy shit :). if still occurs the only way to resolve this is to ignore the skeleton folder in PhpStorm
