### ISSUE TITLE
Debug URL links lead to app.php, not app_dev.php

### ISSUE THREAD

**Issue by etomilin** [Haehnchen/idea-php-symfony2-plugin#540]
The links that appear in Debug-Url section of Symfony2 Profiler status bar (http://take.ms/NnkKG) are missing app_dev.php part thus leading to prod-environment where profiler is disabled.
For example, where link should lead to: localhost/app_dev.php/_profiler/355651, it is actually leading to localhost/_profiler/355651.

**Comment by murilolobato** [comment]
I'm also facing a similar problem. My project don't runs under localhost, it runs under localhost/myproject

So I always receives an 404 when I click on a debug-url

**Comment by scottgutman** [comment]
I have the same problem

![2015-10-03_18-58-29_symfony 2 profiler links button](https://cloud.githubusercontent.com/assets/8239129/10268271/31a98d1a-6a81-11e5-9303-844f164f6345.png)
![2015-10-03_18-59-32_bad-link](https://cloud.githubusercontent.com/assets/8239129/10268270/31a8e054-6a81-11e5-9367-d900359701f1.png)
![2015-10-03_19-00-22_good-link](https://cloud.githubusercontent.com/assets/8239129/10268272/31ab0884-6a81-11e5-86b5-7c2073c52bae.png)

**Comment by Toelath** [comment]
+1, thx

**Comment by Haehnchen** [comment]
fixed by profiler refactoring
