### ISSUE TITLE
[Doctrine] Plugin does not resolve Doctrine repository by explicit classname (5.5 syntax)

### ISSUE THREAD

**Issue by scaytrase** [Haehnchen/idea-php-symfony2-plugin#541]
Given a code snippet

```php
   use Some\Name\SpaceBundle\User;

   $this->getDoctrine()->getManager()->getRepository(User::class)->someCustomMethod();
```

marks `someCustomMethod` as not existing. 

Using `SpaceBundle:User` syntax works well.

**Comment by Haehnchen** [comment]
which phpstorm version?

**Comment by scaytrase** [comment]
That was on most 9x EAPs and 9.0. Not sure about 8.x as I mostly use 9.x last time

**Comment by scaytrase** [comment]
Also it is not recognizing `EntityName::class` when using it with Form `data_class` option. Replacing it with FQCN make the entity mapping helper working in `buildForm` `$builder->add` method. Switching back to `EntityName::class` disables autocompletion

**Comment by Jean85** [comment]
The form issue was already in #523
Its just been resolved! Maybe the fix is somehow reusable for this problem too?

**Comment by Haehnchen** [comment]
also started here, but its still working. need to validate it against several api's, need testing "assert" first. btw you missed `find(1)` in your example.

```php
$this->getDoctrine()->getRepository(Bike::class)->find(1)->getBikes()
```

**Comment by Haehnchen** [comment]
https://github.com/Haehnchen/phpstorm-phpdi/commit/eb9e16a7ba596607daa5e30d4142826860ca5fcd

**Comment by Haehnchen** [comment]
a wtf issue, but fixed ;)
