### ISSUE TITLE
"Cannot find declaration to go to" in PhpStorm 9

### ISSUE THREAD

**Issue by metaer** [Haehnchen/idea-php-symfony2-plugin#551]
When I update PhpStorm to PhpStorm 9 and install Symfony 2 plugin, I can not use "Ctrl + B" to go to js and css files in twig asset function:
<script src="{{ asset('bundles/projectmain/js/base.js') }}"></script>
Error: "Cannot find declaration to go to"

All checkboxes in Symfony 2 plugin settings are enabled.
In PhpStorm 8 it is ok, but in PhpStorm 9 it does not work.

**Comment by rvanhuizen** [comment]
I can confirm. I have the same issue.

**Comment by BlueTM** [comment]
I have the same issue.
