### ISSUE TITLE
Any benefit to Timber users?

### ISSUE THREAD

**Issue by christianmagill** [Haehnchen/idea-php-symfony2-plugin#554]
I primarily do WordPress development and have recently been looking at Timber (http://upstatement.com/timber/) which implements Twig into WordPress.

I am wondering if there would be any benefit to installing the symfony2-plugin or is it dependent on a standard symfony2 project.

Much thanks,

**Comment by Haehnchen** [comment]
you can just install it. there many features in twig that also work without a full-stack symfony
