### ISSUE TITLE
[Doctrine] simple_array and json_array

### ISSUE THREAD

**Issue by Soullivaneuh** [Haehnchen/idea-php-symfony2-plugin#555]
For this kind of code:

```php
/**
 * @var string[]
 *
 * @ORM\Column(name="$emails", type="simple_array", nullable=true)
 */
private $emails = null;
```

The `type` autocomplete provide only `array`. [`simple_array`](http://doctrine-dbal.readthedocs.org/en/latest/reference/types.html#simple-array) and [`json_array`](http://doctrine-dbal.readthedocs.org/en/latest/reference/types.html#json-array) are missing.

Thanks.

**Comment by Haehnchen** [comment]
`\Doctrine\DBAL\Types\JsonArrayType::getName` implements `\Doctrine\DBAL\Types\Type` so i can remove the static internal list. having parser for this know.

Implementation needs to but done in Annotation Plugin.

**Comment by Soullivaneuh** [comment]
> Implementation needs to but done in Annotation Plugin.

It's another external plugin? Do you have the github page of it?

**Comment by King2500** [comment]
https://github.com/Haehnchen/idea-php-annotation-plugin
