### ISSUE TITLE
[Idea] Class auto-completion on SecurityVoter

### ISSUE THREAD

**Issue by Soullivaneuh** [Haehnchen/idea-php-symfony2-plugin#556]
For example, with this kind of `SecurityVoter` implement:

``` php
class CloudFlareZoneVoter extends AbstractVoter
{
    const DELETE    = 'delete';

    /**
     * {@inheritdoc}
     */
    protected function getSupportedClasses()
    {
        return [
            'AppBundle\Entity\CloudFlareZone',
        ];
    }

    /**
     * {@inheritdoc}
     */
    protected function getSupportedAttributes()
    {
        return [
            self::DELETE,
        ];
    }

    /**
     * @param string               $attribute
     * @param CloudFlareZone       $object
     * @param UserInterface|string $user
     *
     * @return bool
     */
    protected function isGranted($attribute, $object, $user = null)
    {
        return $object->getOwner() === $user;
    }
}
```

It would be great to have class auto-completion for `getSupportedClasses` method, like you do for form types.

Thanks.

**Comment by Haehnchen** [comment]
Added provider inside external Php Toolbox plugin: https://github.com/Haehnchen/idea-php-toolbox/commit/36a013d537d7206eb875d974f58f62b3cf06ba9b

Need to think about who can provide such json files, we need something like this`AbstractVoter::getSupportedClasses`. idea: composer packages!?

**Comment by Koc** [comment]
@Soullivaneuh does `getSupportedClasses` returns classes for objects on which we do checks? I think that it returns token or user classes...

**Comment by Koc** [comment]
upd: sorry, you are right. But looks this methods will be deprecated soon https://github.com/symfony/symfony/pull/15151

**Comment by Soullivaneuh** [comment]
> Added provider inside external Php Toolbox plugin: Haehnchen/idea-php-toolbox@36a013d

Can't find this plugin on JetBrains repository. Is that normal?

> But looks this methods will be deprecated soon

Indeed, but not at this moment and SF 2.3 using this method is still maintained.

**Comment by King2500** [comment]
I think that plugin is not released yet.

**Comment by Haehnchen** [comment]
supported by toolbox with custom configuration, but also looking redundant to me by using the class constant syntax.
