### ISSUE TITLE
Missing service on a form object

### ISSUE THREAD

**Issue by Soullivaneuh** [Haehnchen/idea-php-symfony2-plugin#559]
With this code:

```php
$form = $this->createForm(new CDNSettingsType(), $zone->getSettings())
    ->add('flush_cache', 'button');
$form->handleRequest($request);

if ($form->isValid()) {
    // Stuff...
    if ($form->get('flush_cache')->isSubmitted()) {
        // Stuff...
    }
```

PHPStorm is telling "missing service" on `$form->get('flush_cache')`.

That's wrong because it's not a service getter but a form element.

**Comment by Haehnchen** [comment]
the problem is inside `add` it returns a ContainerInterface, really crazy. not found the problem yet, some core problems!?

```php
$form = $this->createForm()->add();
$form->get('flush_cache');
```

**Comment by Haehnchen** [comment]
fix by new PhpClass `instanceof` migration some weeks ago
