### ISSUE TITLE
Provide completion for block names in extended templates

### ISSUE THREAD

**Issue by samimussbach** [Haehnchen/idea-php-symfony2-plugin#563]
I did not find this, hopefully it is not a duplicate.

It would be really helpful if you could provide completion for block names in extended templates. If a template extends another it has to use the blocks of (one of the) Templates it is extending.

My pluginversion is 0.11.94

**Comment by Haehnchen** [comment]
its never ending story, api issues #390 ;). But will check again with new twig release: 141.2325

**Comment by RuSPanzer** [comment]
141.2462 it still not work
