### ISSUE TITLE
Search everywhere/Symfony2 Symbol does not search twig blocks names

### ISSUE THREAD

**Issue by Koc** [Haehnchen/idea-php-symfony2-plugin#567]

**Comment by cedricziel** [comment]
Can be achieved using a Symbol Contributor

https://www.jetbrains.org/intellij/sdk/docs/tutorials/custom_language_support/go_to_symbol_contributor.html

**Comment by ruudk** [comment]
Stumbled upon this issue in search of simple things to create PR's for. This issue does not explain what is needed to be done and how. Since it's from 2015, is this still relevant at all? If not, please close, thanks :)

**Comment by Haehnchen** [comment]
implemented
