### ISSUE TITLE
Missing service: "router"

### ISSUE THREAD

**Issue by apfelbox** [Haehnchen/idea-php-symfony2-plugin#571]
Hi,

(sorry if this is a duplicate and was already reported.)

Since some versions ago I noticed that the service `router` is missing. It is defined, at least calling `->get("router")` correctly fetches it.
Affects both code (`->get("router")`) and yml definitions.

![screen shot 2015-08-23 at 13 01 43](https://cloud.githubusercontent.com/assets/1032411/9427952/62a80e9c-4997-11e5-8d87-99855658a95c.png)

Not sure about other services gone missing.
(Refreshing caches etc. doesn't work)

PhpStorm: 9.0.2 #PS-141.2462
Plugin-Version: 0.11.95

**Comment by Jean85** [comment]
What Symfony2 version are you using?
It works for me here, Symonfony 2.7.3

PhpStorm: 9.0.2 #PS-141.2462
Plugin-Version: 0.11.96

**Comment by Haehnchen** [comment]
`router` is just inside the compiled container. i can add it statically like `kernel`, but better sync your cache folder?

**Comment by Jean85** [comment]
Side note: after clearing your cache, you also need to warmup it; did you do that?

**Comment by apfelbox** [comment]
@Jean85 I am using Symfony 2.7.3, just like you.
And in dev mode, the cache is automatically warmed up.

@Haehnchen I think I just found the issue. I am already using the symfony 3 directory structure (so cache in `./var/cache/`).
The plugin doesn't seem to handle that too well, if I move the cache back to the 2.x position (`./app/cache/`) it works again.

Although it is weird, that it only breaks for some services, not all of them. Is support for the new (or any arbitrary) directory structure planned? Maybe with a new option to explicitly set the cache directory?

**Comment by Jean85** [comment]
I think the support for the new dir structure could be implemented as a fallback if the standard 2.x dir is not found.

**Comment by apfelbox** [comment]
This seems to be fixed in Phpstorm 2016.1.2 (#145.1616) and plugin version 0.12.122

/cc @Haehnchen
