### ISSUE TITLE
[Container] Support for custom services definition file path in YML

### ISSUE THREAD

**Issue by JavierCane** [Haehnchen/idea-php-symfony2-plugin#573]
Hi, I have a project which uses a Service Container very similar to the Symfony one and I can have some of the features of the Container integration such as navigation from the service to it definition and viceversa, service key autocomplete, and so on but with a little "trick":

I have to modify the `.idea/symfony2.xml` file in order to specify the services definition files paths manually like:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="Symfony2PluginSettings">
    <!--… Some options configuration …-->
    <option name="containerFiles">
      <list>
        <container_file path="sub_project_1/custom/file/path/services/definition.yml" />
        <container_file path="sub_project_2/custom/file/path/services/definition.yml" />
        <container_file path="sub_project_3/custom/file/path/services/definition.yml" />
      </list>
    </option>
  </component>
</project>
```

Since this moment, I have all the features mentioned before as if I was using a Symfony project with the default service container.

The issue is that I can't add those paths through the preferences panel UI (PhpStorm settings > Other Settings > Symfony Plugin > Container) because the dialog only accept XML files despite the fact of already supporting YML ones. So the task would consist in allowing to select YML files from this dialog in order to avoid having to modify the `.idea/symfony2.xml` file by hand :)

**Comment by Haehnchen** [comment]
every yaml file is indexed automatically no need to add them in settings. moreover only xml are supported as Symfony compiles it in debug mode
