### ISSUE TITLE
Plugin breaks the context menu in the Project view

### ISSUE THREAD

**Issue by steinarer** [Haehnchen/idea-php-symfony2-plugin#575]
The Context menu in Project view seems to be broken:

Steps to reproduce:
1. Make sure the Symfony2 plugin is the only third-party plugin globally enabled
2. Create a new project in an empty directory. *The Symfony2 plugin does not have to be "project-enabled".*
3. Add some directories
4. Select multiple directories and right click

Instead of displaying the context menu, the dialogue "Choose Destination Directory" pops up and goes into some loop state.

![multiselect-directories](https://cloud.githubusercontent.com/assets/1819752/9629492/42ee0f3c-5173-11e5-92e4-5de663b2dbde.png)

**Versions:**
* Symfony2-plugin: 0.11.96
* PhpStorm: 9.0.2 (Build #PS-141.2462)

**This behaviour does not present itself:**
* When the Symfony2 plugin is globally disabled.
* When context-clicking a multiselection of files as long as the selection contains only one folder

Short screencast:
http://ws.cl.no/sc/symfony2-pluginbug.mp4

**Comment by Haehnchen** [comment]
thx for this video very helpful :+1:
is duplicate by #525, but i catched the reason, now
