### ISSUE TITLE
getRepository() returns base repository interface suggestions if classname passed

### ISSUE THREAD

**Issue by SCIF** [Haehnchen/idea-php-symfony2-plugin#577]
If i pass php5.5 [::class](http://php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class) as repository name, it will suggest methods of base repository interface only.

```
$this->getDoctrine()->getRepository(Someclass::class)->
```

Can you enable it for php5.5 or newer projects?

**Comment by Haehnchen** [comment]
fixed by #541, wait for next release

**Comment by SCIF** [comment]
Good news! Thank you!
