### ISSUE TITLE
[Doctrine] No autocompletion when using QueryBuilder->from

### ISSUE THREAD

**Issue by Azenet** [Haehnchen/idea-php-symfony2-plugin#583]
Hi,

Autocompletion does not trigger when using this kind of pattern in a repository (works if the QueryBuilder is not created within one) :

```
$qb = $this->createQueryBuilder('qb');
$qb
  ->select('i')
  ->from('AppBundle:Item', 'i')
  ->join('i.< does not autocomplete here', 'j')
  ->where('i.< does not autocomplete here')
  ->where('j.< autocompletes with the joined entity properly');
```

If I create the QueryBuilder within the repository with the alias I want (`i`) and remove the select and the from, then `i` is autocompleted properly.

**Comment by Haehnchen** [comment]
working
