### ISSUE TITLE
[Doctrine] Reimplement Model/Entity detection

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#586]
currently the doctrine Model/Entity  classes are detected in a very tricky way. use a indexer an parse classes names out of the metafile. this implementation helps also to support other non symfony+doctrine projects
```
mongodb.xml
orm.xml
couchdb.xml
annotations?
```

also implement missing features of #319

**Comment by kick-the-bucket** [comment]
Would be really great to be able to use this plugin on non-symfony + doctrine projects :)

**Comment by Haehnchen** [comment]
i am working on it :sunglasses:

**Comment by Haehnchen** [comment]
ready
