### ISSUE TITLE
[Yaml] Support escaped \ in double-quoted strings

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#601]
Because of compitibilty issues `\` need to be escaped in double-quoted, support them and add deprecated inspection. Symfony >= 2.8

> "Foo\Var" is not valid whereas "Foo\\Var"
https://github.com/symfony/yaml/commit/3fdb7acb7d4c8540ced9d9c194b5d17b27f63bff

**Comment by Addvilz** [comment]
Same with '@'
