### ISSUE TITLE
@Template annotation doesn't recognize non-html templates

### ISSUE THREAD

**Issue by Jean85** [Haehnchen/idea-php-symfony2-plugin#602]
Code example:

```
    /**
     * @Route("/some/info", name="route_name", defaults={"_format"="json"})
     * @Method({"GET"})
     *
     * @Template()
     */
    public function someAction()
    {
            ...
    }
```

In this case, the `@Template` annotation isn't clickable, because it expects a `.html.twig` file, instead of the `.json.twig` that I'm using.

Can we fix this, please?

**Comment by Haehnchen** [comment]
done

**Comment by King2500** [comment]
why not just template.*.twig?

**Comment by Haehnchen** [comment]
`@TODO: we should support types later on; but nicer`. :)
this results in a complete refactoring. for now xml, html, json support is in, that matches most use cases

**Comment by King2500** [comment]
:+1:
