### ISSUE TITLE
[Form] Autocomplete contains services, not form fields

### ISSUE THREAD

**Issue by lovenunu** [Haehnchen/idea-php-symfony2-plugin#603]
Hi,

when in a controller, when I try to do:

``` php
$form->get('foo_field')->getData();
```

`get`'s autocomplete method gives me my container's services, not the form fields. Moreover, it gives me `Method 'getData' not found in class ...` as `get`'s return type is not FormInterface.
I think it's a confusion between form and controller's `get` method: when I try to ctrl+click on the method, the helper says `Multiple implementations`.

I'm using 0.11.98 and phpstorm 9.0.2

Oh, and thank you very much for all your work on this module !

**Comment by Haehnchen** [comment]
fixed via https://github.com/Haehnchen/idea-php-symfony2-plugin/pull/1797
