### ISSUE TITLE
Custom method-references should work with constructors

### ISSUE THREAD

**Issue by akomm** [Haehnchen/idea-php-symfony2-plugin#604]
Currently this plugin is unable to provide auto completion for the following configuration (example):

CallTo: **\Hateoas\Configuration\Route**
Method: **__construct** or **Route**
Index: **0**
Provider: **route**
Contributor: **parameter**

See for this example: https://github.com/willdurand/Hateoas/blob/2d54cea457745af775433b4ba9f87da308c672f2/src/Hateoas/Configuration/Route.php#L36

In case, when you use the symfony url generator, it would be nice to be able to setup auto completion here.

**Comment by lunetics** [comment]
I got the same problem using a constructor with translationKey.

Any way to make that work?

**Comment by Haehnchen** [comment]
https://github.com/Haehnchen/idea-php-toolbox is supporting as a simple json configuration
