### ISSUE TITLE
Indexing is running continuosly

### ISSUE THREAD

**Issue by compains** [Haehnchen/idea-php-symfony2-plugin#610]
Since last update the indexing progress bar is triggering every time. I had to disable the plugin in order to work.

At beginning I waited until if finished but as soon as I just save an unchanged file it triggers again.

Once disabled I can work again.

**Comment by compains** [comment]
Updated to PhpStorm 10 and by now is working properly.

**Comment by compains** [comment]
After 5 hours with PhpStorm 10 and the plugin updated and running it seems to work fine, so I'm closing this issue.

**Comment by compains** [comment]
On a brand new Laptop pro on PhpStotm 10.0.1 every time I change an Entity starts to re index all the oppened projects.

**Comment by olegrom32** [comment]
+1

On the latest version of PhpStorm (10.0.1 build PS-143.382) and Symfony2 plugin v0.11.102 indexing process keeps running over and over again.
