### ISSUE TITLE
Minor PS API changes for 10.0.x will break plugin

### ISSUE THREAD

**Issue by neuro159** [Haehnchen/idea-php-symfony2-plugin#611]
com.jetbrains.php.lang.psi.resolve.types.PhpType#add(java.util.Collection<java.lang.String>) is removed.

please use series of com.jetbrains.php.lang.psi.resolve.types.PhpType#add(java.lang.String) calls.

**Comment by Haehnchen** [comment]
@neuro159 I think `com.jetbrains.php.lang.psi.resolve.types.PhpType#add(com.intellij.util.io.StringRef)` will also be removed?

Replacement especially for PhpTypeProvider2 would be nice. It's definitely a hack by now to simulate array return types. Is there a way do not break is feature?

```
fr.adrienbrault.idea.symfony2plugin.doctrine.ObjectRepositoryResultTypeProvider#getBySignature
```

```java
if(name.equals("findAll") || name.equals("findBy")) {
  method.getType().add(phpClass.getFQN() + "[]");
  return phpNamedElementCollections;
}
```

![nnnnnnnnnn](https://cloud.githubusercontent.com/assets/1011712/10920405/260598d0-8270-11e5-99d4-55269fef5ed3.png)

**Comment by emil-nasso** [comment]
Sorry for hijacking this issue. Does anyone know the status of this plugin in phpstorm 10? Will updating completely break it?

**Comment by Haehnchen** [comment]
PhpStorm 10 itself will work. some tests fail https://travis-ci.org/Haehnchen/idea-php-symfony2-plugin but not critical. but with next release 10.0.x we will get into trouble.

**Comment by apfelbox** [comment]
@Haehnchen could you please release a hotfix release fixing this?

In the new EAP, every (!) single click in a PHP file triggers

```
16:30:15 NoSuchMethodError: com.jetbrains.php.lang.psi.resolve.types.PhpType.add(Ljava/util/Collection;)Lcom/jetbrains/php/lang/psi/resolve/types/PhpType;
```

**Comment by ByScripts** [comment]
@apfelbox I confirm.

**Comment by Haehnchen** [comment]
... possible tomorrow
