### ISSUE TITLE
New Symfony 2.8 change: form field types are class names

### ISSUE THREAD

**Issue by weaverryan** [Haehnchen/idea-php-symfony2-plugin#623]
Hi there!

I <3 this plugin, and I usually if something isn't up to date, it suddenly is a few days later!

For Symfony 2.8, the form types have changed from being a string (e.g. `text`) to being a full class name:

```php
// before
$builder->add('username', 'text');
```

```php
// after
$builder->add('username', TextType::class);
```

In PhpStorm itself, the only unfortunate thing is that typing `TextType` does not bring up the `TextType` class as an auto-complete suggestion, because it has no static methods/constants/properties. So, you need to type `TextType::class`, and then go back and "Import class" to add the `use` statement. Ideally - if this is possible - it would auto-complete known classes that implement `FormTypeInterface` in the project.

If I can help with this, I'd be happy to assist.

Thanks!

**Comment by Haehnchen** [comment]
same on Doctrine `getRepository`; annoying behavior. want to start with a quickfix overlay first to replace string with class constant. will search for a suitable completion solution.

**Comment by MisatoTremor** [comment]
@Haehnchen This change also seems to break the form type options autocompletion.

**Comment by Haehnchen** [comment]
completion done. also added intention and generator for migration

**Comment by weaverryan** [comment]
Wow, you rock: I'll be very interested to show people the migration aspect. Thanks!

**Comment by Haehnchen** [comment]
migration and many other stuff is useless because of #651 :)

**Comment by hoshsadiq** [comment]
Sorry to open an older ticket, but the same is the case for `from` in `QueryBuilder` (probably other things too):
```php
$qb = new QueryBuilder($em);
$qb->select('t')->from(MyEntity::class, 't')
```

**Comment by dewos** [comment]
I'm +1 for @hoshsadiq question. @Haehnchen any news about this one? 
it would be useful

**Comment by hoshsadiq** [comment]
Aah damn, I was meant to raise a new issue with that as this one is closed. Totally forgot.
