### ISSUE TITLE
[Yaml] Expectation for psi/lexer changes in core plugin

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#626]
YAML Plugin will get some more love. So some symfony plugin hacks can be removed and pattern need to change.

- Implement testing for most used `Utils` to find lexer and psi changes that breaks features
- Prepare list of most painful workarounds ;)
- Legacy support possible; need it?
- ... ?

**Comment by rvanlaak** [comment]
Great news about the Yaml plugin :+1: You have an update on the IntelliJ status?

**Comment by sidz** [comment]
Hi, when or where can we get smth like alpha or beta version for PS 11? Thank you

**Comment by Shimmi** [comment]
@sidz You can find the EAP version in their confluence: https://confluence.jetbrains.com/x/ZAgNAw

**Comment by sidz** [comment]
@Shimmi I'm talking about alpha/beta version of Symfony2 plugin, not PhpStorm EAP :)

**Comment by Shimmi** [comment]
@sidz Oh! Sorry. Removing the comment as unrelated :)

**Comment by Haehnchen** [comment]
not soon; lot of work

**Comment by nicwortel** [comment]
Does this mean that we cannot use the plugin with the new PhpStorm 2016.1 yet?

**Comment by joshuataylor** [comment]
@nicwortel It's not a major update anyway, so you can probably hold off 5. This plugin dictates for example when I update PHPStorm.

**Comment by iltar** [comment]
I can't upgrade to the newest phpstorm because of yaml errors. I would offer to help out but my java knowledge is far too poor for this :(

**Comment by stof** [comment]
@Haehnchen do you have any plan for this ? 145.x builds are not the stable version

**Comment by Haehnchen** [comment]
having some free time during this week, will try my best

**Comment by leusic38** [comment]
Damned I'll work on symfony project next 2 weeks and I updated phpstorm before seeing this bug

**Comment by samplenull** [comment]
@leusic38 Download and use previous version for now https://confluence.jetbrains.com/display/PhpStorm/Previous+PhpStorm+Releases

**Comment by scaytrase** [comment]
I use to have two versions of PhpStorm in parallel (Major + EAP or Major + new Major). Updating to new PhpStorm major version never goes flawlessly

**Comment by ureimers** [comment]
@leusic38 I simply installed PhpStorm 10 again (and let the installer remove 2016 by itself). Took 2 minutes and I'm able to use all plugins.

@Haehnchen I will try to twist my bosses arm to donate you some money. Doing this all by yourself, I have to say I almost feel guilty when I read "having some free time during this week, will try my best". You need to get recompensed for the hours and hours you put into this incredibly time saving plugin(s).

**Comment by Haehnchen** [comment]
i uploaded a nightly build; main features are back in the game ...

**Comment by oojacoboo** [comment]
Haehnchen, where is this nightly plugin and how is it installed?

**Comment by samplenull** [comment]
@oojacoboo, I've installed the latest version (0.12.114) to 2016.1 release and have no issues so far.

**Comment by NickStemerdink** [comment]
@oojacoboo, try "File -> Invalidate Caches / Restart" in PhpStorm. That worked for me.

**Comment by yannickl88** [comment]
Thanks for quick fix @Haehnchen.

**Comment by TomSchillemans** [comment]
Everything works except for translation declaration lookup.
Is there something I missed?

**Comment by oojacoboo** [comment]
@NickStemerdink thanks, that did the trick!

**Comment by aurelijusrozenas** [comment]
Translation lookup does not work for me either. Nevertheless @Haehnchen you are THE man!

**Comment by ackimwilliams** [comment]
Thanks @Haehnchen Having the same issue with translation though.

**Comment by Haehnchen** [comment]
... done. will test during worktime for missing implementations that not covered by test cases
