### ISSUE TITLE
com.jetbrains.php.lang.psi.resolve.types.PhpType.add(Ljava/util/Collection;)Lcom/jetbrains/php/lang/psi/resolve/types/PhpType;

### ISSUE THREAD

**Issue by rtreffler-pgs** [Haehnchen/idea-php-symfony2-plugin#627]
[exception.txt](https://github.com/Haehnchen/idea-php-symfony2-plugin/files/41404/exception.txt)
Event Log output:
09:34:25 NoSuchMethodError: com.jetbrains.php.lang.psi.resolve.types.PhpType.add(Ljava/util/Collection;)Lcom/jetbrains/php/lang/psi/resolve/types/PhpType;

PhpStorm 10.0.2
Build #PS-143.790, built on November 12, 2015
JRE: 1.8.0_51-b16 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

Symfony2 plugin version 0.11.102

Error appears continuously while Symfony2 project is opened.
About 85 errors in 50 mins.

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

**Comment by solazs** [comment]
Same java, ubuntu and config, same error here.

**Comment by Haehnchen** [comment]
fixed by not released right now. duplicates #611 #622

**Comment by rtreffler-pgs** [comment]
Thanks for update and sorry for duplicate.

Regards,
RT
