### ISSUE TITLE
variables from controller are not autocompleted in twig view

### ISSUE THREAD

**Issue by remmel** [Haehnchen/idea-php-symfony2-plugin#633]
Hello,

Autocompletion on variables added by controller doesn't seems to work.

Eg, when I have the following controller :

```
    /**
     * @Route("/")
     * @Template("AppBundle:search.html.twig")
     */
    public function train(Request $request) {
        $user = new User();
        return [
            'varOne' => 1,
            'varTwo' => 2,
            'varThree' => 3,
            'user' => $user
        ];
    }
```

I'm expecting having autocompletion in the _search.html.twig_ file typing:
**{{var**CURSOR_HERE_AND_CTRL_SPACE**}}** or **{{user.**CURSOR_HERE_AND_CTRL_SPACE**}}**

Thanks,

Rémy

PhpStorm 10.0.1
Symfony2 plugin 0.11.104

**Comment by Haehnchen** [comment]
fixed by https://github.com/Haehnchen/idea-php-symfony2-plugin/commit/fddd5f54490a389f10557efe697d63c5b1a2854d also related to #773
