### ISSUE TITLE
Fatal Error on com/jetbrains/twig/TwigFile

### ISSUE THREAD

**Issue by welcoMattic** [Haehnchen/idea-php-symfony2-plugin#634]
Hi, I catch a fatal error on my PHPStorm 10 with Symfony2 plugin.

Weirdly, PHPStorm tell me to visit this url : http://xenji.github.com/phpstorm-symfony2-plugin/ which is an abandonware plugin. Then, I post it here.

Screenshot here:
![image](https://cloud.githubusercontent.com/assets/773875/11528444/18bcad20-98e7-11e5-9128-4cda0041bdf9.png)

Thanks

**Comment by Haehnchen** [comment]
you installed the wrong plugin, just replace it ;)

**Comment by welcoMattic** [comment]
I don't think so :/ 

![image](https://cloud.githubusercontent.com/assets/773875/11541704/f1922606-9933-11e5-9e11-d3460af0bfe0.png)

**Comment by King2500** [comment]
Uninstall "Symfony2 - Clickable Views" plugin. It's abandoned.

"Symfony2 Plugin" does the same and a lot more :)

**Comment by welcoMattic** [comment]
Thanks a lot!
