### ISSUE TITLE
Add support for Symfony 2.8 and 3 using the new directory structure

### ISSUE THREAD

**Issue by gperdomor** [Haehnchen/idea-php-symfony2-plugin#635]
Hi, i'm using Symfony 2.8 with the new directory structure but many things are missing, like template completion or service completion, etc.

Also, the plugin not work with symfony 3.

As proposal i think you should rename the plugin to "Symfony Plugin" to handle both version (Symfony 2 and Symfony 3) :D

**Comment by luchaninov** [comment]
+1

**Comment by Haehnchen** [comment]
change settings until i implement new stucture. see https://knpuniversity.com/screencast/new-in-symfony3/new-dir-structure at ~2min

**Comment by Haehnchen** [comment]
added path structure and auto configuration for new projects; also thinking of auto enable the plugin later on
