### ISSUE TITLE
Erroneous file name when creating twig template

### ISSUE THREAD

**Issue by jaimz22** [Haehnchen/idea-php-symfony2-plugin#636]
When creating a new twig template by choosing "Twig Template"  from the new file creation menu there is an additional period entered after the first portion of the filename.

For instance, the new file name box comes up and you type in "login" and press enter a file is created with the filename "login..html.twig" I'd expect it to be "login.html.twig"

This issue is new in v0.11.104 using PHPStorm 10.0.1

**Comment by Haehnchen** [comment]
@jaimz22 can you provide a screenshot, its feature i dont know about ;)

**Comment by jaimz22** [comment]
This is no longer an issue. and I'm pretty sure it wasn't even caused by this plugin
