### ISSUE TITLE
"Best Practices" template to action support missing 

### ISSUE THREAD

**Issue by iltar** [Haehnchen/idea-php-symfony2-plugin#637]
[According to the Best Practices, templates are supposed to be in `app/`](http://symfony.com/doc/current/best_practices/templates.html#template-locations). When I use `@Template`, my templates are found and I can click through. However, when I'm in my template, it "forgets" which action belongs to it. Currently one of the best features (imo) is broken with the best practices and I would love to see that fixed.

**Comment by Haehnchen** [comment]
basically is was supported by one of the first plugin commits ever, but only with help of the dumped container. :) latest plugin updates also support it out of the box eg with #784
