### ISSUE TITLE
[2.8][3.0][YAML] Definition created by "Generate Symfony2 service" is now invalid

### ISSUE THREAD

**Issue by MisatoTremor** [Haehnchen/idea-php-symfony2-plugin#638]
From the [upgrade documents](https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md) (last paragraph):

* Deprecated usage of @, `, |, and > at the beginning of an unquoted string

At least service arguments should therefor be surrounded by single quotes.

**Comment by Haehnchen** [comment]
related #601
