### ISSUE TITLE
[Twig] constant() references with double backslash

### ISSUE THREAD

**Issue by King2500** [Haehnchen/idea-php-symfony2-plugin#639]
Just tested this (see also #327).

It's not working with double backslashes in Namespace according to http://twig.sensiolabs.org/doc/functions/constant.html

``` php
{{ constant('Symfony\\Component\\HttpFoundation\\Request::<CARET>') }}
```

I also hope the full class-constant auto-completion from empty string gets implemented some time ;-)

``` php
{{ constant('<CARET>') }}
```

**Comment by Haehnchen** [comment]
https://github.com/Haehnchen/idea-php-shopware-plugin/issues/30

**Comment by Haehnchen** [comment]
working now

**Comment by King2500** [comment]
Nope:

![image](https://cloud.githubusercontent.com/assets/4896363/20158825/259cb076-a6dd-11e6-8fed-843306c0c1ca.png)

Version: 0.12.130
