### ISSUE TITLE
Symfony Version 2.7 missing from installer

### ISSUE THREAD

**Issue by apocratus** [Haehnchen/idea-php-symfony2-plugin#643]
Since a couple of days I can't select the 2.7 version when creating a new project in PHPStorm with the symfony2 plugin. Just updated the plugin to no result.

Is there a way I can add version 2.7 to the installer again?

**Comment by Haehnchen** [comment]
source for this is `http://symfony.com/versions.json`. and 2.7 is non_installable there. dont now if there is a reason for. some research or support would be nice ;)

**Comment by Haehnchen** [comment]
File will be updated soon:
> So this error is now fixed and it will be available after the next server deploy
