### ISSUE TITLE
Selecting versions for new projects should list only latest versions of each branch

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-symfony2-plugin#645]
Letting users choose the patch-level versions does not make sense: they should never use anything else than the latest one when creating a new project.

http://symfony.com/versions.json already gives the matching between maintained branches and their latest version

**Comment by stof** [comment]
Better UI would be to make them select the minor version only (e.g. displaying ``2.7`` rather than ``2.7.7``)

**Comment by Haehnchen** [comment]
sry, i do see a need for improvement. commly versions are at the top. i am personally also need to checkout a specified version
