### ISSUE TITLE
Feature request: Quick Documentation on routing

### ISSUE THREAD

**Issue by MECU** [Haehnchen/idea-php-symfony2-plugin#655]
Feature request:
When the cursor in on a route, hitting the "Quick Documentation" keyboard shortcut (mine is Ctrl-Q, Netbeans keyboard, Main Menu > View > Quick Documentation) could show the parameters. Currently, I had to click the route which loaded the action function, and then click into the `routing.yml` file. While I saved minutes thanks to this awesomeness, I'd rather just be able to popup the parameters and be done.

In a `.twig`:
![image](https://cloud.githubusercontent.com/assets/4950394/11875282/3354f69a-a4a1-11e5-9ac0-c53d652cc310.png)

Hit Ctrl-Q ("Show Parameters"):
![image](https://cloud.githubusercontent.com/assets/4950394/11875438/d13ed27c-a4a1-11e5-95cc-4d0f3f18e49b.png)

**Comment by Haehnchen** [comment]
dont a common feature
