### ISSUE TITLE
Failed to parse command output

### ISSUE THREAD

**Issue by rechengehirn** [Haehnchen/idea-php-symfony2-plugin#656]
Hi, 
I'm trying to use the Plugin with phpstorm 10.0.1 and symfony 3.0.0

When i try to add the command line tool, i get the error:

Failed to parse command output.

And the details window shows:
Problem
Failed to determine version.
Command
/usr/local/bin/php /path/to/mydir/bin/console -V
Output
Symfony version 3.0.0 - app/dev/debug

Is this Symfony version not supported or am i doing something wrong?

**Comment by King2500** [comment]
If you updated your Symfony application from 2.x to 3.0 you may have to adjust the paths in the Symfony Plugin settings.

**Comment by scaytrase** [comment]
@King2500 the problem is that version format has changed

Also there is no more `--xml` option. Now it is `--format=xml` option

**Comment by Haehnchen** [comment]
non plugin issue
