### ISSUE TITLE
NullPointerException: null on 0.11.107 with Intellij

### ISSUE THREAD

**Issue by manelephant** [Haehnchen/idea-php-symfony2-plugin#666]
On Version 0.11.107 with Intellij 14.1.6 my event log is flooded with : 

11:15:49 NullPointerException: null

I tried to : 

-uninstall / reinstall
-reindex project

Still there...Any idea ?

**Comment by Haehnchen** [comment]
some more information would be helpfull. eg full stacktrace

**Comment by Haehnchen** [comment]
sry. not helpful closing.
possible related index issues around this are more secure now

**Comment by manelephant** [comment]
ok thanx
