### ISSUE TITLE
Autocomplete route name in php and twig not working since Symfony 2.8

### ISSUE THREAD

**Issue by Tarsonius** [Haehnchen/idea-php-symfony2-plugin#669]
Since the update to symfony 2.8 the autocomplete of routes doesn't work anymore..
The format appDevUrlGenerator.php file has changed, i think..
Anyone else has this problem?

**Comment by acidjames** [comment]
Hi tarsonius, i still have route autocomplete working on 2.8.2 but twig files and controller functions are no longer connected :(

**Comment by Tarsonius** [comment]
@acidjames 
What's the format of your appDevUrlGenerator.php? This is the file, where the routes are extracted from?
Mine looks like:

```php
class appDevUrlGenerator extends Symfony\Component\Routing\Generator\UrlGenerator
{
    private static $declaredRoutes;

    /**
     * Constructor.
     */
    public function __construct(RequestContext $context, LoggerInterface $logger = null)
    {
        $this->context = $context;
        $this->logger = $logger;
        if (null === self::$declaredRoutes) {
            self::$declaredRoutes = array(
        '_wdt' => array (  0 =>   array (    0 => 'token',  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:toolbarAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'variable',      1 => '/',      2 => '[^/]++',      3 => 'token',    ),    1 =>     array (      0 => 'text',      1 => '/_wdt',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
        '_profiler_home' => array (  0 =>   array (  ),  1 =>   array (    '_controller' => 'web_profiler.controller.profiler:homeAction',  ),  2 =>   array (  ),  3 =>   array (    0 =>     array (      0 => 'text',      1 => '/_profiler/',    ),  ),  4 =>   array (  ),  5 =>   array (  ),),
```

**Comment by acidjames** [comment]
@Tarsonius the file structure is the same as yours.

Finally, i've rebuilt all the cache and seems to work + there has been an update this morning for the plugin :)

**Comment by Tarsonius** [comment]
I've updated to the latest version this morning. Still doesn't work for me..
It says 'Missing route..' in controllers and twig templates..

**Comment by gharlan** [comment]
Same issue here. it works in a 2.7 project, but not in 2.8.

> The format appDevUrlGenerator.php file has changed

the assignment has moved from property declaration to constructor. Don't know if this is the reason.

**Comment by Tarsonius** [comment]
Yes, i think, that's the problem..
The getRoutesInsideUrlGeneratorFile method in the RouteHelper class extracts the routes as follows:

```java
if(new Symfony2InterfacesUtil().isInstanceOf(phpClass, "\\Symfony\\Component\\Routing\\Generator\\UrlGeneratorInterface")) {
                for(Field field: phpClass.getFields()) {
                    if(field.getName().equals("declaredRoutes")) {
                        PsiElement defaultValue = field.getDefaultValue();
                        if(defaultValue instanceof ArrayCreationExpression) {
                            Iterable<ArrayHashElement> arrayHashElements = ((ArrayCreationExpression) defaultValue).getHashElements();
                            for(ArrayHashElement arrayHashElement: arrayHashElements) {
```

Since the update to 2.8, the default value is empty, so there are no routes for the autocomplete feature.. 
I'm not sure how to get it working again..

**Comment by Haehnchen** [comment]
thx for some debugging of what changed in detail. also supporting constructor now

**Comment by Tarsonius** [comment]
We have to thank you for the fix.. :)
