### ISSUE TITLE
ContainerAwareTrait does not autocomplete

### ISSUE THREAD

**Issue by andrewtch** [Haehnchen/idea-php-symfony2-plugin#679]
Hi all!

For symfony 3 project controllers use ContainerAware trait. Unfortunately, autocmpletition with this approach does not work anymore.

Is it plugin-related or is it PHPStorm issue?

**Comment by Haehnchen** [comment]
@andrewtch where do you expect completion `ContainerAwareTrait` is a setter only `container` is also working fine

**Comment by andrewtch** [comment]
```ContainerAwareTrair``` says that a class has 

```
    /**
     * @var ContainerInterface
     */
    protected $container;
```

However, $this->container does not autocomplete in Controlelrs. Before latest update it did:

![image](https://cloud.githubusercontent.com/assets/925330/13199962/d002c636-d83e-11e5-9c65-29f8ccd1a936.png)

is it more of PHPStorm or of SymfonyPlugin issue?

**Comment by Haehnchen** [comment]
duplicate #689

**Comment by Haehnchen** [comment]
reported: https://youtrack.jetbrains.com/issue/WI-31048
