### ISSUE TITLE
Create template for controller action is broken

### ISSUE THREAD

**Issue by Knagg0** [Haehnchen/idea-php-symfony2-plugin#681]
When using the @Template annotation, the create template helper will only create .xml.twig files.
But the default symfony application needs .html.twig files.
Is there any config i haven't seen to fix this?

![screenshot](https://cloud.githubusercontent.com/assets/670319/13169757/16aece98-d6e8-11e5-938b-73217b19294d.png)

Symfony Version: 3.0.2
Symfony Plugin Version: 0.11.109
PHPStorm Version: 10.0.3

**Comment by xeroxzone** [comment]
+1

**Comment by Knagg0** [comment]
Thanks for the fix... Works again :-)
