### ISSUE TITLE
ConsoleOutput Formatted issues

### ISSUE THREAD

**Issue by robhunt3r** [Haehnchen/idea-php-symfony2-plugin#682]
So, when using `ConsoleOutput` in PhpStorm, it gives you multiple errors related to 'Closing tag name missing' when for example, using this

`$output->writeln("<options=bold>Hello world</>");`

As `options` tag is not closed, it throws you an error, when the full php class is correct... I couldn't find any way to disable html inspections inside PHP strings in order to avoid this and get a 100% ok class in phpstorm... I think it should be a warning instead, but not an error...

Maybe this plugin can make it work correctly when using ConsoleOutput ?

**Comment by Haehnchen** [comment]
there is nothing i can do about it; jetbrains issue

**Comment by robhunt3r** [comment]
Such a pity. Thanks!

**Comment by Loilo** [comment]
This comes up when googling (like I did), so for anyone interested, here's a solution (sorry for spamming you, maintainers).

Add a `@lang` tag right before the string, like this:
```php
$output->writeln(/* @lang text */ "<options=bold>Hello world</>");
```

PhpStorm will highlight the string as plain text and therefore won't complain about unclosed tags.
