### ISSUE TITLE
Translation for .xliff extension

### ISSUE THREAD

**Issue by hjurgeleit** [Haehnchen/idea-php-symfony2-plugin#684]
Our project uses translation files named ``messages.<LOCALE>.xliff`` which is obviously not found by the plugin. Changing the file extension to .xlf the translation keys are known immediately.
Can you add support for ``.xliff`` extension please?

**Comment by Haehnchen** [comment]
done

**Comment by hjurgeleit** [comment]
wow! that was quick! thank you very much!

**Comment by rvanlaak** [comment]
Awesome! :rocket:

**Comment by rvanlaak** [comment]
CTRL+click in Twig does only work for `.xlf` and not for `.xliff`

**Comment by TomSchillemans** [comment]
@Haehnchen To compliment @rvanlaak last comment. Apart from needing to rename the `.xliff` files to `.xlf` (Maybe different release? I am running 0.11.114), it also doesn't jump to the correct translation key. 
Is this something that can be fixed too?
