### ISSUE TITLE
Download compiled files on remote deployment files

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#685]
Reuse webDeployment plugin and continuously check for remote files like routing and container. Improves usages of vagrant and other VMs resolves #269

- provide menu entry inside "Remote Host"; sync Symfony files
- support routing and container files
- implement multi routing ui fixes #138

**Comment by Haehnchen** [comment]
related http://stackoverflow.com/questions/35101331/phpstorm-symfony-plugin-deployment-paths

**Comment by Koc** [comment]
Awesome! Thank you

**Comment by Koc** [comment]
@Haehnchen is there remote translations support?

**Comment by Haehnchen** [comment]
currently not, but will follow
