### ISSUE TITLE
Autocomplete stops working after class cache is generated

### ISSUE THREAD

**Issue by UNOwen** [Haehnchen/idea-php-symfony2-plugin#689]
Environment: PhpStorm 10.0.3 OSX, php 7.0 installed from homebrew, Symfony Plugin 0.11.112, Symfony 3.0.3 fresh install.

Steps to reproduce:
1. Run `bin/console server:run`, open http://127.0.0.1:8000. Try autocompleting `$this->container->get('templating')` e.g. within a controller: autocomplete works properly.
2. Run `bin/console cache:clear`, visit http://127.0.0.1:8000, then force Symfony Plugin clear its index. Try autocompleting the snippet above: it will say it can't find `$this->container` declaration.
3. Delete `var/cache/dev/classes.php`, clear Symfony Plugin index again: the snippet above will be autocompleted again.

Unfortunately, I have no idea how and why this happens.

Further note: being a brand new Symfony Plugin user, I have no idea wether this happens with other Plugin versions or not.

**Comment by Haehnchen** [comment]
this is because of a duplicate trait name `ContainerAwareTrait` in your project. it inside vendor and also in classes.php file. this a bug of PhpStorm i will report it.

btw you should ignore the cache in Settings -> Project -> Directories

**Comment by Haehnchen** [comment]
reported: https://youtrack.jetbrains.com/issue/WI-31048
