### ISSUE TITLE
Add Symfony 2.8: YAML deprecations inspections

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#693]
http://symfony.com/blog/new-in-symfony-2-8-yaml-deprecations
see also #601, #638

**Comment by Haehnchen** [comment]
related https://github.com/symfony/symfony/issues/18079

**Comment by Haehnchen** [comment]
also `%` https://github.com/symfony/symfony/pull/17809/files

**Comment by stof** [comment]
@Haehnchen your implementation is broken. It detects ``\n`` as a deprecated usage, while this is a valid escape sequence
