### ISSUE TITLE
"Navigate to definition" does not work 

### ISSUE THREAD

**Issue by Strate** [Haehnchen/idea-php-symfony2-plugin#698]
![image](https://cloud.githubusercontent.com/assets/392644/13807207/0a3e26b6-eb71-11e5-8755-0e6c46622a91.png)
Clicking by this button does not shows popup on PhpStorm PS-145.256.26 (2016.1)

**Comment by Haehnchen** [comment]
because of #626

**Comment by Haehnchen** [comment]
fixed in nightly build by #626
