### ISSUE TITLE
Optimize Yaml key auto completion

### ISSUE THREAD

**Issue by theofidry** [Haehnchen/idea-php-symfony2-plugin#700]
When starting to type `class`, get the auto-completion suggestion and select it, it completes the `class` word. That's cool but it could be better by completing `class:`. The same goes for other keys. For array keys, like `arguments`, it could either auto-complete to `arguments: []` or to:

``` yaml
arguments:
    - 
```

Maybe adding a configuration entry for choising between both.

**Comment by Haehnchen** [comment]
https://github.com/Haehnchen/idea-php-shopware-plugin/issues/30
