### ISSUE TITLE
Travis status is incorrect

### ISSUE THREAD

**Issue by NicoHaase** [Haehnchen/idea-php-symfony2-plugin#706]
According to https://travis-ci.org/Haehnchen/idea-php-symfony2-plugin/builds/117786755, there were some failed tests. But Travis marks your build as passed, which seems incorrect

**Comment by Haehnchen** [comment]
because of `allow_failures` matrix; dropped now

**Comment by NicoHaase** [comment]
https://travis-ci.org/Haehnchen/idea-php-symfony2-plugin/jobs/117963542 as an example for a recent build does not look better: even though there is an exception thrown, the build is marked as passed

**Comment by Haehnchen** [comment]
removed this "background exception", status fine
