### ISSUE TITLE
[XLF] XLF declaration go-to doesn't go to the correct entry

### ISSUE THREAD

**Issue by TomSchillemans** [Haehnchen/idea-php-symfony2-plugin#712]
The plugin knows that the key is there, but it isn't jumping to the correct key in the translation file.
It opens the file however, but jumps to the place where the cursor was the last time the file was opened.

**Comment by Haehnchen** [comment]
todo: register them on project initialize seen by Drupal plugin on `.module` extension.
related #479

**Comment by Haehnchen** [comment]
done, you need to whitelist xlf extension for xml inside "File Types" of PhpStorm settings
