### ISSUE TITLE
[XLF] Create new XLF entry from non-existing translation

### ISSUE THREAD

**Issue by TomSchillemans** [Haehnchen/idea-php-symfony2-plugin#713]
If there is no translation found for a key, generate a new xlf entry in the domain.

it would look something like this:

``` xlf
<trans-unit id="1">
    <source><![CDATA[translation.key]]></source>
    <target><![CDATA[This is the value for the translation key]]></target>
</trans-unit>
```

It would mean that you would select a file in where it would be placed (as with YAML)
and also that it would need to be inserted **after** the last `<trans-unit>` element.
Additionally get the `id` of the previous `trans-unit` and add 1 to it

**Comment by Haehnchen** [comment]
done by #479 and https://github.com/Haehnchen/idea-php-symfony2-plugin/commit/0a27c3fb617a3fa8b4415ec605ba27bb9bee6b9c
