### ISSUE TITLE
Erroneous warnings about expected classes in YML service definitions

### ISSUE THREAD

**Issue by pmishev** [Haehnchen/idea-php-symfony2-plugin#715]
With the latest phpstorm and symfony plugin, on a Symfony 2.8 project, I'm getting a lot of wrong warnings about the expected service parameter types:

![yml services](https://cloud.githubusercontent.com/assets/5188763/14459142/31be3da0-00ae-11e6-9a41-40cfff1dda8a.png)

On the other hand, in the same yml file, I have other service definitions that show no warnings at all, even though I mix the order of the params on purpose!

The issue does not exist on PhpStorm 10 / 0.11.115.

------------------------

PhpStorm 2016.1
Build #PS-145.258, built on March 16, 2016
JRE: 1.8.0_76-release-b18 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Symfony Plugin Version: 0.12.115

**Comment by Haehnchen** [comment]
fixed by latest commits, pls just wait for new relase today
