### ISSUE TITLE
Translations with translation in parameter: guessed invalid translation_domain

### ISSUE THREAD

**Issue by BrechtBonte** [Haehnchen/idea-php-symfony2-plugin#716]
In a file

``` Twig
{% trans_default_domain "test_domain" %}

{{ "label_a"|trans }}

{{
    "label_b"|trans({
        '%some%': "label_c"|trans,
        '%vars%': "label_d"|trans({}, 'different_domain')
    })
}}
```

The following domains are guessed for the labels (and validation and hinting are based off of these):

| Label | Domain | Correct |
| --- | --- | --- |
| label_a | test_domain | ✔️ |
| label_b | different_domain | ✖️ |
| label_c | different_domain | ✖️ |
| label_d | different_domain | ✔️ |

**Comment by Haehnchen** [comment]
fixed and released
