### ISSUE TITLE
Shortcut to routing in margin no longer visible

### ISSUE THREAD

**Issue by jurriaanr** [Haehnchen/idea-php-symfony2-plugin#717]
I no longer see the handy shortcut to the routing when looking at my actions in the controller.

The appDevUrlGenerator.php is generated and available. No idea when this broke, because I waited a long time before switching to the ugly logo version of phpstorm. But it looks like it broke since I switched.

![image](https://cloud.githubusercontent.com/assets/7426848/14491483/4ddadf54-0179-11e6-8fea-d5dc7eccfb59.png)

**Comment by Haehnchen** [comment]
please update to latest build and force a cache invalidation

**Comment by jurriaanr** [comment]
Yes, fixed, thank you
