### ISSUE TITLE
Form configureOptions doesn't autocomplete

### ISSUE THREAD

**Issue by clytemnestra** [Haehnchen/idea-php-symfony2-plugin#718]
Phpstorm 10 and 2016.1

``` php
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Bundle\Entity\Ad'
        ));
    }
```

Missing autocomplete on both data_class(or any other parameter that goes here) and the entity itself.
'Bundle\Entity\Ad' is also not clickable, goTo doesn't work.

**Comment by Haehnchen** [comment]
fixed by a previous release becasue of `OptionsResolverInterface` drop on Symfony 3.x.
fyi: better use `Ad::class`
