### ISSUE TITLE
Click from view to controller with @template() notation

### ISSUE THREAD

**Issue by RobVermeer** [Haehnchen/idea-php-symfony2-plugin#723]
In our current setup we have the templates located in `app/Resources/views`. We want to use the `@template` annotation but this will break the ability to click from the view back to the controller.

Example:

``` php
/**
 * @template('example/show.html.twig')
 */
```

With this I can command click on the template and go right to it. When in the template itself there is no ability to go back to the controller.

When using the render method it does work:

``` php
return $this->render('example/show.html.twig', []);
```

Command clicking on the template will result in going to the template and in the template itself you can click back to the controller.

**Comment by Haehnchen** [comment]
https://github.com/Haehnchen/idea-php-shopware-plugin/issues/30

**Comment by Haehnchen** [comment]
support for Template annotations added by latest plugin versions
