### ISSUE TITLE
 NoClassDefFoundError erros on  .xml .svg  and .dist

### ISSUE THREAD

**Issue by AlaeddineMessadi** [Haehnchen/idea-php-symfony2-plugin#724]
```
 NoClassDefFoundError
         Error while indexing /home/mypc/vagrant/data/www/control-panel/symfony/web/build/fonts/open-sans-latin_latin-ext-600.svg
         To reindex this file IDEA has to be restarted: Could not initialize class com.intellij.psi.xml.XmlChildRole
```

and : 

`NoClassDefFoundError: Could not initialize class com.intellij.psi.xml.XmlChildRole`

hundreds of exceptions.. :(

PhpStorm 2016.1
Build #PS-145.258, built on March 16, 2016
JRE: 1.8.0_76-release-b18 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by Haehnchen** [comment]
duplicates #707. thx for given `.svg` error scope

**Comment by Haehnchen** [comment]
filtered, only xml are taken now, also if svg technically a xml syntax
