### ISSUE TITLE
Controllers are not annotated with routes anymore

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-symfony2-plugin#725]
When using PhpStorm 10, controllers had an annotation (not sure whether it is the right name) allowing to access the associated route definition. In PhpStorm 2016.1, this does not appear anymore (I'm using Yaml for my route definitions)

**Comment by NicoHaase** [comment]
Have you tried clearing the caches through settings, Languages & Frameworks, Symfony? I can still see the icon next to the PHP code, and clicking it opens the yml file

**Comment by stof** [comment]
yeah, I saw it on some controllers too. I'm not sure why one of them was not having the annotation at that time.

**Comment by Haehnchen** [comment]
thats because of the continuous yaml plugin migration. without a change in files or a forced index rebuild the new values dont make it. commit will force a index rebuild in next release
