### ISSUE TITLE
Inspections about using FQCN rather than type name should be disabled on Symfony 2.7

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-symfony2-plugin#734]
Displaying such warning when the project uses Symfony 2.7 or older is wrong (and annoying as it creates lots of messages I need to ignore, making it harder to spot real warnings)

**Comment by stof** [comment]
OK, not that critical as I can disable the inspection in the PhpStorm settings, but it would still be great that the inspection detects automatically whether it should warn or no.

**Comment by Haehnchen** [comment]
version compare on `\Symfony\Component\HttpKernel\Kernel::VERSION` also discussed in commit https://github.com/Haehnchen/idea-php-symfony2-plugin/commit/cf47fb74184638e20ab51f865220de158b1dd9bd

**Comment by stof** [comment]
Well, I totally agree with @XitasoChris on this. Forcing users to disable the inspections manually based depending on their Symfony version is a bad user experience.

**Comment by Haehnchen** [comment]
done
