### ISSUE TITLE
Create service in YAML format should use space instead of tab

### ISSUE THREAD

**Issue by leo108** [Haehnchen/idea-php-symfony2-plugin#736]
It's recommended to use `space` instead of `tab` in YAML format

**Comment by veloxy** [comment]
I agree, it's stated in the [Symfony docs](http://symfony.com/doc/current/components/yaml/yaml_format.html) to always use spaces:

>There is one important thing you need to remember when using indentation in a YAML file: Indentation must be done with one or more spaces, but never with tabulators.

**Comment by veloxy** [comment]
Also, this is a duplicate of #533

**Comment by Haehnchen** [comment]
done
