### ISSUE TITLE
Unused use statement while used as constant in annotation

### ISSUE THREAD

**Issue by akeeman** [Haehnchen/idea-php-symfony2-plugin#752]
### Introduction
The plugin is capable of marking use statements as used when a class is used in an annotation, when it is preceded with an @.

```php
use Acme\Component\Example\Annotations\Example; // This use statement will be recognized as used.

/**
 * @Example
 */
class Example
{
    // ...
}
```

The doctrine annotation reader is also capable of reading constants from a class in annotations. The plugin is capable of recognizing this too, as one can follow the reference by ctrl+clicking the class name (e.g. in the example below the 'ClassWithConstant' in the annotation is clickable).

```php
use Acme\Component\Example\Annotations\Example; // This use statement will be recognized as used.
use Acme\Component\Example\ClassWithConstant; // This use statement will NOT be recognized as used.

/**
 * @Example(ClassWithConstant::SOME_CONSTANT)
 */
class Example
{
    // ...
}
```

### Problem description
In the example above, the class that is only used as part of a constant name is not recognized as used. Thus it gets a grey color, red underline and will say something like "Import 'Example\Component\Example\ClassWithConstant' is never used [...]". As the doctrine annotation reader does use this import, it is incorrectly marked as not used.
Real problems arise when one tries to fast cleanup files and remove unused use statements, or use functions like the auto-format-tool with default settings, which will remove the 'unused annotation', leaving the file broken.

### Solution
It would be very nice that such use statements get recognized as used.

**Comment by Koc** [comment]
Duplicates https://github.com/Haehnchen/idea-php-annotation-plugin/issues/26 https://github.com/Haehnchen/idea-php-annotation-plugin/issues/51 and many others

**Comment by akeeman** [comment]
Ah, I see. I missed them in my quick search :/

**Comment by Haehnchen** [comment]
fixed at external plugin done
