### ISSUE TITLE
No autocomplete for SVG assets

### ISSUE THREAD

**Issue by mafzst** [Haehnchen/idea-php-symfony2-plugin#753]
In twig template it's possible to insert all the block `{{ asset('img/image.png` }}` when starting typing the asset path. 

![image](https://cloud.githubusercontent.com/assets/6941014/16145948/c47bed76-347b-11e6-8de9-7e0af5d27ac9.png)

It's not possible to do it for svg ressources.

It would be very useful to increasing efficiency!

**Comment by Haehnchen** [comment]
done
