### ISSUE TITLE
Shortcut for services are not working

### ISSUE THREAD

**Issue by jeancsil** [Haehnchen/idea-php-symfony2-plugin#754]
After the plugin update there are a lot of error messages into the PHPStorm console as well as the shortcut for the DIC are not working anymore.

Plugin version: 0.12.121
The error message received is:

> IllegalArgumentException: Argument for @NotNull parameter 'className' of fr/adrienbrault/idea/symfony2plugin/dic/ContainerService.addClassName must not be null

**Comment by Haehnchen** [comment]
looks like a eap channel problem related to #737, to be fixed in next release

**Comment by Haehnchen** [comment]
fixed
