### ISSUE TITLE
Global "Generate" popup is overwritten

### ISSUE THREAD

**Issue by kstenschke** [Haehnchen/idea-php-symfony2-plugin#760]
Tested in IntelliJIdea (seems not to happen in PhpStorm) When having opened a project marked as Symfony project, pressing CTRL+ENTER globally opens the symfony2 plugin's "New"-Popup, and in some cases overrides local KeyListeners registered on components of other plugins' toolWindows.

Better: Prevent affecting other plugins: register that keyListener on specific components, e.g.: the IDEs "Project" toolWindow.

**Comment by Haehnchen** [comment]
there is no custom key mapping in this plugin. inspection and quickfixes are just extended

**Comment by Haehnchen** [comment]
closing. no response and there is not such event registering
