### ISSUE TITLE
Autocomplete service ids for ContainerBuilder::removeDefinition

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-symfony2-plugin#761]
``ContainerBuilder::removeDefinition`` takes a service id as first (and only) argument. It would be great to provide autocompletion there (including private services)

**Comment by Haehnchen** [comment]
https://github.com/Haehnchen/idea-php-shopware-plugin/issues/30

**Comment by stof** [comment]
@Haehnchen you could do the same for ``removeAlias`` btw

**Comment by Haehnchen** [comment]
done
