### ISSUE TITLE
Plugin broken with latest EAP?

### ISSUE THREAD

**Issue by mnapoli** [Haehnchen/idea-php-symfony2-plugin#762]
I've updated to the latest EAP and many features seem to be broken, for example Twig autocompletion, autocompletion from services fetched from the container (even though Ctrl+Click on a service ID still works), etc.

Is this a known issue? I've searched for similar issues without finding anything.

**Comment by Haehnchen** [comment]
some tests fail for PhpStorm 2016.2, but main features are working

**Comment by Haehnchen** [comment]
all features should work again
