### ISSUE TITLE
No auto-completing using @Template annotation

### ISSUE THREAD

**Issue by marcel-ambta** [Haehnchen/idea-php-symfony2-plugin#773]
When using the @Template annotation for actions:

> /**
>      \* @author Marcel van Nuil marcel@ambta.com
>      \* @Route("{edmCampaign}", name="_dashboard_edm_campaign_view")
>      \* @Security("has_role('ROLE_ADMIN') or has_role('ROLE_USER') or has_role('ROLE_TELEMARKETER') or has_role('ROLE_COMPANY_USER')")
>      \* @Template("ExampleBundle:Template/Dashboard/Pages/Edm:CampaignView.html.twig")
>      \* @ParamConverter("edmCampaign")
>      *
>      \* @param EdmCampaign $edmCampaign
>      *
>      \* @return array
>      */
>     public function viewAction(EdmCampaign $edmCampaign)
>     {
>         return [
>             'edmCampaign' => $edmCampaign
>         ];
>     }

You do not have auto-completing in the Twig template. This only works when you use return $this->render. For ease we now use both, but would be nice if only the @Template annotation would be sufficient.

**Comment by MiguelAlcaino** [comment]
I'm facing the same issue at the moment. Not sure if it is my installation or the plugin. I remember it was working.

**Comment by Haehnchen** [comment]
no support for this atm, only render or folder structure detection

**Comment by MiguelAlcaino** [comment]
Thanks @Haehnchen Your are very kind! :)

**Comment by MiguelAlcaino** [comment]
It is happening in all the alias starting with "@".

**Comment by MiguelAlcaino** [comment]
Hi @Haehnchen .Hope you are well!. 
After the last update the aliases of templates are not working with this format too: 

AppBundle:ViewFolder:myView.html.twig
Also it is not working with:
@App/ViewFolder/myView.html.twitg

You can see this when using the @Template annotation inside a controller.

Cheers!

**Comment by Haehnchen** [comment]
@MiguelAlcaino os environment issue hopefully fixed now  :) #803

**Comment by MiguelAlcaino** [comment]
It is working now! Thanks @Haehnchen !

**Comment by Haehnchen** [comment]
so closeable
