### ISSUE TITLE
Bug - problem with type hinting

### ISSUE THREAD

**Issue by er1z** [Haehnchen/idea-php-symfony2-plugin#779]
I don't know if it's directly associated with plugin but I encountered on this weird issue.

Probably plugin incorrectly flushes type cache: https://www.dropbox.com/s/xzl67fm4lokaz64/Screenshot%202016-08-22%2015.15.33.png?dl=0

What produces an incorrect hinting/etc. It appears nevetherless the "invalidate caches and restart" usage. I also noticed that for a few minutes since IDE start everything works fine - later: starts to behave pretty weird as on the picture above.

PHPStorm 2016.2 and the newest plugin version.

**Comment by Haehnchen** [comment]
not related to this plugin
