### ISSUE TITLE
Switch from PhpResolveResult#create to PsiElementResolveResult#createResults 

### ISSUE THREAD

**Issue by neuro159** [Haehnchen/idea-php-symfony2-plugin#782]
This is quick and straightforward change.
We dropping this intermediate non-open class in 2016.3, EAP starts Sep 1 '16 
Target platform method exists since 2010, only a year after we made ours )
3 of your plugins (Symfony, annotations, shopware) are only external users of this class.

**Comment by Haehnchen** [comment]
thx, all plugins updated
