### ISSUE TITLE
wrong annotation for entity setter/getters 

### ISSUE THREAD

**Issue by cAstraea** [Haehnchen/idea-php-symfony2-plugin#783]
Not sure if it's the plugin doing this or symfony ? Anyone bumped into this ?

when defined an entity property like 
    /**
     * @var string
     * @ORM\Column(name="sp_email", type="text", length=50, nullable=true)
     */
    private $sponsor_email;

Would let phpstorm auto generate them by writing public function and autocomplete. 
However after the last updates it's generating wrong for example for get would generate 
    /**
     * @return string
     */
    public function getSponsorEmail(): string
    {
        return $this->sponsor_email;
    }
why does it add that : string at the end ? 

and for set 

   /**
     * @param string $sponsor_email
     */
    public function setSponsorEmail(string $sponsor_email)
    {
        $this->sponsor_email = $sponsor_email;
    }
where it should be 

   /**
     * @param string $sponsor_email
     */
    public function setSponsorEmail($sponsor_email)
    {
        $this->sponsor_email = $sponsor_email;
    }

Was getting a really weird error on cache:clear --env prod because of that string coerce on $sponsor_email 

  [Doctrine\Common\Proxy\Exception\UnexpectedValueException]
  The type hint of parameter "sponsor_email" in method "setSponsorEmail" in class "AppBundle\Entity\Account" is invalid.

  [ReflectionException]
  Class AppBundle\Entity\string does not exist

**Comment by King2500** [comment]
Looks like you have PHP Language level 7.0 or greater.
Check:
https://www.jetbrains.com/help/phpstorm/2016.2/enabling-php-support-in-a-project.html#choose_interpreter

Maybe your Doctrine version does not support PHP 7 type hints.
Set your PHP language level lower or consider upgrading Symfony/Doctrine.

**Comment by cAstraea** [comment]
Indeed this was it thanks :D Had to upgrade the doctrine to >2.5.3 to take advantage of the PHP 7 scalar type-hints.
