### ISSUE TITLE
[Form] adding field does not properly autocompletes some properties

### ISSUE THREAD

**Issue by Koc** [Haehnchen/idea-php-symfony2-plugin#786]
There is `Company` class with protected property `$uploadedLogo`. I've create form for it

```php
class CompanySaveLogoType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                '<autocomplete>',
                'file',
                array(
                    'required' => !$options['data']->getLogo(),
                )
            );
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(
            array(
                'data_class' => Company::class,
            )
        );
    }
}
```
![2016-09-03_13-03-11](https://cloud.githubusercontent.com/assets/191082/18224228/5f2ec850-71d7-11e6-8cb8-32facdaf6bf0.png)

As you see from screenshot there are some autocompletes: two fields - ok, method `updated` - looks strange and `uploaded_logo` - it correctly discovers method, but why in underscore? Property is `uploadedLogo`.

**Comment by Haehnchen** [comment]
released, also dropped "uploaded_logo" completion some completion as Twig now. hope that more useful for all
