### ISSUE TITLE
"Cannot resolve symbol" for factory service, regression

### ISSUE THREAD

**Issue by zerkms** [Haehnchen/idea-php-symfony2-plugin#791]
This worked before, but now the factory method is highlighted in red as an error

![screenshot](https://photos-6.dropbox.com/t/2/AAAL2YBu5v1kYRcOKn0b7fBfUm26dqIs8PZrPnljBklAGQ/12/4486681/png/32x32/3/1474272000/0/2/Screenshot%202016-09-19%2015.04.19.png/EMbirgMY0JIGIAcoBw/sQ3TQDC6O5_Apk_dB8BSw5nJ8Ia5Y3gRiMiijP9uIB0?size_mode=3&dl=0&size=2048x1536)

The `ctrl+click` still leads to the proper method, since

* `rabbitmq.stream_connection` is an instance of `\PhpAmqpLib\Connection\AMQPStreamConnection`
* there is a `\PhpAmqpLib\Connection\AMQPStreamConnection::create` method declared

The auto-completion also works fine when I type the `method` parameter.

The same is reproducible with other factories as well.

Versions used:

* Symfony Plugin v0.12.125
* phpstorm v2016.2.1

**Comment by Haehnchen** [comment]
done and added better completion, too

**Comment by Haehnchen** [comment]
released
