### ISSUE TITLE
Symfony2 Plugin: missing routing file

### ISSUE THREAD

**Issue by kbond** [Haehnchen/idea-php-symfony2-plugin#80]
I am getting this error when starting PhpStorm.  I see this was added in the latest version (0.9.3) but am not sure how to resolve.  

I am using JMSI18nRoutingBundle if that makes any difference.

**Comment by cilefen** [comment]
If this happens to you more recently note that the plugin may look for the file in var/cache/dev/appDevUrlGenerator.php assuming you have the new 3.0 layout. If that happens on a 2.x project, simply change the path in on the plugin configuration form.
