### ISSUE TITLE
High load when plugin is enabled

### ISSUE THREAD

**Issue by metalmini** [Haehnchen/idea-php-symfony2-plugin#800]
I am experiencing some problems with this plugin. Whenever i enable the plugin i have a high load on my Mac (macOS Sierra 10.12, 2,3 GHz Intel Core i7, 8 GB mem)

![screenshot 2016-10-05 14 51 16](https://cloud.githubusercontent.com/assets/510652/19113716/4351414c-8b0b-11e6-91af-15e3c49a3240.png)

I was running version 0.12.127 of the plugin when i first noticed the high load. So i downgraded to 0.12.126 but this made no difference.

PhpStorm 2016.2.1
JRE: 1.8.0_76-release-b216 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Any ideas where i can find the solution to this problem?

Thanks in advance!

**Comment by apfelbox** [comment]
I had the same issue, but after updating to the most recent (and the one before) EAP, the issue is gone.

**Comment by metalmini** [comment]
Installed PHPstorm EAP, results are the same:

![screenshot 2016-10-05 16 15 14](https://cloud.githubusercontent.com/assets/510652/19116813/10843966-8b17-11e6-8b21-058c91c1f6a1.png)

**Comment by metalmini** [comment]
This is not a problem if i open another project (with less routes, services etc.)

**Comment by Haehnchen** [comment]
is there a way to reduce the issue scope; which component routing, services results in this behavior, try to delete some of them ;)

did you ignore you cache folder for not indexing it?

**Comment by metalmini** [comment]
![screenshot 2016-10-06 08 45 42](https://cloud.githubusercontent.com/assets/510652/19142961/4be108c4-8ba1-11e6-8675-72c6c26141d8.png)

All settings are default for a Symfony project.

This morning i went and check the above settings, which are only available if the plugin is enabled, and it seems to be smooth sailing. So i am going to monitor the usage and come back in a couple of hours.

**Comment by metalmini** [comment]
One step further, there seems to be one twig template that causes this high load. If i select and cut all the text from the file, the load drops. If i paste it back and save it, boom, its high again.

**Comment by Haehnchen** [comment]
is the ide still responding or blocked? possible an endless loop in twig template paths.

**Comment by dr0bz** [comment]
Same behavior. Change a twig file and save. Clicking save causes a full load on cpu's. The ide is still responsive. I've tried 0.12.127, .126 and .125 versions. I fear the issue is not new. If you need more investigation let me know.

**Comment by metalmini** [comment]
I can still use the ide, scrolling becomes a pain. And my Mac starts to turn on the fans, which never happens.

The endless loop thing, i removed all the includes in the template but the problem still occurs. Is there a debug option in the plugin that logs its every move? This might help.

**Comment by Blackskyliner** [comment]
When I had this problem I increased the memory the JavaVM can use via "Help | Edit Custom VM Options". Since then I don't have this problem anymore as the whole index needs no swapping anymore and can be held in memory (I guess).

**Comment by metalmini** [comment]
Thanks for the comment but i will be waiting for the next release to see if this makes any difference.

**Comment by metalmini** [comment]
Updated to last version, system seems a lot more stable.

Problem solved, thanks!
