### ISSUE TITLE
CPU usage: more than 300%

### ISSUE THREAD

**Issue by dop3** [Haehnchen/idea-php-symfony2-plugin#801]
Hi all.
I talked with jetBrain support becouse i've found that editing a very specific file the CPU usage of my mac goes to more than 300%.
After sending them ide.log and the "guilty" file they asked me to disable the symfony2 plugin. Disabling it solved the problem.
I'm posting here to see if you can do something about it.
Attached the template file.

Thanks,
Marcello

[guilty.html.twig.zip](https://github.com/Haehnchen/idea-php-symfony2-plugin/files/515614/guilty.html.twig.zip)

**Comment by King2500** [comment]
Same as #800?

**Comment by dop3** [comment]
yes, I can close this issue!
