### ISSUE TITLE
Cann't navigate to Twig templates from xml

### ISSUE THREAD

**Issue by Koc** [Haehnchen/idea-php-symfony2-plugin#803]
``` xml
        <service id="brouzie_widgets.data_collector"
                 class="Brouzie\Bundle\WidgetsBundle\DataCollector\WidgetsDataCollector">
            <argument type="service" id="brouzie_widgets.data_collector_widget_manager" />
            <tag name="data_collector" template="@BrouzieWidgets/profiler.html.twig" id="brouzie_widgets"  />
        </service>
```

no ctrl+click or autocomplete on `@BrouzieWidgets/profiler.html.twig`

**Comment by plfort** [comment]
Same issue in Controller ($this->render) since 0.12.128

**Comment by Haehnchen** [comment]
are ADD_PATH entries inside "Languages & Frameworks -> Symfony > Twig / Templates" for bundles visible on your enviroment?

**Comment by Haehnchen** [comment]
sry guys os path issue. please update to latest release

**Comment by plfort** [comment]
Sounds good to me , thank you !

**Comment by Koc** [comment]
Still reprodusable https://yadi.sk/i/0YV-55J738Au9d

**Comment by Haehnchen** [comment]
fixed by https://github.com/Haehnchen/idea-php-symfony2-plugin/commit/53b121d7eb6d04490ac761a4842b4fccb269e3c8

**Comment by Koc** [comment]
@Haehnchen thank you, will check
