### ISSUE TITLE
Creating a Template using a Quick-Fix

### ISSUE THREAD

**Issue by 0TshELn1ck** [Haehnchen/idea-php-symfony2-plugin#806]
Creating a Template using a Quick-Fix does not work properly after update.
When using combination Alt + Enter - template creates in the wrong folder path. 

the expected path (src/bundle/Resources/views)
actually path (null/Resources/views)

**Comment by timfennis** [comment]
I'm having a similar issue after upgrading to the lastest version (128.something)

```php
        return $this->render(TheNameOfTheBundleThatUsedToWork:Course:index.html.twig', [
            'courses' => $courses,
        ]);
```

This no longer correctly links to the template and when trying to generate the template through quick fix i get a file in `null/Resources`. Seems like the plugin is lost.

**Comment by robhunt3r** [comment]
Yep, I have same problem using 0.12.128

**Comment by Haehnchen** [comment]
fixed in 0.12.129 #803

**Comment by ahonymous** [comment]
thank`s

**Comment by 0TshELn1ck** [comment]
Thank's
