### ISSUE TITLE
Default settings for Plugin missing/incorrect

### ISSUE THREAD

**Issue by iltar** [Haehnchen/idea-php-symfony2-plugin#810]
I'm having some trouble with the default settings of the plugins. For a start, while Symfony has the cache in `var/cache/` now, the default settings in the plugin point towards `app/cache/`. Every project I open/create, I have to change this.

I also _hate_ code folding, but again, I have to change this for each project. It would all be solved by adding the option to add default settings to the plugin which can be used across projects (not sure if this is possible in phpstorm for plugins).

**Comment by King2500** [comment]
Maybe this plugin could implement some default settings (File > Default Settings) and/or auto-detect Symonfy version and cache folder path.

**Comment by 20uf** [comment]
I confirm, I have noticed this bug for a while, I have identified (unless I'm mistaken) the cause.
I opened a PR #915

**Comment by 20uf** [comment]
This issue can be closed :)

**Comment by Haehnchen** [comment]
so closed ;)
