### ISSUE TITLE
transchoice missing translation with index variable

### ISSUE THREAD

**Issue by teerawutdir** [Haehnchen/idea-php-symfony2-plugin#814]
![symfony](https://cloud.githubusercontent.com/assets/6366132/20140349/43ff57be-a6bd-11e6-9aef-ccab748b05dd.png)

**Comment by snoek09** [comment]
I think I have the same issue.
Is it possible to get the list of `id` attribute values here instead of the `source` tag values?

**Comment by Haehnchen** [comment]
released
