### ISSUE TITLE
[Doctrine] autocomplete not working for getRepository(Entity::class)

### ISSUE THREAD

**Issue by mzk** [Haehnchen/idea-php-symfony2-plugin#824]
This works fine
![screen shot 2016-11-22 at 11 00 07](https://cloud.githubusercontent.com/assets/382475/20519853/d9630d6e-b0a4-11e6-894b-fd75256aaee5.png)
```php
$em->getRepository('FulfillmentUserBundle:Store')
            ->createQueryBuilder('store')
            ->andWhere('store.id');
```
but, `Entity::class` not working
![screen shot 2016-11-22 at 11 00 29](https://cloud.githubusercontent.com/assets/382475/20519861/e5d9f1f2-b0a4-11e6-9f25-652637feba2b.png)
```php
$em->getRepository(Store::class)
            ->createQueryBuilder('store')
            ->andWhere('store.');
```

PHPStorm 2016.3 EAP 163.7743.39

**Comment by Haehnchen** [comment]
released

**Comment by dewos** [comment]
Hi @Haehnchen.

Happy new year :)
Nice update, but I was wondering if it works also with ->from(Entity::class, 'e') and ->join(Entity::class, 'e', 'WITH', 'e.id = :id')

**Comment by Haehnchen** [comment]
@dewos `from` support by https://github.com/Haehnchen/idea-php-symfony2-plugin/commit/6d17c64e819106cf12077789d628f85db73d98e4
