### ISSUE TITLE
Add configuration for default configuration format

### ISSUE THREAD

**Issue by tomasfejfar** [Haehnchen/idea-php-symfony2-plugin#829]
This would be a nice DX enhancement. 

**Steps to reproduce:**
* have `services.yml`
* open any file with class inside 
* Generate → Symfony service

**Expected:**
* code at the bottom is already YAML (or there is a configuration option to make it so)
* copy and insert code

**Actual:**
* you need to click to change format to YAML
* copy and insert code

**Comment by Haehnchen** [comment]
last selected output format is known written in settings and value reused
