### ISSUE TITLE
Unrecognized Validator Constraint annotation

### ISSUE THREAD

**Issue by gadelkareem** [Haehnchen/idea-php-symfony2-plugin#831]
After upgrading to PHPStorm 2016.3.1 and Symfony plugin 0.12.131. The plugin does not recognize the Validator annotation. PHPStorm auto formatting removes the import automatically because it is marked as not used.
ex:
![screen shot 2016-12-08 at 6 48 06 pm](https://cloud.githubusercontent.com/assets/1441127/21021334/5288a69c-bd78-11e6-9ffe-f3a3de1c4aa4.png)

**Comment by gadelkareem** [comment]
NM I forgot to add Assert `@Assert\UniqueEntity`

**Comment by gadelkareem** [comment]
Still valid issue

**Comment by kasparsklavins** [comment]
Having the same problem.

**Comment by Haehnchen** [comment]
PhpStorm `2016.3.1` regression fixed by `2016.3.2` see https://github.com/Haehnchen/idea-php-annotation-plugin/issues/76
