### ISSUE TITLE
Add missed translations in inspection result

### ISSUE THREAD

**Issue by sashaaro** [Haehnchen/idea-php-symfony2-plugin#832]
I do "inspect code", but I want look "Missed translations" section. It is not work?! I want find all missed translations and fixed quickly. Seems It is not there now. Is there other way?

**Comment by Haehnchen** [comment]
TODO: Annotator -> Inspection migration

**Comment by Haehnchen** [comment]
done for Twig related inspections, PHP will follow

**Comment by Haehnchen** [comment]
done. all annotators are migrated to inspections
