### ISSUE TITLE
Service ids should be autocompleted for decorates

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-symfony2-plugin#834]
```xml
<service id="foo" decorates="|">
</service>
```

should trigger the completion.

~~Btw, it would be great to support the inner service of the decoration to avoid marking it as invalid in arguments (named ``<id>.inner`` by default, but can be overwritten by ``decorates-inner-name``)~~ already supported

**Comment by stof** [comment]
btw, it would be even better if the autocompletion could priorize services implemented the same interface than the current service.

**Comment by Haehnchen** [comment]
`priorize services` also supported here now
