### ISSUE TITLE
update failed for AnAction with ID=SymfonyWebDeploymentDownload: SERVER_CONFIG

### ISSUE THREAD

**Issue by memboc** [Haehnchen/idea-php-symfony2-plugin#837]
PhpStorm 2016.3.1
Build #PS-163.9735.1, built on December 6, 2016
JRE: 1.8.0_112-release-408-b2 x86
JVM: OpenJDK Server VM by JetBrains s.r.o

Symfony Plugin Version: 0.12.132
Exception:
update failed for AnAction with ID=SymfonyWebDeploymentDownload: SERVER_CONFIG

full trace http://pastebin.com/kwjANZYp

**Comment by vaidotas-adf** [comment]
Same issue here, error pops up every time when opening project.

**Comment by Rahelno** [comment]
I have the same problem

PhpStorm 2016.3.1
Build #PS-163.9735.1, built on December 6, 2016
Licensed to PAYMILL GmbH / Robert Hennig
You have perpetual fallback license for this version
Subscription is active until January 21, 2018
JRE: 1.8.0_112-release-408-b2 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Symfony Plugin Version: 0.12.132

Exception: 
update failed for AnAction with ID=SymfonyWebDeploymentDownload: SERVER_CONFIG

full trace http://pastebin.com/00cufpJx

**Comment by memboc** [comment]
depends from #826

**Comment by gekkota38** [comment]
Same issue here, error pops up every time when opening project.

**Comment by mu4ddi3** [comment]
same here

**Comment by Haehnchen** [comment]
fixed by 0.13.133
