### ISSUE TITLE
"create template" is not clickable

### ISSUE THREAD

**Issue by DedicatedManager** [Haehnchen/idea-php-symfony2-plugin#843]
I'm told by the Jetbrains this issue is with your plugin and I should report it to you:

I'm using Symfony (which uses twig for templates).When I hover over a template file that doesn't exist it shows a box that says "create template" a the top of two words. That phrase is not clickable. I should be able to click that phrase and create the template. I was able to find the shortcut that actually works. It took me an hour. Then I used it once and forgot it. Now I have to spend another hour looking it up. It would be nicer if I could just click that phrase.

**Comment by Haehnchen** [comment]
sry that's not what PhpStorm works. use alt+enter or the highlighted yellow icon.

**Comment by DedicatedManager** [comment]
Thanks.  I've never noticed the yellow icon.    Since you can't make that popup box clickable, you could put the shortcut in the text:

Create Template (Alt+Enter)
------------------------------
Missing Template
