### ISSUE TITLE
Possible to remove SF2-specific file types from "New" keyboard shortcut?

### ISSUE THREAD

**Issue by jtreminio** [Haehnchen/idea-php-symfony2-plugin#844]
I use `ALT+N` to create a new file, and `f` has always been tied to `File`. Now it's defaulting to `Form`, which I really don't want:

![image](https://cloud.githubusercontent.com/assets/589398/21567967/15753e0a-ce76-11e6-9a96-cac7d1cc0797.png)

Is it possible to disable all these types completely and only have the vanilla types?

**Comment by Koc** [comment]
Maybe it is better create submenu - `Symfony` and move all Symfony's stuff to it?

**Comment by jtreminio** [comment]
@Koc That's a better idea than a flag to completely remove.

I'm unsure if this is also due to the plugin, but D brings up data sources, not directory:

![image](https://cloud.githubusercontent.com/assets/589398/21904746/5166e68a-d8ca-11e6-994f-8ffb34a970ee.png)

**Comment by Haehnchen** [comment]
own menu provided
