### ISSUE TITLE
twig asset function autocomplete not working

### ISSUE THREAD

**Issue by bftanase** [Haehnchen/idea-php-symfony2-plugin#85]
Hi, 
Is it just me or there's a problem with this feature?

when I have code like `{{ asset('bundles/mybundlename/image.jp') }}` autocomplete does not trigger and also PHP Storm is highligting the asset string with a warning "Missing Asset".

Let me know what other info I can give you.

PhpStorm 6.0.2
Symfony plugin: 0.9.4
Symfony 2.3.1

**Comment by furious-snail** [comment]
In Symfony 4 it's recommended to place assets in the public/ directory. So, the plugin should check for this path also.
