### ISSUE TITLE
[Twig] Incorrect autocompletion for Twig extension

### ISSUE THREAD

**Issue by guzzlefry** [Haehnchen/idea-php-symfony2-plugin#853]
For a \Twig_Extension, when a \Twig_SimpleFunction object is returned rather than an array of \Twig_SimpleFunction objects in \Twig_Extension::getFunctions(), the function is registered for auto-completion even though Twig itself doesn't register the function.

I haven't verified this for the other get*() functions, but I suspect the issue could apply to those as well.

**Comment by Haehnchen** [comment]
indeed this is invalid php code itself, but invalid or incomplete code needs to stepover in static code analysis.
