### ISSUE TITLE
Autocompletion fails with createFormBuilder while chained method calls

### ISSUE THREAD

**Issue by LinkingYou** [Haehnchen/idea-php-symfony2-plugin#863]
I am using PhpStorm 2016.3.2 with the current symfony plugin 0.13.134 in many projects in the MacOs and Linux-Version.

Everything works fine on symfony 2.8 projects, but in symfony 3.2.x projects, the autocompletion fails in chained method calls on createFormBuilder at the fourth element:

This works fine:

        $abc = $this->createFormBuilder()
            ->add('element1', 'Symfony\Component\Form\Extension\Core\Type\TextType')
            ->add('element2', 'Symfony\Component\Form\Extension\Core\Type\TextType')
            ->add('element3', 'Symfony\Component\Form\Extension\Core\Type\TextType');

But from the fourth element, the autocompletion failed:

        $abc = $this->createFormBuilder()
            ->add('element1', 'Symfony\Component\Form\Extension\Core\Type\TextType')
            ->add('element2', 'Symfony\Component\Form\Extension\Core\Type\TextType')
            ->add('element3', 'Symfony\Component\Form\Extension\Core\Type\TextType')
            ->add('element4', 'Symfony\Component\Form\Extension\Core\Type\TextType');

**Comment by LinkingYou** [comment]
I have checked the problem again - now on an new completly new Windows environment with PhpStorm 2016.3.2 and Symfony Plugin 0.13.135.

Here is absolutly the same result.

At the fourth element in FormBuilder chained methodcall the autocompletion doesn't work :-(

It does not matter whether this element is another "add" or "getForm". Always from the fourth element the autocomplete is not working.

**Comment by Steveb-p** [comment]
I'd just like to say I got hit by this as well. However in my case, transitioning from Symfony 3.2.0 to 3.3.2 made the bug to show up.

**Comment by CyanoFresh** [comment]
Same. Just started with symfony...

**Comment by Haehnchen** [comment]
Please check against PhpStorm 2017.2 when public

**Reworked polymorphic types support**
> ... missing type in chain call if a method has a double return type, lost type with new static() call if method from base class returns $this, returning self in traits not resolved correctly, and many others

**Comment by LinkingYou** [comment]
Yes. It's working fine now in PhpStorm 2017.2 EAP.
Great job! Thank you!
