### ISSUE TITLE
Irrelevant "Missing translation domain" warning

### ISSUE THREAD

**Issue by vudaltsov** [Haehnchen/idea-php-symfony2-plugin#877]
I have the following template:

```twig
{% extends 'base.html.twig' %}

{% import 'component/macros/nav.html.twig' as nav %}

{% block main %}
    <nav class="tabs mt-1 mb-2 font-weight-bold">
        {{ nav.link('title.profile'|trans, path('profile'), '/^profile(_locked|)$/') }}
        {{ nav.link('title.attendees_and_payment'|trans, path('profile_attendees'), '/^profile_attendees$/') }}
    </nav>
{% endblock %}
```

The third argument of the `nav.link` macro is yellow with the warning: Missing translation domain.

<img width="1006" alt="2017-02-28 1 51 10" src="https://cloud.githubusercontent.com/assets/2552865/23383630/7725cba4-fd58-11e6-8cd2-f375775df2dc.png">

**Comment by Haehnchen** [comment]
thx, related to #814 same magic regular expression i need to fix
