### ISSUE TITLE
Short block tag autocomplete

### ISSUE THREAD

**Issue by vudaltsov** [Haehnchen/idea-php-symfony2-plugin#883]
Autocomplete for `'...'|trans` and `path('...')` does not work for short block declarations:

```twig
{% block title ''|trans %}
```

Although missing routes and translations are properly marked with a yellow warning.

**Comment by Haehnchen** [comment]
properly a bug in api. completion event is fired, but blocked by block name completion

**Comment by Haehnchen** [comment]
nothing can be done here, as completion usage is blocked by Twig plugin
