### ISSUE TITLE
asset() inside html comments for IE

### ISSUE THREAD

**Issue by vudaltsov** [Haehnchen/idea-php-symfony2-plugin#887]
```html
<!--[if lt IE 9]>
<script src="{{ asset('vendor/bower_components/html5shiv/dist/html5shiv.js') }}"></script>
<![endif]-->
```

<img width="741" alt="2017-03-14 16 37 00" src="https://cloud.githubusercontent.com/assets/2552865/23903121/7d73e4c8-08d4-11e7-84cd-99b90665de9a.png">

**Comment by Haehnchen** [comment]
wrong implementation by Twig Plugin, no way to correct this by this plugin
