### ISSUE TITLE
[Twig] Allow usage of new Twig 2.0 function in Extension parser

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#893]
`Twig_Function`, `Twig_Filter`, `Twig_Test` were added in favoir of `*Simple*` ones

**Comment by Haehnchen** [comment]
see https://github.com/twigphp/Twig/blob/2.x/lib/Twig/Extension/Core.php

**Comment by stof** [comment]
I suggest also adding support for the new namespaced class names (which are aliases for existing `Twig_*` classes), which will make the code ready for Twig 3 (where only namespaced names will be kept AFAIK).

Symfony switched to namespaced names when referencing Twig classes.

**Comment by Haehnchen** [comment]
thx for this note. also easy. found some clear namespaces:

```php
\Twig\TwigFilter
\Twig\TwigFunction
\Twig\TwigTest
```

**Comment by Haehnchen** [comment]
so done
