### ISSUE TITLE
[PHPStorm][annotations] Missing route with "Test"

### ISSUE THREAD

**Issue by jbartfay** [Haehnchen/idea-php-symfony2-plugin#897]
Routes are not being indexed if controller file name contains "Test".

I have a controller called TestPageController.php that displays TestPage entities. Routes are defined with '@Route("foo", name="bar")' annotations. Route hints in PHP and twig don't work.  If I rename the controller so that the file name does not contain "Test", then hinting works.

I've narrowed it down to https://github.com/Haehnchen/idea-php-symfony2-plugin/blob/master/src/fr/adrienbrault/idea/symfony2plugin/stubs/indexes/ContainerBuilderStubIndex.java#L115 (isValidForIndex method)

Isn't it a little aggressive to ignore anything with "Test" in its name?

Either way, thanks for the excellent plugin.

**Comment by Haehnchen** [comment]
done
