### ISSUE TITLE
Support Optional class for named services

### ISSUE THREAD

**Issue by dewos** [Haehnchen/idea-php-symfony2-plugin#902]
Maybe an autocoplemte #Class \ #Interface for service name.

````yaml

AppBundle\EventListener\UserManager:
        tags:  ['kernel.event_subscriber']
````

http://symfony.com/blog/new-in-symfony-3-3-optional-class-for-named-services

**Comment by lunetics** [comment]
+1, was just about to create an issue for that. Would love to have that "clickable"

**Comment by dewos** [comment]
@lunetics yeah, also < s.3.3

**Comment by GeoffreyHervet** [comment]
@lunetics same for me !

**Comment by lunetics** [comment]
Thanks @Haehnchen !!! can be closed then!

**Comment by dewos** [comment]
Fixed, thanks @Haehnchen
