### ISSUE TITLE
[Twig] Wrong type hint for app variable in Symfony 2.7+ and 3.x

### ISSUE THREAD

**Issue by King2500** [Haehnchen/idea-php-symfony2-plugin#903]
Starting from Symfony 2.7 the global Twig variable `app` is from type `Symfony\Bridge\Twig\AppVariable` instead of `Symfony\Bundle\FrameworkBundle\Templating\GlobalVariables`.

This did not made any problem, since until Sf 3.2 the methods of both classes are the same. But starting from Sf 3.3 there will be a method called `getFlashes` (see https://github.com/symfony/symfony/pull/21819) which is only defined in `AppVariable`.

Since the `AppVariable` class only exists since Sf 2.7, the best solution would be to (dynamically) read the configuration from `src/Symfony/Bundle/TwigBundle/Resources/config/twig.xml` and find the actual class of `app` variable:
![image](https://cloud.githubusercontent.com/assets/4896363/24333513/76b4905e-1259-11e7-9d12-a0b213d6de25.png)

References:
https://github.com/symfony/symfony/blob/2.6/src/Symfony/Bundle/TwigBundle/Resources/config/twig.xml
https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/TwigBundle/Resources/config/twig.xml

**Comment by exactquery** [comment]
Ideally, all service configurations as well as the application configuration should be taken into account as well - probably in that order (Twig Service -> User Configured Services -> config.yml globals)

For instance, if someone overrides the "twig.app_variable" service with their own service, this should take precedence.  I have done this in a few projects; my service simply extended the AppVariable class. 

Another way I've overridden the 'app' variable is to add 'app' key to the Twig Globals key in config.yml that points to my own service/class (which extends AppVariable).  This is also not detected by this plugin, but probably should be.

**Comment by Haehnchen** [comment]
already fixed
