### ISSUE TITLE
Twig macro autocompletion not working as advertised

### ISSUE THREAD

**Issue by Danita** [Haehnchen/idea-php-symfony2-plugin#924]
Hi! Thanks for this wonderful plugin. I discovered the documentation says it supports twig macro autocompletion but it never worked in any of my projects so far:

```twig
{% extends 'AppBundle::base.html.twig' %}
{% import 'AppBundle::macros.html.twig' as macros %}

{% block body %}
  <p>{{ macros.  // NO AUTOCOMPLETION HERE  }}</p>
{% endblock %}
``` 

Using v0.14.142

Thanks!

**Comment by Danita** [comment]
I just read this on the README

> Many features require the app/cache/dev/appDevDebugProjectContainer.xml file to exist. It is generated when you boot your app in dev environment (open /app_dev.php in a browser or php app/console).

Could it be this? I'm using Vagrant, so I don't have the cache autogenerated files on my dev machine. 

Also: PHPStorm 2017.1.3, Windows 7 x64.

**Comment by Danita** [comment]
Wasn't that. Downloaded the file from the VM and I now get services autocompletion, but still no macro autocomplete. 😭

**Comment by Haehnchen** [comment]
confirming this is not working. an untested feature that is broken by some previous Twig Plugin changes. 😭

**Comment by Danita** [comment]
Yeah, you rock! Thanks!! :metal:
