### ISSUE TITLE
Types resolving breaks since last plugin update

### ISSUE THREAD

**Issue by Koc** [Haehnchen/idea-php-symfony2-plugin#926]
```
PhpStorm 2017.1.3
Build #PS-171.4424.11, built on April 26, 2017

JRE: 1.8.0_112-release-736-b21 x86
JVM: OpenJDK Server VM by JetBrains s.r.o
Windows 8.1 6.3
```

I've just installed build 0.14.143 and have some error: `$this->get()` autocompletes services but types of this services are not resolved properly. I've tryed clear PS cache - it didn't help.

![2017-05-07_15-34-42](https://cloud.githubusercontent.com/assets/191082/25780968/dabf285a-333a-11e7-9464-bf42136b7498.png)

**Comment by Koc** [comment]
But `ctrl+q` displays correct type

![2017-05-07_15-36-34](https://cloud.githubusercontent.com/assets/191082/25780971/0566e9ee-333b-11e7-81ac-ca22109451a2.png)

**Comment by Haehnchen** [comment]
indeed what a crazy shit :(. Intellij Plattform is working but not PhpStorm

**Comment by Haehnchen** [comment]
so its a cross implementation issue between plugins using `typeProvider2` the new `typeProvider3` implementation. @Koc can you please try to disable foreign plugin one by one to see which breaks. On my side `Shopware Plugin` was the criminals.

**Comment by Haehnchen** [comment]
i dropped `0.14.143` and moved completely to `typeProvider3` for this plugin in `0.14.144` now

**Comment by Koc** [comment]
I've tryed disable a lot of plugins (orocrm, magicento, magicento2, php inspection) but it didn't help. Will try fresh build, hope it fixes

**Comment by Haehnchen** [comment]
also reported to JetBrains https://youtrack.jetbrains.com/issue/WI-36271

**Comment by Koc** [comment]
can confirm: fixed. @Haehnchen thank you for fast reaction

**Comment by Haehnchen** [comment]
@Koc no. thank you for your feedback, else a problem for +10k devs tomorrow :)

**Comment by felicitus** [comment]
In my case, the culprit was the OXID PHP Plugin - disabled it and now completion works again :+1:
