### ISSUE TITLE
Symfony Plugin was not loaded

### ISSUE THREAD

**Issue by vaidotas-adf** [Haehnchen/idea-php-symfony2-plugin#928]
Plugin "Symfony Plugin" was not loaded: required plugin "de.espend.idea.php.annotation" not installed.
Symfony plugin version 0.14.144
PhpStorm 2017.1.3

**Comment by Koc** [comment]
you need install php annotations plugin first https://plugins.jetbrains.com/plugin/7320-php-annotations
