### ISSUE TITLE
Plugin "Symfony Plugin" was not loaded: required plugin "de.espend.idea.php.annotation" not installed. 

### ISSUE THREAD

**Issue by metaer** [Haehnchen/idea-php-symfony2-plugin#930]
Message in Phpstorm

_Problems found loading plugins: Plugin "Symfony Plugin" was not loaded: required plugin "de.espend.idea.php.annotation" not installed._

**Comment by metaer** [comment]
In description of symfony plugin:
_(Optional) Install PHP Annotations_

Is it optional or required?

**Comment by shvrcho** [comment]
looks like required because installing PHP Annotations fixed the problem for me

**Comment by ViceDigitWeb** [comment]
@shvrcho thank you, i confirm it's working also for me :).

**Comment by metaer** [comment]
Yes, It works after installing PHP Annotations

If it is required - may be it need to be fixed in the plugin description:
![symfony_plugin](https://cloud.githubusercontent.com/assets/6103208/25951320/eeb8678a-3665-11e7-9e8d-f6c137a6675d.png)

If it is optional - this issue is a bug.

In any case, thanks for this plugin

**Comment by pschulz** [comment]
According to the release notes for v0.14.143
> - Move PHP Annotation plugin `de.espend.idea.php.annotation` from soft to hard dependency to drop duplicate code usages #448
I would say the PHP Annotations isn't optional any longer, so the Install documentation should be changed.

Reinstalling the plugin automatically adds the dependency, after asking for confirmation.
For existing installations there should be a more concise hint, that the Annotations plugin must be installed.

On the other hand, it would be a nice feature of the IDEA platform to resolve a plugin's dependencies automatically on its update. I believe aside the documentation, this is the major pain of this issue.

**Comment by matiux** [comment]
I have the same problem even after reinstalling the plugin.

PhpStorm 2018.1 EAP
Build #PS-181.3494.16, built on February 7, 2018

**Comment by johnutzm** [comment]
@matiux please check  Haehnchen/idea-php-annotation-plugin#105
