### ISSUE TITLE
Exception in PhpStorm

### ISSUE THREAD

**Issue by lo-cwb** [Haehnchen/idea-php-symfony2-plugin#938]
Hi,

Each time I use the symfony plugin an exception is raised.

> PhpStorm 2017.1.4
> Build #PS-171.4694.2, built on May 16, 2017
> JRE: 1.8.0_112-release-736-b21 x86_64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Mac OS X 10.12.5

Comments of the exception:

> Worker exited due to exception: Argument for @NotNull parameter 'key' of com/intellij/util/indexing/impl/MapReduceIndex.getData must not be null

Details:

> Worker exited due to exception: Argument for @NotNull parameter 'key' of com/intellij/util/indexing/impl/MapReduceIndex.getData must not be null
> java.lang.IllegalArgumentException: Argument for @NotNull parameter 'key' of com/intellij/util/indexing/impl/MapReduceIndex.getData must not be null
> 	at com.intellij.util.indexing.impl.MapReduceIndex.getData(MapReduceIndex.java)
> 	at com.intellij.util.indexing.InvertedIndexUtil.collectInputIdsContainingAllKeys(InvertedIndexUtil.java:43)
> 	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1062)
> 	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:841)
> 	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1068)
> 	at com.intellij.util.indexing.FileBasedIndexImpl.processFilesContainingAllKeys(FileBasedIndexImpl.java:928)
> 	at com.intellij.util.indexing.FileBasedIndexImpl.getFilesWithKey(FileBasedIndexImpl.java:1103)
> 	at fr.adrienbrault.idea.symfony2plugin.translation.dict.TranslationUtil.getTranslationPsiElements(TranslationUtil.java:124)
> 	at fr.adrienbrault.idea.symfony2plugin.templating.TranslationTagCompletionRegistrar$MyTranslationGotoCompletionProvider.getPsiTargets(TranslationTagCompletionRegistrar.java:111)
> 	at fr.adrienbrault.idea.symfony2plugin.codeInsight.navigation.GotoHandler.getGotoDeclarationTargets(GotoHandler.java:34)
> 	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:289)
> 	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:523)
> 	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:502)
> 	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$2200(CtrlMouseHandler.java:103)
> 	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.a(CtrlMouseHandler.java:834)
> 	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2900(CtrlMouseHandler.java:774)
> 	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:819)
> 	at com.intellij.openapi.progress.util.ReadTask.a(ReadTask.java:66)
> 	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:48)
> 	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:243)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:192)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:192)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:241)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:47)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:192)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> 
> 
> java.lang.IllegalArgumentException: Argument for @NotNull parameter 'key' of com/intellij/util/indexing/impl/MapReduceIndex.getData must not be null
> 	at com.intellij.util.indexing.impl.MapReduceIndex.getData(MapReduceIndex.java)
> 	at com.intellij.util.indexing.InvertedIndexUtil.collectInputIdsContainingAllKeys(InvertedIndexUtil.java:43)
> 	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1062)
> 	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:841)
> 	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1068)
> 	at com.intellij.util.indexing.FileBasedIndexImpl.processFilesContainingAllKeys(FileBasedIndexImpl.java:928)
> 	at com.intellij.util.indexing.FileBasedIndexImpl.getFilesWithKey(FileBasedIndexImpl.java:1103)
> 	at fr.adrienbrault.idea.symfony2plugin.translation.dict.TranslationUtil.getTranslationPsiElements(TranslationUtil.java:124)
> 	at fr.adrienbrault.idea.symfony2plugin.templating.TranslationTagCompletionRegistrar$MyTranslationGotoCompletionProvider.getPsiTargets(TranslationTagCompletionRegistrar.java:111)
> 	at fr.adrienbrault.idea.symfony2plugin.codeInsight.navigation.GotoHandler.getGotoDeclarationTargets(GotoHandler.java:34)
> 	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:289)
> 	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:523)
> 	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:502)
> 	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$2200(CtrlMouseHandler.java:103)
> 	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.a(CtrlMouseHandler.java:834)
> 	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2900(CtrlMouseHandler.java:774)
> 	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:819)
> 	at com.intellij.openapi.progress.util.ReadTask.a(ReadTask.java:66)
> 	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:48)
> 	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:243)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:192)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:192)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:241)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:47)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:192)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> 
> 
> java.lang.IllegalArgumentException: Argument for @NotNull parameter 'key' of com/intellij/util/indexing/impl/MapReduceIndex.getData must not be null
> 	at com.intellij.util.indexing.impl.MapReduceIndex.getData(MapReduceIndex.java)
> 	at com.intellij.util.indexing.InvertedIndexUtil.collectInputIdsContainingAllKeys(InvertedIndexUtil.java:43)
> 	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1062)
> 	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:841)
> 	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1068)
> 	at com.intellij.util.indexing.FileBasedIndexImpl.processFilesContainingAllKeys(FileBasedIndexImpl.java:928)
> 	at com.intellij.util.indexing.FileBasedIndexImpl.getFilesWithKey(FileBasedIndexImpl.java:1103)
> 	at fr.adrienbrault.idea.symfony2plugin.translation.dict.TranslationUtil.getTranslationPsiElements(TranslationUtil.java:124)
> 	at fr.adrienbrault.idea.symfony2plugin.templating.TranslationTagCompletionRegistrar$MyTranslationGotoCompletionProvider.getPsiTargets(TranslationTagCompletionRegistrar.java:111)
> 	at fr.adrienbrault.idea.symfony2plugin.codeInsight.navigation.GotoHandler.getGotoDeclarationTargets(GotoHandler.java:34)
> 	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:289)
> 	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:523)
> 	at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:502)
> 	at com.intellij.codeInsight.navigation.CtrlMouseHandler.access$2200(CtrlMouseHandler.java:103)
> 	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.a(CtrlMouseHandler.java:834)
> 	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider.access$2900(CtrlMouseHandler.java:774)
> 	at com.intellij.codeInsight.navigation.CtrlMouseHandler$TooltipProvider$1.performInReadAction(CtrlMouseHandler.java:819)
> 	at com.intellij.openapi.progress.util.ReadTask.a(ReadTask.java:66)
> 	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:48)
> 	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:243)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:192)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:192)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.a(ProgressIndicatorUtils.java:241)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.access$000(ProgressIndicatorUtils.java:47)
> 	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$4.run(ProgressIndicatorUtils.java:192)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)

Thanks

**Comment by Haehnchen** [comment]
duplicate #927
