### ISSUE TITLE
Aliases to private services don't autocomplete

### ISSUE THREAD

**Issue by weaverryan** [Haehnchen/idea-php-symfony2-plugin#943]
Hi guys!

We just got a question on KnpU about why (at least in 3.3) `$this->container->get('templating')` does not auto-complete and reports as a "missing service".

The reason is that `templating` is an alias to `templating.engine.twig` and `templating.engine.twig` is a *private* service. When I manually change `templating.engine.twig` to public, auto-completion works instantly.

Is it possible that the plugin is incorrectly hiding an alias if the final service is private? The alias itself can be public/private, and that should be used.

Thanks!

**Comment by Haehnchen** [comment]
reworked `appDevDebugProjectContainer.xml` handling with #618. also tested against Symfony 3.3 and `templating` is working.

**Comment by weaverryan** [comment]
Indeed fixed! Thanks!
