### ISSUE TITLE
kernel parameters are missing from the DIC completion

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-symfony2-plugin#950]
There are a few parameters set by the kernel directly:

- `kernel.environment`
- `kernel.debug`
- `kernel.root_dir`
- `kernel.cache_dir`
- `kernel.logs_dir`
- `kernel.project_dir` (as of Symfony 3.3)
- `kernel.name`
- `kernel.bundles`
- `kernel.charset`

The plugin does not provide completion for them currently (it may be doing it based on the compiled container in the cache, but I'm working on a bundle currently and so I don't have the cached compiled container). It would be great if it could do it.

If you want to automate the loading instead of hardcoding the list in the plugin, the implement lives in `\Symfony\Component\HttpKernel\Kernel::getKernelParameters`.

**Comment by Haehnchen** [comment]
done
