### ISSUE TITLE
Service visibility does not work when using defaults to make them private by default

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-symfony2-plugin#954]
Currently, the code assumes that a service which does not have the `public` attribute defined on it is public.
But as of Symfony 3.3, this assumption is not good anymore. When the public attribute is not set on the `<service>` tag, the value must first be checked in `<defaults>` in the same file before the fallback to public (rules is the same for YAML file, by adapting to the YAML syntax of course)

**Comment by Haehnchen** [comment]
done
