### ISSUE TITLE
[Symfony 3.3] Argument hint must support yaml class shortcut

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-symfony2-plugin#958]
```
  AppBundle\Menu\RouteAclAccess:
    arguments: ['@router', '@security.authorization_checker']
```

Currently no argument hints for arguments

**Comment by stof** [comment]
XML also allows to omit the `class` configuration when the id is the class name, not only YAML (even PHP with `new Definition()` supports it)
