### ISSUE TITLE
Autocompletion for controller names in routing files is broken for namespaced classes

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-symfony2-plugin#961]
The autocompletion for the `_controller` key in my YAML routing file just suggested me è WebBundle:AccountManagement/Organization:index`
This is broken. The namespace separator is `\` in PHP, not `/`. So the right string is `WebBundle:AccountManagement\Organization:index`

**Comment by Haehnchen** [comment]
done. changed the behavior to `\` as also described in:
https://github.com/symfony/symfony/issues/2424
https://github.com/symfony/symfony/pull/2429
