### ISSUE TITLE
Autocompletion for Twig tests is missing all core tests

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-symfony2-plugin#962]
Autocompletion in `{% if foo is not <caret> %}` does not include tests defined by Twig_Extension_Core.

I'm using Twig 2.x in case this is related to a difference between 1.x and 2.x.

**Comment by Haehnchen** [comment]
duplicate by #893 changes to support https://github.com/twigphp/Twig/blob/2.x/lib/Twig/Extension/Core.php

**Comment by stof** [comment]
is there any chance to get support for them ?

**Comment by Haehnchen** [comment]
just started, almost ready ;)
