### ISSUE TITLE
Twig 2 supports hassers for the attribute operator

### ISSUE THREAD

**Issue by stof** [Haehnchen/idea-php-symfony2-plugin#964]
Twig 1 only supports getters and issers for the attribute operator (`.`), but Twig 2 added support for hassers.
Currently the bundle marks this as an undefined property (and generates the access with `hasFoo` on autocomplete). It would be great if it could change its behavior based on the Twig version instead.

**Comment by Haehnchen** [comment]
related https://github.com/twigphp/Twig/pull/1969

**Comment by Haehnchen** [comment]
done. but without Twig version check, overhead for this feature
