### ISSUE TITLE
Detect templates when using `__invoke` controllers

### ISSUE THREAD

**Issue by ruudk** [Haehnchen/idea-php-symfony2-plugin#980]
I'm using controllers that only contain 1 action, called: `__invoke`. 

For example:

```php
<?php

namespace AdminBundle\Controller\Cases;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

class ShowCaseController extends BaseController
{
    /**
     * @Route("/cases/show/{id}", name="case_show")
     * @Template
     */
    public function __invoke()
    {
    }
}
```

The template is located in `AdminBundle/Resources/views/Cases/ShowCase.html.twig`.

Symfony / SensioFrameworkExtraBundle perfectly pick this up. But this amazing plugin doesn't :( 

Whenever I click on `@Template` it opens the Annotation instead of showing the dropdown with the Twig template.

**Comment by Haehnchen** [comment]
now its a little bit more amazing ;)

**Comment by ruudk** [comment]
You are awesome! Put a small donation in, thanks ✌️
