### ISSUE TITLE
Twig path directory separator must be "\" to be clickable

### ISSUE THREAD

**Issue by kroshp** [Haehnchen/idea-php-symfony2-plugin#995]
Inside twig template:

This path is not clickable:
`{{ render(controller('Vendor:Folder/Controller:action')) }}`

This path is clickable:
`{{ render(controller('Vendor:Folder\Controller:action')) }}`

Env:
PhpStorm 2017.2.1
Build #PS-172.3544.41, built on August 2, 2017
JRE: 1.8.0_152-release-915-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
Symfony plugin Version: 0.14.150

**Comment by stof** [comment]
well, the second one is the right path anyway. Namespace separators are `\` in PHP, not `/`

**Comment by Haehnchen** [comment]
both is supported now and tested but PHP namespace still wins for completion

**Comment by Haehnchen** [comment]
done
