### ISSUE TITLE
@Template() complains about non-existing template, but it does work

### ISSUE THREAD

**Issue by rudiedirkx** [Haehnchen/idea-php-symfony2-plugin#999]
* PHP Storm 2017.2.2 EAP
* Symfony plugin 0.14.150
* Project is Symfony 2.8.x
* No plugin errors, I think?

`sensio/framework-extra-bundle` defines a `@Template` annotation to magically use the correct template. This works for every action in my controller, but the plugin complains about the template not existing for `editAction`. The template does exist, and works.

When I use the inspection action it wants to make `ed.html.twig`. Where is the `it` ?
If I rename the action to `edit2Action`, it wants to make `edit2.html.twig`, which is correct.
If I rename the action to `edititAction`, it wants to make `ed.html.twig` again, which is wrong.

The rest of the actions are fine (showAction, newAction, indexAction etc).

This happened in 2017.2.1 EAP and 2017.2 (not EAP) too. I'm not sure about before then...

(For me: `BriefsjabloonController::editAction`)

**Comment by rudiedirkx** [comment]
Actual use case - warning:

![screen-ps-sf-1](https://user-images.githubusercontent.com/168024/29212604-c4eb8e64-7e9f-11e7-93c6-b1ca4858cb9c.png)

Actual use case - inspection action:

![screen-ps-sf-2](https://user-images.githubusercontent.com/168024/29212602-c4e13a18-7e9f-11e7-837f-bf9ff7d904a6.png)

`edit2Action` inspection action:

![screen-ps-sf-3](https://user-images.githubusercontent.com/168024/29212601-c4cea416-7e9f-11e7-9b57-7e4985f84c93.png)

`edititAction` inspection action:

![screen-ps-sf-4](https://user-images.githubusercontent.com/168024/29212603-c4eb0a84-7e9f-11e7-9881-311698abdbea.png)

**Comment by druidvav** [comment]
Too bad there is no solution for that...

**Comment by Haehnchen** [comment]
fixed shame on me :)
